export type IdeologyAxis = string;
export type IdeologyTag = string;
export const IDEOLOGY_BASES = ["declared", "editorial", "observed", "insufficient_evidence"] as const;
export type IdeologyBasis = (typeof IDEOLOGY_BASES)[number];
export const PUBLIC_VERIFICATION_STATUSES = ["blue", "organization", "government", "not_verified", "unknown"] as const;
export type PublicVerificationStatus = (typeof PUBLIC_VERIFICATION_STATUSES)[number];
export type BlueCheckStatus = PublicVerificationStatus;
export const SUBSCRIPTION_TIERS = ["unknown", "free", "basic", "premium", "premium_plus", "organization"] as const;
export type SubscriptionTier = (typeof SUBSCRIPTION_TIERS)[number];
export type AccountSubscriptionEvent = {
    id: number;
    tier: SubscriptionTier;
    effectiveAt: number;
    createdAt: number;
    updatedAt: number;
};
export type AccountSubscriptionState = {
    tier: SubscriptionTier;
    observedAt: number;
    historyComplete: boolean;
};
export type SourceProfile = {
    identityHandle?: string;
    niche?: string;
    ideology?: IdeologyAxis;
    ideologyTags?: IdeologyTag[];
    ideologyConfidence?: number;
    ideologyBasis?: IdeologyBasis;
    ideologyReason?: string;
    tone?: string;
    topics?: string[];
    certainty?: string;
    origin?: "seed" | "manual" | "discovered";
    status?: "candidate" | "active";
    pinned?: boolean;
    avatarUrl?: string;
    bio?: string;
    followers?: number;
    parentHandles?: string[];
    evidenceWeight?: number;
    lastEvidenceAt?: number;
    sourceScore?: number;
    sourceConfidence?: number;
    sourceRisk?: number;
    scoreReason?: string;
    scoreModel?: string;
    lastSeenAt?: number;
    lastScoredAt?: number;
    lowScoreStreak?: number;
    historicalPerformance?: number | null;
    blueCheckStatus?: BlueCheckStatus;
    sourceRelevanceSource?: "jev" | "openai" | "openai_fallback";
    jevRelevance?: number;
    jevCategoryScores?: Record<string, number>;
    jevDiagnostics?: string[];
};
export type SourceConfig = {
    handle: string;
    name: string;
    enabled: boolean;
    maxPosts: number;
    rightsStatus: "cleared" | "unknown" | "prohibited";
    profile: SourceProfile;
};
export type DeletedSource = {
    handle: string;
    score: number;
    reason: string;
    model: string;
    deletedAt: number;
};
export type ObservedPost = {
    externalId: string;
    sourceHandle: string;
    authorHandle: string;
    statusUrl: string;
    text: string;
    createdTimestamp: number;
    likes: number;
    replies: number;
    reposts: number;
    quotes: number;
    views: number;
    followers?: number;
    blueCheckStatus?: BlueCheckStatus;
    mediaCount: number;
    mediaJson: string;
    rawJson: string;
    score: number;
    scoreReason: string;
    sensitive: boolean;
    clusterKey: string;
    relevanceScore?: number | null;
    relevanceSource?: string | null;
    relevanceJson?: string | null;
    relevanceAt?: number | null;
};
export type RecentPost = ObservedPost & {
    observedAt: number;
    draftText: string;
    draftStatus: string;
    publishStatus: string;
};
export type ActivityPoint = {
    label: string;
    observed: number;
    opportunities: number;
};
export type DashboardSummary = {
    generatedAt: number;
    dbAvailable: boolean;
    dbError?: string;
    sourcesConfigured: number;
    sourcesObserved: number;
    postsObserved: number;
    postsLast24h: number;
    opportunities: number;
    attemptsPending: number;
    publishedConfirmed: number;
    publishBlocked: number;
    automationRuntime: {
        owner: "worker" | "web" | "none";
        heartbeatAt: number | null;
        healthy: boolean;
        lagSeconds: number | null;
    };
    automationEnabled: boolean;
    openaiConfigured: boolean;
    aiEnabled: boolean;
    aiConfigured: boolean;
    aiProvider: "api" | "compatible" | "codex" | "anthropic" | "chatgpt";
    officialPublisherConfigured: boolean;
    recentPosts: RecentPost[];
    activity: ActivityPoint[];
    lastRun: {
        status: string;
        finishedAt: number;
        sourceCount: number;
        postsSeen: number;
        postsNew: number;
        errors: string;
    } | null;
};
export const AUTOMATION_TASK_IDS = ["monitor_engine", "source_scan", "source_liveness", "queue_worker", "reconciliation", "account_inference"] as const;
export type AutomationTaskId = (typeof AUTOMATION_TASK_IDS)[number];
export type AutomationTaskStatus = "never" | "running" | "success" | "partial" | "failed" | "skipped";
export type AutomationTaskSchedule = {
    id: AutomationTaskId;
    enabled: boolean;
    intervalSeconds: number;
    nextRunAt: number;
    lastRunAt: number;
    lastStatus: AutomationTaskStatus;
    updatedAt: number;
};
export type AutomationLog = {
    id: number;
    taskId: AutomationTaskId;
    status: AutomationTaskStatus;
    startedAt: number;
    finishedAt: number | null;
    message: string;
    details: Record<string, unknown>;
};
export type Account = {
    id: number;
    ownerUserId?: string | null;
    accountKey: string;
    handle: string;
    displayName: string;
    enabled: boolean;
    defaultAccount: boolean;
    automationMode: "manual" | "auto";
    dailyLimit: number;
    capabilities: string[];
    styleProfile: Record<string, unknown>;
    subscriptionHistory: AccountSubscriptionEvent[];
    subscriptionState: AccountSubscriptionState;
    publicVerificationStatus?: PublicVerificationStatus;
    updatedAt: number;
};
export const CATEGORY_BASE_STRATEGIES = ["news", "politics", "technology", "finance", "sports", "entertainment", "meme", "shitpost", "generic"] as const;
export type CategoryBaseStrategy = (typeof CATEGORY_BASE_STRATEGIES)[number];
export const CATEGORY_CLUSTER_STRATEGIES = ["event", "topic", "meme", "conversation", "format", "hybrid"] as const;
export type CategoryClusterStrategy = (typeof CATEGORY_CLUSTER_STRATEGIES)[number];
export const CATEGORY_VERIFICATION_MODES = ["strict", "moderate", "minimal", "none"] as const;
export type CategoryVerificationMode = (typeof CATEGORY_VERIFICATION_MODES)[number];
export type CategoryDefinition = {
    id: number;
    slug: string;
    name: string;
    enabled: boolean;
    builtIn: boolean;
    baseStrategy: CategoryBaseStrategy;
    clusterStrategy: CategoryClusterStrategy;
    verificationMode: CategoryVerificationMode;
    description: string;
    positiveExamples: string[];
    negativeExamples: string[];
    keywords: string[];
    excludedKeywords: string[];
    seedHandles: string[];
    defaultFormats: string[];
    sourcePolicy: Record<string, unknown>;
    riskPolicy: Record<string, unknown>;
    scoringPolicy: Record<string, unknown>;
    publishingPolicy: Record<string, unknown>;
    aiContext: string;
    createdAt: number;
    updatedAt: number;
    ownerUserId?: string | null;
    accountId?: number | null;
};
export type AccountCategoryConfig = {
    accountId: number;
    categoryId: number;
    categorySlug: string;
    categoryName: string;
    enabled: boolean;
    primary: boolean;
    weight: number;
    priority: number;
    publishThreshold: number | null;
    dailyBudget: number | null;
    styleOverride: Record<string, unknown>;
    aiRouteOverride: Record<string, unknown>;
    source?: "manual" | "inferred" | "imported";
    userModifiedAt?: number | null;
};
export type AccountCategoryInferenceResult = {
    status: "ready" | "insufficient_evidence";
    contentLanguage: string;
    suggestions: Array<{
        categoryId: number;
        slug: string;
        name: string;
        confidence: number;
        evidence: string[];
    }>;
};
export type AccountCategoryInferenceJob = {
    id: number;
    accountId: number;
    status: string;
    version: number;
    updatedAt: number;
    result: AccountCategoryInferenceResult | null;
};
export type SourceCategoryConfig = {
    accountId?: number;
    sourceHandle: string;
    categoryId: number;
    categorySlug: string;
    categoryName: string;
    monitoringTier: "A" | "B" | "C";
    discoveryWeight: number;
    categoryReputation: number | null;
    enabled: boolean;
    lastEvidenceAt: number;
};
export type Competitor = {
    id: number;
    handle: string;
    name: string;
    category: string;
    enabled: boolean;
    initializedAt: number;
    lastSuccessAt: number;
    lastError: string;
    createdAt: number;
    updatedAt: number;
};
export type PublicMetrics = {
    likes: number;
    replies: number;
    reposts: number;
    quotes: number;
    views: number;
    pollVotes: number;
};
export type WritingSkill = {
    id: "newsroom-style" | "humanize-writing";
    name: string;
    sourceUrl: string;
    reviewedRevision: string;
    enabled: boolean;
    instructions: string;
};
export type WritingStyleSettings = {
    exampleStyle: Record<string, unknown>;
    skills: WritingSkill[];
};
export type MarketItem = Omit<RecentPost, "rawJson"> & {
    momentum: number;
    freshness: number;
    velocity: number;
    relevance: number;
    risk: number;
    engagementRate: number;
    engagements: number;
    hit: boolean;
    marketStatus: "new" | "drafted" | "queued" | "published" | "ignored";
    decision: MarketDecision;
    scoreEvidence: ScoreEvidence;
    jevRelevance: number | null;
    jevRelevanceFactor: number;
    jevRelevanceSource: string;
    jevRelevanceAt: number;
    jevRelevanceApplied: boolean;
};
export const MARKET_VIEWS = ["opportunities", "observed", "rejected", "sensitive"] as const;
export type MarketView = typeof MARKET_VIEWS[number];
export type MarketDecision = "opportunity" | "below_threshold" | "expired" | "processed" | "not_eligible_evidence" | "sensitive";
export type MarketInbox = {
    items: MarketItem[];
    total: number;
    counts: {
        opportunities: number;
        observed: number;
        rejected: number;
        sensitive: number;
    };
};
export type ScoreEvidence = {
    kind: "deterministic" | "hybrid" | "heuristic";
    momentum: number;
    ai: number;
    risk: number;
    confidence: number;
    model: string;
    reason: string;
    categories: string[];
    breaking: boolean;
    breakingReason: string;
};
export type DraftPerformanceBaseline = {
    scope: "account_category_format" | "account_format" | "account" | "none";
    samples: number;
    medianViews: number | null;
    medianLikes: number | null;
    medianReplies: number | null;
    medianReposts: number | null;
    medianQuotes: number | null;
    medianEngagementRate: number | null;
};
export type DraftEvaluation = {
    id: number;
    draftId: number;
    accountId: number | null;
    categorySlug: string;
    mode: "shadow_calibrated" | "shadow_cold_start";
    score: number;
    confidence: number;
    predictedResidual: number | null;
    baseline: DraftPerformanceBaseline;
    predictedViews: number | null;
    predictedReplies: number | null;
    predictedReposts: number | null;
    predictedQuotes: number | null;
    features: Record<string, unknown>;
    semantic: Record<string, unknown>;
    helped: string[];
    hurt: string[];
    createdAt: number;
    updatedAt: number;
};
export type DraftRecord = {
    id: number;
    batchId: string;
    origin: string;
    prompt: string;
    provider: string;
    model: string;
    variantMode: string;
    sourceHandle: string;
    sourceUrl: string;
    externalId: string;
    accountId: number | null;
    accountHandle: string;
    format: string;
    text: string;
    status: string;
    gateReason: string;
    score: number;
    evaluation: DraftEvaluation | null;
    createdAt: number;
    updatedAt: number;
};
export type AutomationJob = {
    id: number;
    draftId: number;
    accountId: number | null;
    accountHandle: string;
    action: string;
    scheduledAt: number;
    status: string;
    receipt: string;
    reason: string;
    remoteUrl: string;
    reconciliationStatus: string;
    attempts: number;
    maxAttempts: number;
    leaseToken: string | null;
    leaseUntil: number | null;
    heartbeatAt: number | null;
    nextAttemptAt: number;
    errorClass: string;
    deadLetteredAt: number | null;
    approvalExpiresAt: number | null;
    approvalSnapshotId: number | null;
    remoteWriteStartedAt: number | null;
    createdAt: number;
    updatedAt: number;
};
export type AutomationJobEvent = {
    id: number;
    jobId: number;
    event: string;
    status: string;
    errorClass: string;
    createdAt: number;
};
export type AutomationJobLease = {
    job: AutomationJob;
    leaseToken: string;
    leaseUntil: number;
};
export type AccountDispatchLease = {
    accountId: number;
    leaseToken: string;
    leaseUntil: number;
};
export type PublicationPolicyHistoryRow = {
    recordType: "publication_intent" | "automation_job";
    recordId: number;
    accountId: number;
    status: string;
    action: string;
    text: string;
    clusterId: number | null;
    sourceHandle: string;
    targetId: string;
    createdAt: number;
    updatedAt: number;
    sendStartedAt: number | null;
    confirmedAt: number | null;
    publishedAt: number | null;
    potentialBudgetUsed: boolean;
};
export type AccountOpportunity = {
    id: number;
    clusterId: number;
    accountId: number;
    status: string;
    primaryCategoryId: number | null;
    matchedCategoryIds: number[];
    categoryScores: Record<string, number>;
    expectedIncrementalReach: number;
    publishConfidence: number;
    createdAt: number;
    updatedAt: number;
};
export type Publication = {
    id: number;
    clusterId: number;
    accountOpportunityId: number;
    accountId: number;
    sourceObservationExternalId: string;
    remotePostId: string;
    remoteUrl: string;
    status: string;
    requestedAt: number;
    confirmedAt: number | null;
};
export const MONITOR_KINDS = ["account", "keyword", "search_query", "conversation"] as const;
export type MonitorKind = (typeof MONITOR_KINDS)[number];
export type MonitorTier = "hot" | "warm" | "normal" | "cold";
export type MonitorBucket = "proven_alpha" | "hot_categories" | "discovery" | "challengers" | "reconciliation" | "exploration";
export type MonitorTarget = {
    id: number;
    kind: MonitorKind;
    key: string;
    categoryId: number | null;
    sourceHandle: string;
    query: string;
    conversationId: string;
    lifecycle: "challenger" | "active" | "retired";
    tier: MonitorTier;
    intervalSeconds: number;
    burstUntil: number;
    nextRunAt: number;
    enabled: boolean;
    priority: number;
    runs: number;
    results: number;
    uniqueResults: number;
    hits: number;
    duplicates: number;
    falsePositives: number;
    reviewed: number;
    leadTimeTotal: number;
    lastResultAt: number;
    lastHitAt: number;
    createdAt: number;
    updatedAt: number;
};
export type PublicationIntentStatus = "pending_approval" | "approved" | "dispatching" | "pending_reconciliation" | "confirmed" | "blocked" | "cancelled" | "expired" | "reconciliation_required" | "dead_letter";
export type PublicationIntent = {
    id: number;
    draftId: number;
    accountId: number;
    accountHandle: string;
    status: PublicationIntentStatus;
    idempotencyKey: string;
    text: string;
    mediaPath: string;
    mediaHash: string;
    receipt: string;
    remoteUrl: string;
    remotePostId: string;
    reason: string;
    requestedAt: number;
    approvedAt: number | null;
    approvalExpiresAt: number | null;
    approvalSnapshotId: number | null;
    dispatchedAt: number | null;
    confirmedAt: number | null;
    updatedAt: number;
    leaseToken: string | null;
    leaseUntil: number | null;
    heartbeatAt: number | null;
    attempts: number;
    maxAttempts: number;
    nextAttemptAt: number;
    errorClass: string;
    deadLetteredAt: number | null;
    remoteWriteStartedAt: number | null;
};
export type PublicationIntentEvent = {
    id: number;
    intentId: number;
    event: string;
    status: string;
    errorClass: string;
    createdAt: number;
};
export type PublicationIntentLease = {
    intent: PublicationIntent;
    leaseToken: string;
    leaseUntil: number;
};
export type DraftBatch = {
    id: string;
    prompt: string;
    format: string;
    variantMode: "per_account" | "same_text";
    accountIds: number[];
    provider: string;
    model: string;
    status: string;
    createdAt: number;
    updatedAt: number;
};
export type UsageEvent = {
    id: number;
    kind: string;
    provider: string;
    model: string;
    units: number;
    estimatedUsd: number;
    metadata: Record<string, unknown>;
    createdAt: number;
};
export type SecretMeta = {
    name: string;
    provider: string;
    configured: boolean;
    masked: string;
    updatedAt: number;
};
export type SourceReaderCursor = {
    sourceHandle: string;
    lastSeenPostId: string;
    lastSeenCreatedAt: number;
    paginationCursor: string;
    gapDetected: boolean;
    lastSuccessAt: number;
};
export type MetricBaseline = {
    sampleCount: number;
    engagement: number | null;
    views: number | null;
    ageSeconds: number;
};
export type AccountSubscriptionEvidence = {
    currentTier: SubscriptionTier;
    previousTier: SubscriptionTier | null;
    currentSamples: number;
    previousSamples: number;
    currentWeeks: number;
    previousWeeks: number;
    currentMedianViewsPerThousand: number | null;
    previousMedianViewsPerThousand: number | null;
    currentMedianEngagementPerThousand: number | null;
    previousMedianEngagementPerThousand: number | null;
    lift: number | null;
    bonus: number;
    eligible: boolean;
};
export type AiBudgetReservation = {
    id: string;
    allowed: boolean;
    reason?: "budget_exceeded" | "unknown_cost";
};
export type AutomationLock = {
    owner: string;
    pid: number;
    host: string;
    at: number;
};
export type JevScoreRow = {
    id: number;
    subjectKind: string;
    subjectId: string;
    questionKey: string;
    score: number;
    mode: string;
    model: string;
    latencyMs: number;
    requestHash: string;
    diagnostics: string[];
    createdAt: number;
};
export type JevScoreEntry = {
    subjectId: string;
    questionKey: string;
    score: number;
};
export type JevCacheRow = {
    requestHash: string;
    scoresJson: string;
    reportedModel: string;
    createdAt: number;
};
export type DraftVariantRecord = {
    id: number;
    draftId: number;
    variantIndex: number;
    angle: string;
    format: string;
    text: string;
    chosen: boolean;
    evaluatorScore: number | null;
    jevScore: number | null;
    combinedScore: number | null;
    selectionMode: string;
    gateReason: string;
    detail: Record<string, unknown>;
    createdAt: number;
};
export type DraftVariantInput = {
    variantIndex: number;
    angle?: string;
    format?: string;
    text: string;
    chosen?: boolean;
    evaluatorScore?: number | null;
    jevScore?: number | null;
    combinedScore?: number | null;
    selectionMode?: string;
    gateReason?: string;
    detail?: Record<string, unknown>;
};
export type OwnUserProfile = {
    username: string;
    displayName: string;
    bio: string;
    visibility: "private" | "public";
    createdAt: number;
    updatedAt: number;
    xHandle: string | null;
    avatarUrl: string | null;
    onboardingCompleted: boolean;
    profilePath: string;
};
export type PublicUserProfile = {
    username: string;
    displayName: string;
    bio: string;
    xHandle: string | null;
    avatarUrl: string | null;
    profilePath: string;
};
export type HitShareMetrics = {
    views: number | null;
    likes: number | null;
    replies: number | null;
    reposts: number | null;
    quotes: number | null;
};
export type ShareableXPost = {
    remotePostId: string;
    accountHandle: string;
    postUrl: string;
    text: string;
    publishedAt: number;
    metrics: HitShareMetrics;
    observedAt: number;
};
export type OwnHitShare = {
    publicId: string;
    remotePostId: string;
    createdAt: number;
    revokedAt: number | null;
    leaderboardOptIn: boolean;
};
export type PublicHitShare = ShareableXPost & {
    publicId: string;
    verification: "official_x_api";
};
export type LeaderboardEvidence = ShareableXPost & {
    ownerUserId: string;
    accountId: number;
    followers: number;
    publicId: string | null;
};
