import { LOCALES, type Locale } from "./config";

export type Dictionary = {
  status: { partial: string };
  nav: {
    tour: string; login: string; start: string; primary: string; dashboard: string; opportunities: string;
    drafts: string; queue: string; operations: string; accounts: string; timeline: string; sources: string;
    categories: string; analytics: string; evaluation: string; settings: string; keys: string;
    automation: string; style: string; profile: string; security: string; signOut: string;
    signOutPending: string; signOutError: string; shellDescription: string; language: string; menuOpen: string; appearance: string; leaderboard: string;
  };
  landing: {
    metadataTitle: string; metadataDescription: string; menuLabel: string; brand: string; eyebrow: string;
    headlineFirst: string; headlineSecond: string; intro: string; createAccount: string; sourceCode: string;
    flowLabel: string; flowTitle: string; proofVisible: string; sourcePost: string; sourceDetail: string;
    opportunity: string; opportunityDetail: string; draft: string; draftDetail: string; outcome: string;
    outcomeDetail: string; stepOne: string; stepOneDetail: string; stepTwo: string; stepTwoDetail: string;
    stepThree: string; stepThreeDetail: string; localLabel: string; localTitle: string; localDescription: string;
    docsDemo: string; footer: string; trustLabel: string; security: string; privacy: string; terms: string;
    partialNotice: string;
  };
};

const navKeys = [
  "tour", "login", "start", "primary", "dashboard", "opportunities", "drafts", "queue", "operations",
  "accounts", "timeline", "sources", "categories", "analytics", "evaluation", "settings", "keys",
  "automation", "style", "profile", "security", "signOut", "signOutPending", "signOutError",
  "shellDescription", "language", "menuOpen", "appearance", "leaderboard",
] as const satisfies readonly (keyof Dictionary["nav"])[];

const landingKeys = [
  "metadataTitle", "metadataDescription", "menuLabel", "brand", "eyebrow", "headlineFirst", "headlineSecond",
  "intro", "createAccount", "sourceCode", "flowLabel", "flowTitle", "proofVisible", "sourcePost", "sourceDetail",
  "opportunity", "opportunityDetail", "draft", "draftDetail", "outcome", "outcomeDetail", "stepOne",
  "stepOneDetail", "stepTwo", "stepTwoDetail", "stepThree", "stepThreeDetail", "localLabel", "localTitle",
  "localDescription", "docsDemo", "footer", "trustLabel", "security", "privacy", "terms", "partialNotice",
] as const satisfies readonly (keyof Dictionary["landing"])[];

type LocaleCopy = { partial: string; nav: readonly string[]; landing: readonly string[] };

// Each row follows navKeys and landingKeys above. The final landing string is empty
// because these surfaces are fully translated and should not display a partial-copy notice.
const copy: Record<Locale, LocaleCopy> = {
  en: {
    partial: "Some sections of this product are still being translated.",
    nav: ["Product tour", "Sign in", "Get started", "Workspace", "Dashboard", "Opportunities", "Draft studio", "Publishing queue", "Operations", "Accounts", "X timeline", "Sources", "Categories", "Analytics", "Decision review", "Settings", "Key management", "Automation", "Writing style", "Sharing profile", "Account security", "Sign out", "Signing out…", "Could not sign out. Try again.", "Research and publishing desk", "Language", "Open menu", "Language and appearance", "Verified hits"],
    landing: ["Ispatla — Add your own AI key, choose a sourced opportunity, and shape an editable draft.", "Turn real X signals into drafts in your voice. Choose the opportunity, approve the post, and see the evidence behind the result.", "Main menu", "Ispatla", "Social AI HitMaker", "Stop begging the algorithm.", "Make your next move count.", "Turn real X signals into drafts in your voice. Choose the opportunity, approve the post, and see the evidence behind the result.", "Create an account", "Source code", "Sample workflow · product tour", "Source → decision → publication", "evidence visible", "Source post", "original link and source retained", "Opportunity", "review relevance and evidence", "Draft", "editable text in your account’s voice", "Publishing outcome", "local status and X evidence stay distinct", "Connect your X", "Review the topics detected from your profile and posts. Set your language and writing style.", "Give the signal your voice", "Add your own AI key, choose a sourced opportunity, and shape an editable draft.", "Approve. Publish. Learn.", "Review the final text before publishing. Follow confirmed publications and the metrics X actually provides.", "Run locally and inspect the source", "See how the control room works.", "Explore sources, drafts, and receipts in a demo that needs no credentials. The point where account connection and publishing permission begin stays visible.", "Documentation and demo", "Ispatla · research and publishing desk for X", "Trust and product information", "Security", "Privacy", "Terms", ""],
  },
  "zh-CN": {
    partial: "本产品的部分内容仍在翻译中。",
    nav: ["产品介绍", "登录", "开始使用", "工作区", "控制面板", "机会", "草稿工作室", "发布队列", "运营", "账号", "X 时间线", "来源", "类别", "分析", "决策评估", "设置", "密钥管理", "自动化", "写作风格", "分享资料", "账号安全", "退出登录", "正在退出…", "退出失败，请重试。", "研究与发布工作台", "语言", "打开菜单", "语言与外观", "已验证热门帖子"],
    landing: ["Ispatla — 添加自己的 AI 密钥，选择有来源的机会，编辑草稿。", "将真实的 X 动态转为符合你风格的草稿。选择机会，批准发布，查看结果背后的证据。", "主菜单", "Ispatla", "Social AI HitMaker", "别再讨好算法。", "让每一步都有依据。", "将真实的 X 动态转为符合你风格的草稿。选择机会，批准发布，查看结果背后的证据。", "创建账号", "源代码", "示例流程 · 产品介绍", "来源 → 决策 → 发布", "证据清晰可见", "来源帖文", "保留原始链接和来源", "机会", "审查相关性与证据", "草稿", "符合账号风格的可编辑文字", "发布结果", "本地状态与 X 证据分别呈现", "连接你的 X 账号", "审核从资料与帖子识别的主题，设置语言与写作风格。", "用你的声音表达信号", "添加自己的 AI 密钥，选择有来源的机会，编辑草稿。", "审核、发布、学习。", "发布前审核最终文本，跟踪已确认的发布及 X 实际提供的数据。", "本地运行并查看来源", "了解控制台的运作方式。", "无需凭据的演示可查看来源、草稿和回执。账号连接与发布授权从何处开始，也会清楚显示。", "文档与演示", "Ispatla · X 研究与发布工作台", "信任与产品信息", "安全", "隐私", "条款", ""],
  },
  hi: {
    partial: "इस उत्पाद के कुछ हिस्सों का अनुवाद अभी जारी है।",
    nav: ["उत्पाद परिचय", "साइन इन", "शुरू करें", "कार्यस्थल", "डैशबोर्ड", "अवसर", "ड्राफ़्ट स्टूडियो", "प्रकाशन कतार", "संचालन", "खाते", "X टाइमलाइन", "स्रोत", "श्रेणियाँ", "विश्लेषण", "निर्णय समीक्षा", "सेटिंग", "कुंजी प्रबंधन", "स्वचालन", "लेखन शैली", "साझा प्रोफ़ाइल", "खाता सुरक्षा", "साइन आउट", "साइन आउट हो रहा है…", "साइन आउट नहीं हुआ। फिर कोशिश करें।", "शोध और प्रकाशन डेस्क", "भाषा", "मेनू खोलें", "भाषा और रूप", "सत्यापित सफल पोस्ट"],
    landing: ["Ispatla — अपनी AI कुंजी जोड़ें, स्रोत वाला अवसर चुनें और ड्राफ़्ट संपादित करें।", "असली X संकेतों को अपनी आवाज़ में ड्राफ़्ट बनाएँ। अवसर चुनें, पोस्ट मंज़ूर करें और परिणाम का प्रमाण देखें।", "मुख्य मेनू", "Ispatla", "Social AI HitMaker", "एल्गोरिदम से भीख माँगना बंद करें।", "हर कदम को मायने दें।", "असली X संकेतों को अपनी आवाज़ में ड्राफ़्ट बनाएँ। अवसर चुनें, पोस्ट मंज़ूर करें और परिणाम का प्रमाण देखें।", "खाता बनाएँ", "स्रोत कोड", "उदाहरण कार्यप्रवाह · उत्पाद परिचय", "स्रोत → निर्णय → प्रकाशन", "प्रमाण दिखाई देता है", "स्रोत पोस्ट", "मूल लिंक और स्रोत सुरक्षित", "अवसर", "प्रासंगिकता और प्रमाण की समीक्षा", "ड्राफ़्ट", "आपके खाते की आवाज़ में संपादन योग्य पाठ", "प्रकाशन परिणाम", "स्थानीय स्थिति और X प्रमाण अलग रहते हैं", "अपना X जोड़ें", "प्रोफ़ाइल और पोस्ट से मिले विषय जाँचें। भाषा और लेखन शैली चुनें।", "संकेत को अपनी आवाज़ दें", "अपनी AI कुंजी जोड़ें, स्रोत वाला अवसर चुनें और ड्राफ़्ट संपादित करें।", "मंज़ूर करें। प्रकाशित करें। सीखें।", "प्रकाशन से पहले अंतिम पाठ जाँचें। पुष्ट प्रकाशन और X से मिले आँकड़े देखें।", "स्थानीय रूप से चलाएँ और स्रोत देखें", "देखें कि नियंत्रण कक्ष कैसे काम करता है।", "बिना किसी क्रेडेंशियल वाले डेमो में स्रोत, ड्राफ़्ट और रसीदें देखें। खाता जोड़ने और प्रकाशन की अनुमति शुरू होने का बिंदु साफ़ दिखता है।", "दस्तावेज़ और डेमो", "Ispatla · X शोध और प्रकाशन डेस्क", "विश्वास और उत्पाद जानकारी", "सुरक्षा", "गोपनीयता", "शर्तें", ""],
  },
  es: {
    partial: "Algunas secciones del producto todavía se están traduciendo.",
    nav: ["Recorrido del producto", "Iniciar sesión", "Empezar", "Espacio de trabajo", "Panel", "Oportunidades", "Estudio de borradores", "Cola de publicación", "Operaciones", "Cuentas", "Cronología de X", "Fuentes", "Categorías", "Analítica", "Revisión de decisiones", "Ajustes", "Gestión de claves", "Automatización", "Estilo de escritura", "Perfil para compartir", "Seguridad de la cuenta", "Cerrar sesión", "Cerrando sesión…", "No se pudo cerrar sesión. Inténtalo de nuevo.", "Espacio de investigación y publicación", "Idioma", "Abrir menú", "Idioma y apariencia", "Éxitos verificados"],
    landing: ["Ispatla — Añade tu clave de IA, elige una oportunidad con fuente y edita el borrador.", "Convierte señales reales de X en borradores con tu voz. Elige la oportunidad, aprueba la publicación y consulta las pruebas del resultado.", "Menú principal", "Ispatla", "Social AI HitMaker", "Deja de rogar al algoritmo.", "Haz que tu próximo paso cuente.", "Convierte señales reales de X en borradores con tu voz. Elige la oportunidad, aprueba la publicación y consulta las pruebas del resultado.", "Crear una cuenta", "Código fuente", "Flujo de ejemplo · recorrido del producto", "Fuente → decisión → publicación", "pruebas visibles", "Publicación de origen", "se conservan el enlace original y la fuente", "Oportunidad", "revisar relevancia y pruebas", "Borrador", "texto editable con la voz de tu cuenta", "Resultado de publicación", "el estado local y las pruebas de X se mantienen separados", "Conecta tu X", "Revisa los temas detectados en tu perfil y publicaciones. Elige tu idioma y estilo.", "Dale tu voz a la señal", "Añade tu clave de IA, elige una oportunidad con fuente y edita el borrador.", "Aprueba. Publica. Aprende.", "Revisa el texto final antes de publicar. Sigue publicaciones confirmadas y métricas que X proporciona.", "Ejecuta en local y consulta la fuente", "Descubre cómo funciona el centro de control.", "Explora fuentes, borradores y comprobantes en una demo sin credenciales. El punto en que comienzan la conexión de la cuenta y el permiso de publicación queda claro.", "Documentación y demo", "Ispatla · investigación y publicación en X", "Confianza e información del producto", "Seguridad", "Privacidad", "Condiciones", ""],
  },
  fr: {
    partial: "Certaines sections du produit sont encore en cours de traduction.",
    nav: ["Visite du produit", "Se connecter", "Commencer", "Espace de travail", "Tableau de bord", "Occasions", "Atelier de brouillons", "File de publication", "Opérations", "Comptes", "Fil X", "Sources", "Catégories", "Analyses", "Revue des décisions", "Paramètres", "Gestion des clés", "Automatisation", "Style rédactionnel", "Profil de partage", "Sécurité du compte", "Se déconnecter", "Déconnexion…", "Déconnexion impossible. Réessayez.", "Espace de recherche et de publication", "Langue", "Ouvrir le menu", "Langue et apparence", "Succès vérifiés"],
    landing: ["Ispatla — Ajoute ta clé IA, choisis une occasion avec sa source et modifie le brouillon.", "Transforme les signaux réels de X en brouillons à ta voix. Choisis une occasion, approuve la publication et consulte les preuves du résultat.", "Menu principal", "Ispatla", "Social AI HitMaker", "Arrête de supplier l’algorithme.", "Donne du poids à ton prochain geste.", "Transforme les signaux réels de X en brouillons à ta voix. Choisis une occasion, approuve la publication et consulte les preuves du résultat.", "Créer un compte", "Code source", "Flux type · visite du produit", "Source → décision → publication", "preuves visibles", "Publication source", "lien d’origine et source conservés", "Occasion", "examiner la pertinence et les preuves", "Brouillon", "texte modifiable dans la voix de votre compte", "Résultat de publication", "état local et preuves X restent distincts", "Connecte ton X", "Vérifie les thèmes détectés dans ton profil et tes publications. Choisis ta langue et ton style.", "Donne ta voix au signal", "Ajoute ta clé IA, choisis une occasion avec sa source et modifie le brouillon.", "Approuve. Publie. Apprends.", "Vérifie le texte final avant publication. Suis les publications confirmées et les métriques fournies par X.", "Exécuter localement et examiner la source", "Découvrez le fonctionnement du poste de contrôle.", "Consultez sources, brouillons et reçus dans une démo sans identifiants. Le début de la connexion du compte et de l’autorisation de publier reste visible.", "Documentation et démo", "Ispatla · recherche et publication sur X", "Confiance et informations produit", "Sécurité", "Confidentialité", "Conditions", ""],
  },
  ar: {
    partial: "لا تزال بعض أقسام المنتج قيد الترجمة.",
    nav: ["جولة المنتج", "تسجيل الدخول", "ابدأ الآن", "مساحة العمل", "لوحة التحكم", "الفرص", "استوديو المسودات", "قائمة النشر", "العمليات", "الحسابات", "الخط الزمني في X", "المصادر", "الفئات", "التحليلات", "مراجعة القرارات", "الإعدادات", "إدارة المفاتيح", "الأتمتة", "أسلوب الكتابة", "ملف المشاركة", "أمان الحساب", "تسجيل الخروج", "جارٍ تسجيل الخروج…", "تعذّر تسجيل الخروج. حاول مرة أخرى.", "مكتب البحث والنشر", "اللغة", "فتح القائمة", "اللغة والمظهر", "المنشورات الناجحة الموثقة"],
    landing: ["Ispatla — أضف مفتاح الذكاء الاصطناعي الخاص بك، واختر فرصة لها مصدر، وحرّر المسودة.", "حوّل إشارات X الحقيقية إلى مسودات بصوتك. اختر الفرصة، وافق على المنشور، وراجع أدلة النتيجة.", "القائمة الرئيسية", "Ispatla", "Social AI HitMaker", "توقف عن التوسل للخوارزمية.", "اجعل خطوتك القادمة ذات أثر.", "حوّل إشارات X الحقيقية إلى مسودات بصوتك. اختر الفرصة، وافق على المنشور، وراجع أدلة النتيجة.", "إنشاء حساب", "الشيفرة المصدرية", "مسار نموذجي · جولة المنتج", "المصدر ← القرار ← النشر", "الأدلة واضحة", "منشور المصدر", "يُحفظ الرابط الأصلي والمصدر", "فرصة", "مراجعة الملاءمة والأدلة", "مسودة", "نص قابل للتحرير بصوت حسابك", "نتيجة النشر", "تبقى الحالة المحلية وأدلة X منفصلتين", "اربط حسابك في X", "راجع المواضيع المستخرجة من ملفك ومنشوراتك. اختر لغتك وأسلوبك.", "امنح الإشارة صوتك", "أضف مفتاح الذكاء الاصطناعي الخاص بك، واختر فرصة لها مصدر، وحرّر المسودة.", "وافق. انشر. تعلّم.", "راجع النص النهائي قبل النشر. تابع المنشورات المؤكدة والمقاييس التي يقدّمها X فعليًا.", "شغّل محليًا وافحص المصدر", "تعرّف على طريقة عمل غرفة التحكم.", "استكشف المصادر والمسودات والإيصالات في عرض تجريبي لا يحتاج إلى بيانات اعتماد. يظل موضع بدء ربط الحساب وإذن النشر واضحًا.", "الوثائق والعرض التجريبي", "Ispatla · مكتب البحث والنشر على X", "الثقة ومعلومات المنتج", "الأمان", "الخصوصية", "الشروط", ""],
  },
  bn: {
    partial: "পণ্যের কিছু অংশের অনুবাদ এখনও চলছে।",
    nav: ["পণ্য পরিচিতি", "সাইন ইন", "শুরু করুন", "কর্মক্ষেত্র", "ড্যাশবোর্ড", "সুযোগ", "খসড়া স্টুডিও", "প্রকাশনা সারি", "পরিচালনা", "অ্যাকাউন্ট", "X টাইমলাইন", "উৎস", "বিভাগ", "বিশ্লেষণ", "সিদ্ধান্ত পর্যালোচনা", "সেটিংস", "কী ব্যবস্থাপনা", "স্বয়ংক্রিয়করণ", "লেখার ধরন", "শেয়ার প্রোফাইল", "অ্যাকাউন্ট নিরাপত্তা", "সাইন আউট", "সাইন আউট হচ্ছে…", "সাইন আউট করা যায়নি। আবার চেষ্টা করুন।", "গবেষণা ও প্রকাশনা ডেস্ক", "ভাষা", "মেনু খুলুন", "ভাষা ও চেহারা", "যাচাইকৃত সফল পোস্ট"],
    landing: ["Ispatla — নিজের AI কী যোগ করুন, উৎসসহ সুযোগ বেছে নিন এবং খসড়া সম্পাদনা করুন।", "বাস্তব X সংকেত থেকে নিজের ভাষায় খসড়া বানান। সুযোগ বেছে নিন, পোস্ট অনুমোদন করুন এবং ফলের প্রমাণ দেখুন।", "প্রধান মেনু", "Ispatla", "Social AI HitMaker", "অ্যালগরিদমের কাছে মিনতি বন্ধ করুন।", "পরের পদক্ষেপকে অর্থবহ করুন।", "বাস্তব X সংকেত থেকে নিজের ভাষায় খসড়া বানান। সুযোগ বেছে নিন, পোস্ট অনুমোদন করুন এবং ফলের প্রমাণ দেখুন।", "অ্যাকাউন্ট তৈরি করুন", "সোর্স কোড", "নমুনা কার্যপ্রবাহ · পণ্য পরিচিতি", "উৎস → সিদ্ধান্ত → প্রকাশনা", "প্রমাণ দৃশ্যমান", "উৎস পোস্ট", "মূল লিংক ও উৎস সংরক্ষিত", "সুযোগ", "প্রাসঙ্গিকতা ও প্রমাণ পর্যালোচনা", "খসড়া", "আপনার অ্যাকাউন্টের ভাষায় সম্পাদনাযোগ্য লেখা", "প্রকাশনার ফল", "স্থানীয় অবস্থা ও X-এর প্রমাণ আলাদা থাকে", "আপনার X যুক্ত করুন", "প্রোফাইল ও পোস্ট থেকে শনাক্ত বিষয় যাচাই করুন। ভাষা ও লেখার ধরন ঠিক করুন।", "সংকেতকে নিজের ভাষা দিন", "নিজের AI কী যোগ করুন, উৎসসহ সুযোগ বেছে নিন এবং খসড়া সম্পাদনা করুন।", "অনুমোদন। প্রকাশ। শেখা।", "প্রকাশের আগে চূড়ান্ত লেখা দেখুন। নিশ্চিত প্রকাশনা ও X-এর দেওয়া পরিসংখ্যান অনুসরণ করুন।", "স্থানীয়ভাবে চালান ও উৎস দেখুন", "কন্ট্রোল রুম কীভাবে কাজ করে দেখুন।", "ক্রেডেনশিয়াল ছাড়াই ডেমোতে উৎস, খসড়া ও রসিদ দেখুন। অ্যাকাউন্ট সংযোগ ও প্রকাশনার অনুমতি কোথায় শুরু হয় তা দৃশ্যমান থাকে।", "নথি ও ডেমো", "Ispatla · X গবেষণা ও প্রকাশনা ডেস্ক", "বিশ্বাস ও পণ্যের তথ্য", "নিরাপত্তা", "গোপনীয়তা", "শর্তাবলি", ""],
  },
  "pt-BR": {
    partial: "Algumas seções do produto ainda estão sendo traduzidas.",
    nav: ["Tour do produto", "Entrar", "Começar", "Espaço de trabalho", "Painel", "Oportunidades", "Estúdio de rascunhos", "Fila de publicação", "Operações", "Contas", "Linha do tempo do X", "Fontes", "Categorias", "Análises", "Revisão de decisões", "Configurações", "Gerenciamento de chaves", "Automação", "Estilo de escrita", "Perfil de compartilhamento", "Segurança da conta", "Sair", "Saindo…", "Não foi possível sair. Tente novamente.", "Central de pesquisa e publicação", "Idioma", "Abrir menu", "Idioma e aparência", "Sucessos verificados"],
    landing: ["Ispatla — Adicione sua chave de IA, escolha uma oportunidade com fonte e edite o rascunho.", "Transforme sinais reais do X em rascunhos com sua voz. Escolha a oportunidade, aprove a publicação e veja as evidências do resultado.", "Menu principal", "Ispatla", "Social AI HitMaker", "Pare de implorar ao algoritmo.", "Faça seu próximo passo valer.", "Transforme sinais reais do X em rascunhos com sua voz. Escolha a oportunidade, aprove a publicação e veja as evidências do resultado.", "Criar uma conta", "Código-fonte", "Fluxo de exemplo · tour do produto", "Fonte → decisão → publicação", "evidência visível", "Post de origem", "link original e fonte preservados", "Oportunidade", "revisar relevância e evidências", "Rascunho", "texto editável com a voz da sua conta", "Resultado da publicação", "status local e evidências do X permanecem distintos", "Conecte seu X", "Revise os temas detectados no perfil e nas publicações. Escolha idioma e estilo.", "Dê sua voz ao sinal", "Adicione sua chave de IA, escolha uma oportunidade com fonte e edite o rascunho.", "Aprove. Publique. Aprenda.", "Revise o texto final antes de publicar. Acompanhe publicações confirmadas e métricas fornecidas pelo X.", "Execute localmente e inspecione a fonte", "Veja como funciona a central de controle.", "Explore fontes, rascunhos e comprovantes em uma demonstração que não exige credenciais. O início da conexão da conta e da permissão de publicação fica visível.", "Documentação e demonstração", "Ispatla · pesquisa e publicação no X", "Confiança e informações do produto", "Segurança", "Privacidade", "Termos", ""],
  },
  ru: {
    partial: "Некоторые разделы продукта всё ещё переводятся.",
    nav: ["Обзор продукта", "Войти", "Начать", "Рабочее пространство", "Панель управления", "Возможности", "Редактор черновиков", "Очередь публикаций", "Операции", "Аккаунты", "Лента X", "Источники", "Категории", "Аналитика", "Проверка решений", "Настройки", "Управление ключами", "Автоматизация", "Стиль письма", "Профиль для публикаций", "Безопасность аккаунта", "Выйти", "Выход…", "Не удалось выйти. Попробуйте ещё раз.", "Рабочее место для исследований и публикаций", "Язык", "Открыть меню", "Язык и оформление", "Подтверждённые успехи"],
    landing: ["Ispatla — Добавьте свой ключ ИИ, выберите возможность с источником и отредактируйте черновик.", "Превращайте реальные сигналы X в черновики своим голосом. Выбирайте возможности, утверждайте публикации и изучайте доказательства результата.", "Главное меню", "Ispatla", "Social AI HitMaker", "Хватит умолять алгоритм.", "Пусть следующий шаг будет осмысленным.", "Превращайте реальные сигналы X в черновики своим голосом. Выбирайте возможности, утверждайте публикации и изучайте доказательства результата.", "Создать аккаунт", "Исходный код", "Пример процесса · обзор продукта", "Источник → решение → публикация", "доказательства видны", "Исходная публикация", "исходная ссылка и источник сохранены", "Возможность", "оценить релевантность и доказательства", "Черновик", "редактируемый текст в стиле аккаунта", "Результат публикации", "локальный статус и данные X разделены", "Подключите свой X", "Проверьте темы из профиля и публикаций. Выберите язык и стиль.", "Придайте сигналу свой голос", "Добавьте свой ключ ИИ, выберите возможность с источником и отредактируйте черновик.", "Утвердите. Опубликуйте. Учитесь.", "Проверьте итоговый текст перед публикацией. Следите за подтверждёнными публикациями и доступными метриками X.", "Запустите локально и изучите источник", "Посмотрите, как работает центр управления.", "Изучайте источники, черновики и квитанции в демо без учётных данных. Граница подключения аккаунта и разрешения на публикацию остаётся видимой.", "Документация и демо", "Ispatla · исследования и публикации в X", "Доверие и информация о продукте", "Безопасность", "Конфиденциальность", "Условия", ""],
  },
  id: {
    partial: "Beberapa bagian produk ini masih dalam proses penerjemahan.",
    nav: ["Tur produk", "Masuk", "Mulai", "Ruang kerja", "Dasbor", "Peluang", "Studio draf", "Antrean publikasi", "Operasi", "Akun", "Linimasa X", "Sumber", "Kategori", "Analitik", "Tinjauan keputusan", "Pengaturan", "Pengelolaan kunci", "Otomatisasi", "Gaya penulisan", "Profil berbagi", "Keamanan akun", "Keluar", "Sedang keluar…", "Tidak dapat keluar. Coba lagi.", "Meja riset dan publikasi", "Bahasa", "Buka menu", "Bahasa dan tampilan", "Hasil terverifikasi"],
    landing: ["Ispatla — Tambahkan kunci AI sendiri, pilih peluang bersumber, dan sunting draf.", "Ubah sinyal nyata X menjadi draf dengan suaramu. Pilih peluang, setujui postingan, dan lihat bukti hasilnya.", "Menu utama", "Ispatla", "Social AI HitMaker", "Berhenti memohon pada algoritma.", "Buat langkah berikutnya berarti.", "Ubah sinyal nyata X menjadi draf dengan suaramu. Pilih peluang, setujui postingan, dan lihat bukti hasilnya.", "Buat akun", "Kode sumber", "Alur contoh · tur produk", "Sumber → keputusan → publikasi", "bukti terlihat", "Kiriman sumber", "tautan asli dan sumber tetap tersimpan", "Peluang", "tinjau relevansi dan bukti", "Draf", "teks yang dapat diedit dengan gaya akun Anda", "Hasil publikasi", "status lokal dan bukti X tetap terpisah", "Hubungkan X-mu", "Tinjau topik dari profil dan postingan. Pilih bahasa dan gaya tulisan.", "Beri sinyal suaramu", "Tambahkan kunci AI sendiri, pilih peluang bersumber, dan sunting draf.", "Setujui. Terbitkan. Pelajari.", "Tinjau teks akhir sebelum terbit. Ikuti publikasi terkonfirmasi dan metrik yang disediakan X.", "Jalankan secara lokal dan periksa sumber", "Lihat cara kerja pusat kendali.", "Jelajahi sumber, draf, dan tanda terima dalam demo tanpa kredensial. Titik dimulainya koneksi akun dan izin publikasi tetap terlihat.", "Dokumentasi dan demo", "Ispatla · riset dan publikasi X", "Kepercayaan dan informasi produk", "Keamanan", "Privasi", "Ketentuan", ""],
  },
  ur: {
    partial: "اس پروڈکٹ کے کچھ حصوں کا ترجمہ ابھی جاری ہے۔",
    nav: ["پروڈکٹ کا تعارف", "سائن اِن", "شروع کریں", "کام کی جگہ", "ڈیش بورڈ", "مواقع", "مسودہ اسٹوڈیو", "اشاعت کی قطار", "آپریشنز", "اکاؤنٹس", "X ٹائم لائن", "ذرائع", "زمرے", "تجزیات", "فیصلوں کا جائزہ", "ترتیبات", "کلیدوں کا انتظام", "خودکاری", "تحریری انداز", "شیئرنگ پروفائل", "اکاؤنٹ سیکیورٹی", "سائن آؤٹ", "سائن آؤٹ ہو رہا ہے…", "سائن آؤٹ نہیں ہو سکا۔ دوبارہ کوشش کریں۔", "تحقیق اور اشاعت کی میز", "زبان", "مینو کھولیں", "زبان اور ظاہری شکل", "تصدیق شدہ کامیاب پوسٹس"],
    landing: ["Ispatla — اپنی AI کلید شامل کریں، ماخذ والا موقع چنیں اور مسودہ ترمیم کریں۔", "X کے حقیقی اشاروں سے اپنی آواز میں مسودے بنائیں۔ موقع چنیں، پوسٹ منظور کریں اور نتیجے کے شواہد دیکھیں۔", "مرکزی مینو", "Ispatla", "Social AI HitMaker", "الگورتھم سے منتیں کرنا بند کریں۔", "اپنے اگلے قدم کو معنی دیں۔", "X کے حقیقی اشاروں سے اپنی آواز میں مسودے بنائیں۔ موقع چنیں، پوسٹ منظور کریں اور نتیجے کے شواہد دیکھیں۔", "اکاؤنٹ بنائیں", "ماخذ کوڈ", "مثالی طریقۂ کار · پروڈکٹ کا تعارف", "ذریعہ → فیصلہ → اشاعت", "شواہد واضح ہیں", "ماخذ پوسٹ", "اصل لنک اور ذریعہ محفوظ ہیں", "موقع", "تعلق اور شواہد کا جائزہ", "مسودہ", "آپ کے اکاؤنٹ کے انداز میں قابلِ ترمیم متن", "اشاعت کا نتیجہ", "مقامی حالت اور X شواہد الگ رہتے ہیں", "اپنا X جوڑیں", "پروفائل اور پوسٹوں سے ملے موضوعات دیکھیں۔ زبان اور انداز منتخب کریں۔", "اشارے کو اپنی آواز دیں", "اپنی AI کلید شامل کریں، ماخذ والا موقع چنیں اور مسودہ ترمیم کریں۔", "منظور کریں۔ شائع کریں۔ سیکھیں۔", "اشاعت سے پہلے آخری متن دیکھیں۔ تصدیق شدہ اشاعت اور X کے فراہم کردہ اعداد دیکھیں۔", "مقامی طور پر چلائیں اور ذریعہ دیکھیں", "دیکھیں کہ کنٹرول روم کیسے کام کرتا ہے۔", "ایسے ڈیمو میں ذرائع، مسودے اور رسیدیں دیکھیں جسے اسناد کی ضرورت نہیں۔ اکاؤنٹ جوڑنے اور اشاعت کی اجازت شروع ہونے کی جگہ واضح رہتی ہے۔", "دستاویزات اور ڈیمو", "Ispatla · X تحقیق اور اشاعت کی میز", "اعتماد اور پروڈکٹ کی معلومات", "سیکیورٹی", "رازداری", "شرائط", ""],
  },
  de: {
    partial: "Einige Bereiche dieses Produkts werden noch übersetzt.",
    nav: ["Produkttour", "Anmelden", "Loslegen", "Arbeitsbereich", "Übersicht", "Chancen", "Entwurfsstudio", "Veröffentlichungswarteschlange", "Betrieb", "Konten", "X-Zeitleiste", "Quellen", "Kategorien", "Analysen", "Entscheidungsprüfung", "Einstellungen", "Schlüsselverwaltung", "Automatisierung", "Schreibstil", "Freigabeprofil", "Kontosicherheit", "Abmelden", "Abmeldung läuft…", "Abmeldung fehlgeschlagen. Bitte erneut versuchen.", "Arbeitsplatz für Recherche und Veröffentlichung", "Sprache", "Menü öffnen", "Sprache und Darstellung", "Verifizierte Erfolge"],
    landing: ["Ispatla — Füge deinen KI-Schlüssel hinzu, wähle eine belegte Chance und bearbeite den Entwurf.", "Mach aus echten X-Signalen Entwürfe in deiner Stimme. Wähle die Chance, bestätige den Beitrag und prüfe die Belege des Ergebnisses.", "Hauptmenü", "Ispatla", "Social AI HitMaker", "Hör auf, den Algorithmus anzuflehen.", "Gib deinem nächsten Schritt Gewicht.", "Mach aus echten X-Signalen Entwürfe in deiner Stimme. Wähle die Chance, bestätige den Beitrag und prüfe die Belege des Ergebnisses.", "Konto erstellen", "Quellcode", "Beispielablauf · Produkttour", "Quelle → Entscheidung → Veröffentlichung", "Belege sichtbar", "Quellbeitrag", "Original-Link und Quelle bleiben erhalten", "Chance", "Relevanz und Belege prüfen", "Entwurf", "bearbeitbarer Text im Stil Ihres Kontos", "Veröffentlichungsergebnis", "lokaler Status und X-Belege bleiben getrennt", "Verbinde dein X", "Prüfe erkannte Themen aus Profil und Beiträgen. Wähle Sprache und Schreibstil.", "Gib dem Signal deine Stimme", "Füge deinen KI-Schlüssel hinzu, wähle eine belegte Chance und bearbeite den Entwurf.", "Prüfen. Veröffentlichen. Lernen.", "Prüfe den fertigen Text. Verfolge bestätigte Veröffentlichungen und die von X bereitgestellten Kennzahlen.", "Lokal ausführen und Quelle prüfen", "Erfahren Sie, wie die Schaltzentrale funktioniert.", "Entdecken Sie Quellen, Entwürfe und Belege in einer Demo ohne Zugangsdaten. Der Beginn der Kontoverbindung und der Veröffentlichungsfreigabe bleibt sichtbar.", "Dokumentation und Demo", "Ispatla · Recherche und Veröffentlichung auf X", "Vertrauen und Produktinformationen", "Sicherheit", "Datenschutz", "Bedingungen", ""],
  },
  ja: {
    partial: "製品の一部は現在翻訳中です。",
    nav: ["製品ツアー", "ログイン", "利用を開始", "ワークスペース", "ダッシュボード", "機会", "下書きスタジオ", "公開キュー", "運用", "アカウント", "X タイムライン", "ソース", "カテゴリ", "分析", "判断の確認", "設定", "キー管理", "自動化", "文章スタイル", "共有プロフィール", "アカウントのセキュリティ", "ログアウト", "ログアウト中…", "ログアウトできませんでした。もう一度お試しください。", "リサーチと公開のデスク", "言語", "メニューを開く", "言語と外観", "検証済みの成果"],
    landing: ["Ispatla — 自分のAIキーを追加し、出典のある機会を選んで下書きを編集します。", "実際のXの動きから、あなたの声で下書きを作成。機会を選び、投稿を承認し、結果の根拠を確認できます。", "メインメニュー", "Ispatla", "Social AI HitMaker", "アルゴリズムに媚びるのは終わり。", "次の一手に根拠を。", "実際のXの動きから、あなたの声で下書きを作成。機会を選び、投稿を承認し、結果の根拠を確認できます。", "アカウントを作成", "ソースコード", "ワークフロー例 · 製品ツアー", "ソース → 判断 → 公開", "根拠を表示", "ソース投稿", "元のリンクとソースを保持", "機会", "関連性と根拠を確認", "下書き", "アカウントの文体で編集できる文章", "公開結果", "ローカルの状態と X の根拠は別々に表示", "Xアカウントを接続", "プロフィールと投稿から検出したテーマを確認。言語と文体を設定します。", "シグナルをあなたの声に", "自分のAIキーを追加し、出典のある機会を選んで下書きを編集します。", "確認。投稿。学習。", "投稿前に最終文面を確認。確定した投稿とXが提供する指標を追跡します。", "ローカルで実行してソースを確認", "コントロールルームの仕組みをご覧ください。", "認証情報なしのデモでソース、下書き、受領記録を確認できます。アカウント接続と公開許可の開始点も明示されます。", "ドキュメントとデモ", "Ispatla · X リサーチ・公開デスク", "信頼と製品情報", "セキュリティ", "プライバシー", "利用規約", ""],
  },
  sw: {
    partial: "Baadhi ya sehemu za bidhaa hii bado zinatafsiriwa.",
    nav: ["Utambulisho wa bidhaa", "Ingia", "Anza", "Nafasi ya kazi", "Dashibodi", "Fursa", "Studio ya rasimu", "Foleni ya uchapishaji", "Shughuli", "Akaunti", "Mtiririko wa X", "Vyanzo", "Kategoria", "Uchanganuzi", "Kagua maamuzi", "Mipangilio", "Usimamizi wa funguo", "Uendeshaji otomatiki", "Mtindo wa uandishi", "Wasifu wa kushiriki", "Usalama wa akaunti", "Ondoka", "Unatoka…", "Imeshindwa kutoka. Jaribu tena.", "Dawati la utafiti na uchapishaji", "Lugha", "Fungua menyu", "Lugha na mwonekano", "Mafanikio yaliyothibitishwa"],
    landing: ["Ispatla — Ongeza ufunguo wako wa AI, chagua fursa yenye chanzo, na hariri rasimu.", "Geuza ishara halisi za X kuwa rasimu kwa sauti yako. Chagua fursa, idhinisha chapisho, na uone ushahidi wa matokeo.", "Menyu kuu", "Ispatla", "Social AI HitMaker", "Acha kuisihi algoriti.", "Fanya hatua yako ijayo iwe na maana.", "Geuza ishara halisi za X kuwa rasimu kwa sauti yako. Chagua fursa, idhinisha chapisho, na uone ushahidi wa matokeo.", "Fungua akaunti", "Msimbo chanzo", "Mtiririko wa mfano · utambulisho wa bidhaa", "Chanzo → uamuzi → uchapishaji", "ushahidi unaonekana", "Chapisho la chanzo", "kiungo asili na chanzo vimehifadhiwa", "Fursa", "kagua umuhimu na ushahidi", "Rasimu", "maandishi yanayoweza kuhaririwa kwa sauti ya akaunti yako", "Matokeo ya uchapishaji", "hali ya ndani na ushahidi wa X vinabaki tofauti", "Unganisha X yako", "Kagua mada zilizotambuliwa katika wasifu na machapisho. Chagua lugha na mtindo.", "Ipe ishara sauti yako", "Ongeza ufunguo wako wa AI, chagua fursa yenye chanzo, na hariri rasimu.", "Idhinisha. Chapisha. Jifunze.", "Kagua maandishi ya mwisho kabla ya kuchapisha. Fuatilia machapisho yaliyothibitishwa na vipimo vinavyotolewa na X.", "Endesha hapa na kagua chanzo", "Angalia jinsi chumba cha udhibiti kinavyofanya kazi.", "Chunguza vyanzo, rasimu na stakabadhi kwenye onyesho lisilohitaji vitambulisho. Mwanzo wa kuunganisha akaunti na ruhusa ya kuchapisha unaonekana wazi.", "Hati na onyesho", "Ispatla · dawati la utafiti na uchapishaji wa X", "Uaminifu na taarifa za bidhaa", "Usalama", "Faragha", "Masharti", ""],
  },
  mr: {
    partial: "या उत्पादनातील काही विभागांचे भाषांतर अजून सुरू आहे.",
    nav: ["उत्पादन परिचय", "साइन इन", "सुरू करा", "कार्यस्थळ", "डॅशबोर्ड", "संधी", "मसुदा स्टुडिओ", "प्रकाशन रांग", "कामकाज", "खाती", "X टाइमलाइन", "स्रोत", "श्रेणी", "विश्लेषण", "निर्णय पुनरावलोकन", "सेटिंग्ज", "की व्यवस्थापन", "स्वयंचलन", "लेखनशैली", "शेअर प्रोफाइल", "खाते सुरक्षा", "साइन आउट", "साइन आउट होत आहे…", "साइन आउट झाले नाही. पुन्हा प्रयत्न करा.", "संशोधन आणि प्रकाशन डेस्क", "भाषा", "मेनू उघडा", "भाषा आणि स्वरूप", "पडताळलेल्या यशस्वी पोस्ट"],
    landing: ["Ispatla — स्वतःची AI की जोडा, स्रोत असलेली संधी निवडा आणि मसुदा संपादित करा.", "खऱ्या X संकेतांपासून तुमच्या आवाजात मसुदे बनवा. संधी निवडा, पोस्ट मंजूर करा आणि निकालाचे पुरावे पाहा.", "मुख्य मेनू", "Ispatla", "Social AI HitMaker", "अल्गोरिदमला विनवणे थांबवा.", "पुढच्या पावलाला अर्थ द्या.", "खऱ्या X संकेतांपासून तुमच्या आवाजात मसुदे बनवा. संधी निवडा, पोस्ट मंजूर करा आणि निकालाचे पुरावे पाहा.", "खाते तयार करा", "स्रोत कोड", "नमुना कार्यप्रवाह · उत्पादन परिचय", "स्रोत → निर्णय → प्रकाशन", "पुरावा दिसतो", "स्रोत पोस्ट", "मूळ दुवा आणि स्रोत जतन", "संधी", "सुसंगतता आणि पुरावा तपासा", "मसुदा", "तुमच्या खात्याच्या शैलीतील संपादनयोग्य मजकूर", "प्रकाशनाचा परिणाम", "स्थानिक स्थिती आणि X पुरावे वेगळे राहतात", "तुमचे X जोडा", "प्रोफाइल आणि पोस्टमधून ओळखलेले विषय तपासा. भाषा आणि लेखनशैली निवडा.", "संकेताला तुमचा आवाज द्या", "स्वतःची AI की जोडा, स्रोत असलेली संधी निवडा आणि मसुदा संपादित करा.", "मंजूर करा. प्रकाशित करा. शिका.", "प्रकाशनापूर्वी अंतिम मजकूर तपासा. खात्रीशीर प्रकाशने आणि X ने दिलेली मोजमापे पाहा.", "स्थानिकपणे चालवा आणि स्रोत तपासा", "नियंत्रण कक्ष कसा काम करतो ते पाहा.", "ओळखपत्रांशिवाय चालणाऱ्या डेमोमध्ये स्रोत, मसुदे आणि पावत्या पाहा. खाते जोडणे आणि प्रकाशन परवानगी कुठे सुरू होते ते स्पष्ट दिसते.", "दस्तऐवज आणि डेमो", "Ispatla · X संशोधन आणि प्रकाशन डेस्क", "विश्वास आणि उत्पादन माहिती", "सुरक्षा", "गोपनीयता", "अटी", ""],
  },
  te: {
    partial: "ఈ ఉత్పత్తిలోని కొన్ని భాగాల అనువాదం ఇంకా కొనసాగుతోంది.",
    nav: ["ఉత్పత్తి పరిచయం", "సైన్ ఇన్", "ప్రారంభించండి", "పని ప్రదేశం", "డ్యాష్‌బోర్డ్", "అవకాశాలు", "డ్రాఫ్ట్ స్టూడియో", "ప్రచురణ క్యూ", "కార్యకలాపాలు", "ఖాతాలు", "X టైమ్‌లైన్", "మూలాలు", "వర్గాలు", "విశ్లేషణలు", "నిర్ణయ సమీక్ష", "సెట్టింగ్‌లు", "కీ నిర్వహణ", "ఆటోమేషన్", "రచనా శైలి", "షేరింగ్ ప్రొఫైల్", "ఖాతా భద్రత", "సైన్ అవుట్", "సైన్ అవుట్ అవుతోంది…", "సైన్ అవుట్ కాలేదు. మళ్లీ ప్రయత్నించండి.", "పరిశోధన మరియు ప్రచురణ డెస్క్", "భాష", "మెనూ తెరవండి", "భాష మరియు రూపం", "ధృవీకరించిన విజయాలు"],
    landing: ["Ispatla — మీ AI కీ జోడించి, మూలం ఉన్న అవకాశం ఎంచుకుని డ్రాఫ్ట్ సవరించండి.", "నిజమైన X సంకేతాలను మీ స్వరంలో డ్రాఫ్ట్‌లుగా మార్చండి. అవకాశం ఎంచుకోండి, పోస్ట్ ఆమోదించండి, ఫలితానికి ఆధారాలు చూడండి.", "ప్రధాన మెనూ", "Ispatla", "Social AI HitMaker", "అల్గోరిథమ్‌ను వేడుకోవడం ఆపండి.", "మీ తదుపరి అడుగుకు అర్థం ఇవ్వండి.", "నిజమైన X సంకేతాలను మీ స్వరంలో డ్రాఫ్ట్‌లుగా మార్చండి. అవకాశం ఎంచుకోండి, పోస్ట్ ఆమోదించండి, ఫలితానికి ఆధారాలు చూడండి.", "ఖాతా సృష్టించండి", "సోర్స్ కోడ్", "నమూనా పని విధానం · ఉత్పత్తి పరిచయం", "మూలం → నిర్ణయం → ప్రచురణ", "ఆధారం కనిపిస్తుంది", "మూల పోస్ట్", "అసలు లింక్ మరియు మూలం భద్రం", "అవకాశం", "సంబంధితత మరియు ఆధారాలను పరిశీలించండి", "డ్రాఫ్ట్", "మీ ఖాతా స్వరంలో సవరించగల వచనం", "ప్రచురణ ఫలితం", "స్థానిక స్థితి మరియు X ఆధారాలు వేరుగా ఉంటాయి", "మీ Xను కనెక్ట్ చేయండి", "ప్రొఫైల్, పోస్టుల నుంచి గుర్తించిన అంశాలను చూడండి. భాష, రచనా శైలి ఎంచుకోండి.", "సంకేతానికి మీ స్వరం ఇవ్వండి", "మీ AI కీ జోడించి, మూలం ఉన్న అవకాశం ఎంచుకుని డ్రాఫ్ట్ సవరించండి.", "ఆమోదించండి. ప్రచురించండి. నేర్చుకోండి.", "ప్రచురణకు ముందు తుది వచనాన్ని చూడండి. ధృవీకరించిన ప్రచురణలు, X అందించే గణాంకాలు అనుసరించండి.", "స్థానికంగా నడిపి మూలాన్ని పరిశీలించండి", "కంట్రోల్ రూమ్ ఎలా పనిచేస్తుందో చూడండి.", "ఆధారాలు అవసరం లేని డెమోలో మూలాలు, డ్రాఫ్ట్‌లు, రసీదులను చూడండి. ఖాతా అనుసంధానం మరియు ప్రచురణ అనుమతి ఎక్కడ మొదలవుతాయో స్పష్టంగా ఉంటుంది.", "డాక్యుమెంటేషన్ మరియు డెమో", "Ispatla · X పరిశోధన మరియు ప్రచురణ డెస్క్", "నమ్మకం మరియు ఉత్పత్తి సమాచారం", "భద్రత", "గోప్యత", "నిబంధనలు", ""],
  },
  tr: {
    partial: "Ürünün bazı bölümlerinin çevirisi sürüyor.",
    nav: ["Ürün turu", "Giriş yap", "Başla", "Çalışma alanı", "Kontrol paneli", "Fırsatlar", "Taslak stüdyosu", "Yayın kuyruğu", "Operasyonlar", "Hesaplar", "X zaman akışı", "Kaynaklar", "Kategoriler", "Analitik", "Karar incelemesi", "Ayarlar", "Anahtar yönetimi", "Otomasyon", "Yazım tarzı", "Paylaşım profili", "Hesap güvenliği", "Çıkış yap", "Çıkış yapılıyor…", "Çıkış yapılamadı. Yeniden dene.", "Araştırma ve yayın masası", "Dil", "Menüyü aç", "Dil ve görünüm", "Doğrulanmış hitler"],
    landing: ["Ispatla — Kendi AI anahtarını ekle, kaynağı belli bir fırsat seç ve taslağı şekillendir.", "Gerçek X sinyallerini kendi sesinde taslaklara çevir. Fırsatı sen seç, yayını sen onayla. Sonucun arkasındaki kanıtı gör.", "Ana menü", "İspatla", "Social AI HitMaker", "Algoritmaya yalvarma.", "Kendi oyununu kur.", "Gerçek X sinyallerini kendi sesinde taslaklara çevir. Fırsatı sen seç, yayını sen onayla. Sonucun arkasındaki kanıtı gör.", "Hesap oluştur", "Kaynak kodu", "Örnek akış · ürün turu", "Kaynak → karar → yayın", "kanıt görünür", "Kaynak gönderi", "özgün bağlantı ve kaynak korunur", "Fırsat", "uygunluk ve kanıtı incele", "Taslak", "hesabının üslubunda düzenlenebilir metin", "Yayın sonucu", "yerel durum ve X kanıtı ayrı tutulur", "X hesabını bağla", "Profilinden ve gönderilerinden bulunan konuları gözden geçir. Dilini ve yazım tarzını seç.", "Sinyale kendi sesini kat", "Kendi AI anahtarını ekle, kaynağı belli bir fırsat seç ve taslağı şekillendir.", "Onayla. Yayınla. Öğren.", "Yayınlamadan önce son metni incele. Doğrulanan yayınları ve X’in gerçekten sağladığı metrikleri izle.", "Yerelde çalıştır ve kaynağı incele", "Kontrol masasının nasıl çalıştığını gör.", "Kimlik bilgisi gerektirmeyen demoda kaynakları, taslakları ve makbuzları incele. Hesap bağlantısının ve yayın izninin nerede başladığı açıkça görünür.", "Dokümantasyon ve demo", "İspatla · X araştırma ve yayın masası", "Güven ve ürün bilgileri", "Güvenlik", "Gizlilik", "Koşullar", ""],
  },
  ta: {
    partial: "இந்தத் தயாரிப்பின் சில பகுதிகள் இன்னும் மொழிபெயர்க்கப்பட்டு வருகின்றன.",
    nav: ["தயாரிப்பு அறிமுகம்", "உள்நுழை", "தொடங்கு", "பணியிடம்", "முகப்புப் பலகை", "வாய்ப்புகள்", "வரைவு அரங்கு", "வெளியீட்டு வரிசை", "செயல்பாடுகள்", "கணக்குகள்", "X காலவரிசை", "மூலங்கள்", "வகைகள்", "பகுப்பாய்வு", "முடிவு மதிப்பாய்வு", "அமைப்புகள்", "விசை நிர்வாகம்", "தானியக்கம்", "எழுத்து நடை", "பகிர்வு சுயவிவரம்", "கணக்கு பாதுகாப்பு", "வெளியேறு", "வெளியேறுகிறது…", "வெளியேற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.", "ஆய்வு மற்றும் வெளியீட்டு மேசை", "மொழி", "பட்டியலைத் திற", "மொழி மற்றும் தோற்றம்", "சரிபார்க்கப்பட்ட வெற்றிகள்"],
    landing: ["Ispatla — உங்கள் AI விசையைச் சேர்த்து, மூலம் உள்ள வாய்ப்பைத் தேர்ந்து வரைவைத்திருத்தவும்.", "உண்மையான X சைகைகளை உங்கள் குரலில் வரைவுகளாக்குங்கள். வாய்ப்பைத் தேர்ந்து, பதிவை ஒப்புதல் அளித்து, முடிவின் ஆதாரத்தைப் பாருங்கள்.", "முதன்மை பட்டியல்", "Ispatla", "Social AI HitMaker", "அல்கோரிதத்திடம் கெஞ்சுவதை நிறுத்துங்கள்.", "அடுத்த படிக்கு அர்த்தம் கொடுங்கள்.", "உண்மையான X சைகைகளை உங்கள் குரலில் வரைவுகளாக்குங்கள். வாய்ப்பைத் தேர்ந்து, பதிவை ஒப்புதல் அளித்து, முடிவின் ஆதாரத்தைப் பாருங்கள்.", "கணக்கை உருவாக்கு", "மூலக் குறியீடு", "மாதிரி நடைமுறை · தயாரிப்பு அறிமுகம்", "மூலம் → முடிவு → வெளியீடு", "ஆதாரம் தெரியும்", "மூலப் பதிவு", "அசல் இணைப்பும் மூலமும் பாதுகாக்கப்படும்", "வாய்ப்பு", "பொருத்தம் மற்றும் ஆதாரத்தைப் பாருங்கள்", "வரைவு", "உங்கள் கணக்கின் குரலில் திருத்தக்கூடிய உரை", "வெளியீட்டு முடிவு", "உள்ளூர் நிலையும் X ஆதாரமும் தனித்தனியாக இருக்கும்", "உங்கள் Xஐ இணைக்கவும்", "சுயவிவரம், பதிவுகளில் கண்ட தலைப்புகளைச் சரிபார்க்கவும். மொழி, எழுத்து நடையைத் தேர்வுசெய்யவும்.", "சைகைக்கு உங்கள் குரலைத் தாருங்கள்", "உங்கள் AI விசையைச் சேர்த்து, மூலம் உள்ள வாய்ப்பைத் தேர்ந்து வரைவைத்திருத்தவும்.", "ஒப்புதல். வெளியீடு. கற்றல்.", "வெளியீட்டுக்கு முன் இறுதி உரையைப் பாருங்கள். உறுதியான வெளியீடுகள் மற்றும் X வழங்கும் அளவீடுகளைப் பின்தொடருங்கள்.", "உள்ளூரில் இயக்கி மூலத்தைப் பாருங்கள்", "கட்டுப்பாட்டு அறை எப்படிச் செயல்படுகிறது எனப் பாருங்கள்.", "சான்றுகள் தேவையில்லாத செயல்விளக்கத்தில் மூலங்கள், வரைவுகள், ரசீதுகளைப் பாருங்கள். கணக்கு இணைப்பும் வெளியீட்டு அனுமதியும் தொடங்கும் இடம் தெளிவாகத் தெரியும்.", "ஆவணங்களும் செயல்விளக்கமும்", "Ispatla · X ஆய்வு மற்றும் வெளியீட்டு மேசை", "நம்பிக்கை மற்றும் தயாரிப்பு விவரங்கள்", "பாதுகாப்பு", "தனியுரிமை", "விதிமுறைகள்", ""],
  },
  vi: {
    partial: "Một số mục của sản phẩm vẫn đang được dịch.",
    nav: ["Giới thiệu sản phẩm", "Đăng nhập", "Bắt đầu", "Không gian làm việc", "Bảng điều khiển", "Cơ hội", "Studio bản nháp", "Hàng đợi xuất bản", "Vận hành", "Tài khoản", "Dòng thời gian X", "Nguồn", "Danh mục", "Phân tích", "Đánh giá quyết định", "Cài đặt", "Quản lý khóa", "Tự động hóa", "Phong cách viết", "Hồ sơ chia sẻ", "Bảo mật tài khoản", "Đăng xuất", "Đang đăng xuất…", "Không thể đăng xuất. Hãy thử lại.", "Bàn nghiên cứu và xuất bản", "Ngôn ngữ", "Mở menu", "Ngôn ngữ và giao diện", "Thành công đã xác minh"],
    landing: ["Ispatla — Thêm khóa AI riêng, chọn cơ hội có nguồn và chỉnh sửa bản nháp.", "Biến tín hiệu thật từ X thành bản nháp mang giọng của bạn. Chọn cơ hội, duyệt bài đăng và xem bằng chứng của kết quả.", "Menu chính", "Ispatla", "Social AI HitMaker", "Đừng cầu xin thuật toán nữa.", "Để bước tiếp theo có ý nghĩa.", "Biến tín hiệu thật từ X thành bản nháp mang giọng của bạn. Chọn cơ hội, duyệt bài đăng và xem bằng chứng của kết quả.", "Tạo tài khoản", "Mã nguồn", "Quy trình mẫu · giới thiệu sản phẩm", "Nguồn → quyết định → xuất bản", "bằng chứng hiển thị", "Bài đăng nguồn", "giữ lại liên kết và nguồn ban đầu", "Cơ hội", "xem xét mức liên quan và bằng chứng", "Bản nháp", "văn bản có thể chỉnh sửa theo giọng điệu tài khoản", "Kết quả xuất bản", "trạng thái cục bộ và bằng chứng X được tách riêng", "Kết nối X của bạn", "Xem chủ đề nhận diện từ hồ sơ và bài đăng. Chọn ngôn ngữ và phong cách.", "Đưa tiếng nói vào tín hiệu", "Thêm khóa AI riêng, chọn cơ hội có nguồn và chỉnh sửa bản nháp.", "Duyệt. Đăng. Học hỏi.", "Xem nội dung cuối trước khi đăng. Theo dõi bài đăng xác nhận và số liệu X cung cấp.", "Chạy cục bộ và kiểm tra nguồn", "Tìm hiểu cách phòng điều khiển hoạt động.", "Khám phá nguồn, bản nháp và biên nhận trong bản demo không cần thông tin xác thực. Điểm bắt đầu kết nối tài khoản và cấp quyền đăng bài luôn được hiển thị.", "Tài liệu và bản demo", "Ispatla · nghiên cứu và xuất bản trên X", "Niềm tin và thông tin sản phẩm", "Bảo mật", "Quyền riêng tư", "Điều khoản", ""],
  },
  ko: {
    partial: "제품의 일부 영역은 아직 번역 중입니다.",
    nav: ["제품 둘러보기", "로그인", "시작하기", "작업 공간", "대시보드", "기회", "초안 작업실", "게시 대기열", "운영", "계정", "X 타임라인", "소스", "카테고리", "분석", "의사결정 검토", "설정", "키 관리", "자동화", "글쓰기 스타일", "공유 프로필", "계정 보안", "로그아웃", "로그아웃 중…", "로그아웃할 수 없습니다. 다시 시도하세요.", "리서치 및 게시 데스크", "언어", "메뉴 열기", "언어 및 화면 설정", "검증된 성과"],
    landing: ["Ispatla — 내 AI 키를 추가하고 출처가 있는 기회를 골라 초안을 편집하세요.", "실제 X 신호를 내 목소리의 초안으로 만드세요. 기회를 고르고, 게시를 승인하고, 결과의 근거를 확인하세요.", "주 메뉴", "Ispatla", "Social AI HitMaker", "알고리즘에 매달리지 마세요.", "다음 행동에 근거를 더하세요.", "실제 X 신호를 내 목소리의 초안으로 만드세요. 기회를 고르고, 게시를 승인하고, 결과의 근거를 확인하세요.", "계정 만들기", "소스 코드", "예시 흐름 · 제품 둘러보기", "소스 → 판단 → 게시", "근거 표시", "소스 게시물", "원본 링크와 출처 보존", "기회", "관련성과 근거 검토", "초안", "계정의 말투에 맞춘 편집 가능한 글", "게시 결과", "로컬 상태와 X 근거는 구분됩니다", "내 X 연결하기", "프로필과 게시물에서 찾은 주제를 검토하세요. 언어와 문체를 고르세요.", "신호에 내 목소리 담기", "내 AI 키를 추가하고 출처가 있는 기회를 골라 초안을 편집하세요.", "승인. 게시. 학습.", "게시 전에 최종 문안을 확인하세요. 확정된 게시와 X가 제공하는 지표를 살펴보세요.", "로컬에서 실행하고 소스 확인", "컨트롤 룸이 어떻게 작동하는지 살펴보세요.", "인증 정보가 필요 없는 데모에서 소스, 초안, 영수증을 확인하세요. 계정 연결과 게시 권한이 시작되는 지점도 표시됩니다.", "문서 및 데모", "Ispatla · X 리서치 및 게시 데스크", "신뢰 및 제품 정보", "보안", "개인정보", "약관", ""],
  },
};

function dictionaryFrom(locale: LocaleCopy): Dictionary {
  if (locale.nav.length !== navKeys.length || locale.landing.length !== landingKeys.length) {
    throw new Error("locale dictionary does not match the registered key shape");
  }
  return {
    status: { partial: locale.partial },
    nav: Object.fromEntries(navKeys.map((key, index) => [key, locale.nav[index]])) as Dictionary["nav"],
    landing: Object.fromEntries(landingKeys.map((key, index) => [key, locale.landing[index]])) as Dictionary["landing"],
  };
}

export const dictionaries: Record<Locale, Dictionary> = Object.fromEntries(
  LOCALES.map((locale) => [locale, dictionaryFrom(copy[locale])]),
) as Record<Locale, Dictionary>;

export function getDictionary(locale: Locale): Dictionary {
  return dictionaries[locale];
}
