import { LOCALES, type Locale } from "./config";

export type Dictionary = {
  status: { partial: string };
  onboarding: Record<OnboardingKey, string>;
  nav: {
    tour: string; login: string; start: string; primary: string; dashboard: string; opportunities: string;
    drafts: string; queue: string; operations: string; accounts: string; sources: string;
    categories: string; analytics: string; evaluation: string; settings: string; keys: string;
    automation: string; style: string; profile: string; security: string; signOut: string;
    signOutPending: string; signOutError: string; shellDescription: string; language: string; menuOpen: string; appearance: string; leaderboard: string;
  };
  landing: {
    metadataTitle: string; metadataDescription: string; menuLabel: string; brand: string; eyebrow: string;
    headlineFirst: string; headlineSecond: string; intro: string; createAccount: string; sourceCode: string;
    flowLabel: string; flowTitle: string; proofVisible: string; sourcePost: string; sourceDetail: string;
    opportunity: string; opportunityDetail: string; draft: string; draftDetail: string; outcome: string;
    outcomeDetail: string; stepOne: string; stepOneDetail: string; stepTwo: string; stepTwoDetail: string;
    stepThree: string; stepThreeDetail: string; localLabel: string; localTitle: string; localDescription: string;
    docsDemo: string; footer: string; trustLabel: string; security: string; privacy: string; terms: string;
    partialNotice: string;
  };
};

type OnboardingKey =
  | "stepProfile" | "stepProfileDetail" | "stepX" | "stepXDetail" | "stepAi" | "stepAiDetail" | "stepAppearance" | "stepAppearanceDetail"
  | "workspaceLink" | "firstSteps" | "pageTitle" | "pageIntro" | "stepsLabel"
  | "profileTitle" | "profileImportedDescription" | "profileDescription" | "avatarAlt" | "addDisplayName" | "displayName" | "bio" | "visibility"
  | "publicVisibility" | "publicDescription" | "privateVisibility" | "privateDescription" | "saveFailed" | "incompleteProfile" | "saving" | "saveProfile" | "saveAndContinue"
  | "xTitle" | "xDescription" | "xConnected" | "xNotConnected" | "back" | "manageAccounts" | "continue"
  | "aiTitle" | "aiDescription" | "aiReady" | "aiNotReady" | "manageProviders" | "openWorkspace";

const onboardingKeys = [
  "stepProfile", "stepProfileDetail", "stepX", "stepXDetail", "stepAi", "stepAiDetail", "stepAppearance", "stepAppearanceDetail",
  "workspaceLink", "firstSteps", "pageTitle", "pageIntro", "stepsLabel", "profileTitle", "profileImportedDescription", "profileDescription",
  "avatarAlt", "addDisplayName", "displayName", "bio", "visibility", "publicVisibility", "publicDescription", "privateVisibility",
  "privateDescription", "saveFailed", "incompleteProfile", "saving", "saveProfile", "saveAndContinue", "xTitle", "xDescription", "xConnected",
  "xNotConnected", "back", "manageAccounts", "continue", "aiTitle", "aiDescription", "aiReady", "aiNotReady", "manageProviders", "openWorkspace",
] as const satisfies readonly OnboardingKey[];

const navKeys = [
  "tour", "login", "start", "primary", "dashboard", "opportunities", "drafts", "queue", "operations",
  "accounts", "sources", "categories", "analytics", "evaluation", "settings", "keys",
  "automation", "style", "profile", "security", "signOut", "signOutPending", "signOutError",
  "shellDescription", "language", "menuOpen", "appearance", "leaderboard",
] as const satisfies readonly (keyof Dictionary["nav"])[];

const landingKeys = [
  "metadataTitle", "metadataDescription", "menuLabel", "brand", "eyebrow", "headlineFirst", "headlineSecond",
  "intro", "createAccount", "sourceCode", "flowLabel", "flowTitle", "proofVisible", "sourcePost", "sourceDetail",
  "opportunity", "opportunityDetail", "draft", "draftDetail", "outcome", "outcomeDetail", "stepOne",
  "stepOneDetail", "stepTwo", "stepTwoDetail", "stepThree", "stepThreeDetail", "localLabel", "localTitle",
  "localDescription", "docsDemo", "footer", "trustLabel", "security", "privacy", "terms", "partialNotice",
] as const satisfies readonly (keyof Dictionary["landing"])[];

type LocaleCopy = { partial: string; nav: readonly string[]; landing: readonly string[] };

// Each row follows navKeys and landingKeys above. The final landing string is empty
// because these surfaces are fully translated and should not display a partial-copy notice.
const copy: Record<Locale, LocaleCopy> = {
  en: {
    partial: "Some sections of this product are still being translated.",
    nav: ["Product tour", "Sign in", "Get started", "Workspace", "Dashboard", "Opportunities", "Draft studio", "Publishing queue", "Operations", "Accounts", "Sources", "Categories", "Analytics", "Decision review", "Settings", "Key management", "Automation", "Writing style", "Sharing profile", "Account security", "Sign out", "Signing out…", "Could not sign out. Try again.", "Research and publishing desk", "Language", "Open menu", "Language and appearance", "Verified hits"],
    landing: ["Ispatla — Add your own AI key, choose a sourced opportunity, and shape an editable draft.", "Turn real 𝕏 signals into drafts in your voice. Choose the opportunity, approve the post, and see the evidence behind the result.", "Main menu", "Ispatla", "Social AI HitMaker", "Stop begging the algorithm.", "Make your next move count.", "Turn real 𝕏 signals into drafts in your voice. Choose the opportunity, approve the post, and see the evidence behind the result.", "Create an account", "Source code", "Sample workflow · product tour", "Source → decision → publication", "evidence visible", "Source post", "original link and source retained", "Opportunity", "review relevance and evidence", "Draft", "editable text in your account’s voice", "Publishing outcome", "local status and 𝕏 evidence stay distinct", "Connect your 𝕏", "Review the topics detected from your profile and posts. Set your language and writing style.", "Give the signal your voice", "Add your own AI key, choose a sourced opportunity, and shape an editable draft.", "Approve. Publish. Learn.", "Review the final text before publishing. Follow confirmed publications and the metrics 𝕏 actually provides.", "Run locally and inspect the source", "See how the control room works.", "Explore sources, drafts, and receipts in a demo that needs no credentials. The point where account connection and publishing permission begin stays visible.", "Documentation and demo", "Ispatla · research and publishing desk for 𝕏", "Trust and product information", "Security", "Privacy", "Terms", ""],
  },
  "zh-CN": {
    partial: "本产品的部分内容仍在翻译中。",
    nav: ["产品介绍", "登录", "开始使用", "工作区", "控制面板", "机会", "草稿工作室", "发布队列", "运营", "账号", "来源", "类别", "分析", "决策评估", "设置", "密钥管理", "自动化", "写作风格", "分享资料", "账号安全", "退出登录", "正在退出…", "退出失败，请重试。", "研究与发布工作台", "语言", "打开菜单", "语言与外观", "已验证热门帖子"],
    landing: ["Ispatla — 添加自己的 AI 密钥，选择有来源的机会，编辑草稿。", "将真实的 𝕏 动态转为符合你风格的草稿。选择机会，批准发布，查看结果背后的证据。", "主菜单", "Ispatla", "Social AI HitMaker", "别再讨好算法。", "让每一步都有依据。", "将真实的 𝕏 动态转为符合你风格的草稿。选择机会，批准发布，查看结果背后的证据。", "创建账号", "源代码", "示例流程 · 产品介绍", "来源 → 决策 → 发布", "证据清晰可见", "来源帖文", "保留原始链接和来源", "机会", "审查相关性与证据", "草稿", "符合账号风格的可编辑文字", "发布结果", "本地状态与 𝕏 证据分别呈现", "连接你的 𝕏 账号", "审核从资料与帖子识别的主题，设置语言与写作风格。", "用你的声音表达信号", "添加自己的 AI 密钥，选择有来源的机会，编辑草稿。", "审核、发布、学习。", "发布前审核最终文本，跟踪已确认的发布及 𝕏 实际提供的数据。", "本地运行并查看来源", "了解控制台的运作方式。", "无需凭据的演示可查看来源、草稿和回执。账号连接与发布授权从何处开始，也会清楚显示。", "文档与演示", "Ispatla · 𝕏 研究与发布工作台", "信任与产品信息", "安全", "隐私", "条款", ""],
  },
  hi: {
    partial: "इस उत्पाद के कुछ हिस्सों का अनुवाद अभी जारी है।",
    nav: ["उत्पाद परिचय", "साइन इन", "शुरू करें", "कार्यस्थल", "डैशबोर्ड", "अवसर", "ड्राफ़्ट स्टूडियो", "प्रकाशन कतार", "संचालन", "खाते", "स्रोत", "श्रेणियाँ", "विश्लेषण", "निर्णय समीक्षा", "सेटिंग", "कुंजी प्रबंधन", "स्वचालन", "लेखन शैली", "साझा प्रोफ़ाइल", "खाता सुरक्षा", "साइन आउट", "साइन आउट हो रहा है…", "साइन आउट नहीं हुआ। फिर कोशिश करें।", "शोध और प्रकाशन डेस्क", "भाषा", "मेनू खोलें", "भाषा और रूप", "सत्यापित सफल पोस्ट"],
    landing: ["Ispatla — अपनी AI कुंजी जोड़ें, स्रोत वाला अवसर चुनें और ड्राफ़्ट संपादित करें।", "असली 𝕏 संकेतों को अपनी आवाज़ में ड्राफ़्ट बनाएँ। अवसर चुनें, पोस्ट मंज़ूर करें और परिणाम का प्रमाण देखें।", "मुख्य मेनू", "Ispatla", "Social AI HitMaker", "एल्गोरिदम से भीख माँगना बंद करें।", "हर कदम को मायने दें।", "असली 𝕏 संकेतों को अपनी आवाज़ में ड्राफ़्ट बनाएँ। अवसर चुनें, पोस्ट मंज़ूर करें और परिणाम का प्रमाण देखें।", "खाता बनाएँ", "स्रोत कोड", "उदाहरण कार्यप्रवाह · उत्पाद परिचय", "स्रोत → निर्णय → प्रकाशन", "प्रमाण दिखाई देता है", "स्रोत पोस्ट", "मूल लिंक और स्रोत सुरक्षित", "अवसर", "प्रासंगिकता और प्रमाण की समीक्षा", "ड्राफ़्ट", "आपके खाते की आवाज़ में संपादन योग्य पाठ", "प्रकाशन परिणाम", "स्थानीय स्थिति और 𝕏 प्रमाण अलग रहते हैं", "अपना 𝕏 जोड़ें", "प्रोफ़ाइल और पोस्ट से मिले विषय जाँचें। भाषा और लेखन शैली चुनें।", "संकेत को अपनी आवाज़ दें", "अपनी AI कुंजी जोड़ें, स्रोत वाला अवसर चुनें और ड्राफ़्ट संपादित करें।", "मंज़ूर करें। प्रकाशित करें। सीखें।", "प्रकाशन से पहले अंतिम पाठ जाँचें। पुष्ट प्रकाशन और 𝕏 से मिले आँकड़े देखें।", "स्थानीय रूप से चलाएँ और स्रोत देखें", "देखें कि नियंत्रण कक्ष कैसे काम करता है।", "बिना किसी क्रेडेंशियल वाले डेमो में स्रोत, ड्राफ़्ट और रसीदें देखें। खाता जोड़ने और प्रकाशन की अनुमति शुरू होने का बिंदु साफ़ दिखता है।", "दस्तावेज़ और डेमो", "Ispatla · 𝕏 शोध और प्रकाशन डेस्क", "विश्वास और उत्पाद जानकारी", "सुरक्षा", "गोपनीयता", "शर्तें", ""],
  },
  es: {
    partial: "Algunas secciones del producto todavía se están traduciendo.",
    nav: ["Recorrido del producto", "Iniciar sesión", "Empezar", "Espacio de trabajo", "Panel", "Oportunidades", "Estudio de borradores", "Cola de publicación", "Operaciones", "Cuentas", "Fuentes", "Categorías", "Analítica", "Revisión de decisiones", "Ajustes", "Gestión de claves", "Automatización", "Estilo de escritura", "Perfil para compartir", "Seguridad de la cuenta", "Cerrar sesión", "Cerrando sesión…", "No se pudo cerrar sesión. Inténtalo de nuevo.", "Espacio de investigación y publicación", "Idioma", "Abrir menú", "Idioma y apariencia", "Éxitos verificados"],
    landing: ["Ispatla — Añade tu clave de IA, elige una oportunidad con fuente y edita el borrador.", "Convierte señales reales de 𝕏 en borradores con tu voz. Elige la oportunidad, aprueba la publicación y consulta las pruebas del resultado.", "Menú principal", "Ispatla", "Social AI HitMaker", "Deja de rogar al algoritmo.", "Haz que tu próximo paso cuente.", "Convierte señales reales de 𝕏 en borradores con tu voz. Elige la oportunidad, aprueba la publicación y consulta las pruebas del resultado.", "Crear una cuenta", "Código fuente", "Flujo de ejemplo · recorrido del producto", "Fuente → decisión → publicación", "pruebas visibles", "Publicación de origen", "se conservan el enlace original y la fuente", "Oportunidad", "revisar relevancia y pruebas", "Borrador", "texto editable con la voz de tu cuenta", "Resultado de publicación", "el estado local y las pruebas de 𝕏 se mantienen separados", "Conecta tu 𝕏", "Revisa los temas detectados en tu perfil y publicaciones. Elige tu idioma y estilo.", "Dale tu voz a la señal", "Añade tu clave de IA, elige una oportunidad con fuente y edita el borrador.", "Aprueba. Publica. Aprende.", "Revisa el texto final antes de publicar. Sigue publicaciones confirmadas y métricas que 𝕏 proporciona.", "Ejecuta en local y consulta la fuente", "Descubre cómo funciona el centro de control.", "Explora fuentes, borradores y comprobantes en una demo sin credenciales. El punto en que comienzan la conexión de la cuenta y el permiso de publicación queda claro.", "Documentación y demo", "Ispatla · investigación y publicación en 𝕏", "Confianza e información del producto", "Seguridad", "Privacidad", "Condiciones", ""],
  },
  fr: {
    partial: "Certaines sections du produit sont encore en cours de traduction.",
    nav: ["Visite du produit", "Se connecter", "Commencer", "Espace de travail", "Tableau de bord", "Occasions", "Atelier de brouillons", "File de publication", "Opérations", "Comptes", "Sources", "Catégories", "Analyses", "Revue des décisions", "Paramètres", "Gestion des clés", "Automatisation", "Style rédactionnel", "Profil de partage", "Sécurité du compte", "Se déconnecter", "Déconnexion…", "Déconnexion impossible. Réessayez.", "Espace de recherche et de publication", "Langue", "Ouvrir le menu", "Langue et apparence", "Succès vérifiés"],
    landing: ["Ispatla — Ajoute ta clé IA, choisis une occasion avec sa source et modifie le brouillon.", "Transforme les signaux réels de 𝕏 en brouillons à ta voix. Choisis une occasion, approuve la publication et consulte les preuves du résultat.", "Menu principal", "Ispatla", "Social AI HitMaker", "Arrête de supplier l’algorithme.", "Donne du poids à ton prochain geste.", "Transforme les signaux réels de 𝕏 en brouillons à ta voix. Choisis une occasion, approuve la publication et consulte les preuves du résultat.", "Créer un compte", "Code source", "Flux type · visite du produit", "Source → décision → publication", "preuves visibles", "Publication source", "lien d’origine et source conservés", "Occasion", "examiner la pertinence et les preuves", "Brouillon", "texte modifiable dans la voix de votre compte", "Résultat de publication", "état local et preuves 𝕏 restent distincts", "Connecte ton 𝕏", "Vérifie les thèmes détectés dans ton profil et tes publications. Choisis ta langue et ton style.", "Donne ta voix au signal", "Ajoute ta clé IA, choisis une occasion avec sa source et modifie le brouillon.", "Approuve. Publie. Apprends.", "Vérifie le texte final avant publication. Suis les publications confirmées et les métriques fournies par 𝕏.", "Exécuter localement et examiner la source", "Découvrez le fonctionnement du poste de contrôle.", "Consultez sources, brouillons et reçus dans une démo sans identifiants. Le début de la connexion du compte et de l’autorisation de publier reste visible.", "Documentation et démo", "Ispatla · recherche et publication sur 𝕏", "Confiance et informations produit", "Sécurité", "Confidentialité", "Conditions", ""],
  },
  ar: {
    partial: "لا تزال بعض أقسام المنتج قيد الترجمة.",
    nav: ["جولة المنتج", "تسجيل الدخول", "ابدأ الآن", "مساحة العمل", "لوحة التحكم", "الفرص", "استوديو المسودات", "قائمة النشر", "العمليات", "الحسابات", "المصادر", "الفئات", "التحليلات", "مراجعة القرارات", "الإعدادات", "إدارة المفاتيح", "الأتمتة", "أسلوب الكتابة", "ملف المشاركة", "أمان الحساب", "تسجيل الخروج", "جارٍ تسجيل الخروج…", "تعذّر تسجيل الخروج. حاول مرة أخرى.", "مكتب البحث والنشر", "اللغة", "فتح القائمة", "اللغة والمظهر", "المنشورات الناجحة الموثقة"],
    landing: ["Ispatla — أضف مفتاح الذكاء الاصطناعي الخاص بك، واختر فرصة لها مصدر، وحرّر المسودة.", "حوّل إشارات 𝕏 الحقيقية إلى مسودات بصوتك. اختر الفرصة، وافق على المنشور، وراجع أدلة النتيجة.", "القائمة الرئيسية", "Ispatla", "Social AI HitMaker", "توقف عن التوسل للخوارزمية.", "اجعل خطوتك القادمة ذات أثر.", "حوّل إشارات 𝕏 الحقيقية إلى مسودات بصوتك. اختر الفرصة، وافق على المنشور، وراجع أدلة النتيجة.", "إنشاء حساب", "الشيفرة المصدرية", "مسار نموذجي · جولة المنتج", "المصدر ← القرار ← النشر", "الأدلة واضحة", "منشور المصدر", "يُحفظ الرابط الأصلي والمصدر", "فرصة", "مراجعة الملاءمة والأدلة", "مسودة", "نص قابل للتحرير بصوت حسابك", "نتيجة النشر", "تبقى الحالة المحلية وأدلة 𝕏 منفصلتين", "اربط حسابك في 𝕏", "راجع المواضيع المستخرجة من ملفك ومنشوراتك. اختر لغتك وأسلوبك.", "امنح الإشارة صوتك", "أضف مفتاح الذكاء الاصطناعي الخاص بك، واختر فرصة لها مصدر، وحرّر المسودة.", "وافق. انشر. تعلّم.", "راجع النص النهائي قبل النشر. تابع المنشورات المؤكدة والمقاييس التي يقدّمها 𝕏 فعليًا.", "شغّل محليًا وافحص المصدر", "تعرّف على طريقة عمل غرفة التحكم.", "استكشف المصادر والمسودات والإيصالات في عرض تجريبي لا يحتاج إلى بيانات اعتماد. يظل موضع بدء ربط الحساب وإذن النشر واضحًا.", "الوثائق والعرض التجريبي", "Ispatla · مكتب البحث والنشر على 𝕏", "الثقة ومعلومات المنتج", "الأمان", "الخصوصية", "الشروط", ""],
  },
  bn: {
    partial: "পণ্যের কিছু অংশের অনুবাদ এখনও চলছে।",
    nav: ["পণ্য পরিচিতি", "সাইন ইন", "শুরু করুন", "কর্মক্ষেত্র", "ড্যাশবোর্ড", "সুযোগ", "খসড়া স্টুডিও", "প্রকাশনা সারি", "পরিচালনা", "অ্যাকাউন্ট", "উৎস", "বিভাগ", "বিশ্লেষণ", "সিদ্ধান্ত পর্যালোচনা", "সেটিংস", "কী ব্যবস্থাপনা", "স্বয়ংক্রিয়করণ", "লেখার ধরন", "শেয়ার প্রোফাইল", "অ্যাকাউন্ট নিরাপত্তা", "সাইন আউট", "সাইন আউট হচ্ছে…", "সাইন আউট করা যায়নি। আবার চেষ্টা করুন।", "গবেষণা ও প্রকাশনা ডেস্ক", "ভাষা", "মেনু খুলুন", "ভাষা ও চেহারা", "যাচাইকৃত সফল পোস্ট"],
    landing: ["Ispatla — নিজের AI কী যোগ করুন, উৎসসহ সুযোগ বেছে নিন এবং খসড়া সম্পাদনা করুন।", "বাস্তব 𝕏 সংকেত থেকে নিজের ভাষায় খসড়া বানান। সুযোগ বেছে নিন, পোস্ট অনুমোদন করুন এবং ফলের প্রমাণ দেখুন।", "প্রধান মেনু", "Ispatla", "Social AI HitMaker", "অ্যালগরিদমের কাছে মিনতি বন্ধ করুন।", "পরের পদক্ষেপকে অর্থবহ করুন।", "বাস্তব 𝕏 সংকেত থেকে নিজের ভাষায় খসড়া বানান। সুযোগ বেছে নিন, পোস্ট অনুমোদন করুন এবং ফলের প্রমাণ দেখুন।", "অ্যাকাউন্ট তৈরি করুন", "সোর্স কোড", "নমুনা কার্যপ্রবাহ · পণ্য পরিচিতি", "উৎস → সিদ্ধান্ত → প্রকাশনা", "প্রমাণ দৃশ্যমান", "উৎস পোস্ট", "মূল লিংক ও উৎস সংরক্ষিত", "সুযোগ", "প্রাসঙ্গিকতা ও প্রমাণ পর্যালোচনা", "খসড়া", "আপনার অ্যাকাউন্টের ভাষায় সম্পাদনাযোগ্য লেখা", "প্রকাশনার ফল", "স্থানীয় অবস্থা ও 𝕏-এর প্রমাণ আলাদা থাকে", "আপনার 𝕏 যুক্ত করুন", "প্রোফাইল ও পোস্ট থেকে শনাক্ত বিষয় যাচাই করুন। ভাষা ও লেখার ধরন ঠিক করুন।", "সংকেতকে নিজের ভাষা দিন", "নিজের AI কী যোগ করুন, উৎসসহ সুযোগ বেছে নিন এবং খসড়া সম্পাদনা করুন।", "অনুমোদন। প্রকাশ। শেখা।", "প্রকাশের আগে চূড়ান্ত লেখা দেখুন। নিশ্চিত প্রকাশনা ও 𝕏-এর দেওয়া পরিসংখ্যান অনুসরণ করুন।", "স্থানীয়ভাবে চালান ও উৎস দেখুন", "কন্ট্রোল রুম কীভাবে কাজ করে দেখুন।", "ক্রেডেনশিয়াল ছাড়াই ডেমোতে উৎস, খসড়া ও রসিদ দেখুন। অ্যাকাউন্ট সংযোগ ও প্রকাশনার অনুমতি কোথায় শুরু হয় তা দৃশ্যমান থাকে।", "নথি ও ডেমো", "Ispatla · 𝕏 গবেষণা ও প্রকাশনা ডেস্ক", "বিশ্বাস ও পণ্যের তথ্য", "নিরাপত্তা", "গোপনীয়তা", "শর্তাবলি", ""],
  },
  "pt-BR": {
    partial: "Algumas seções do produto ainda estão sendo traduzidas.",
    nav: ["Tour do produto", "Entrar", "Começar", "Espaço de trabalho", "Painel", "Oportunidades", "Estúdio de rascunhos", "Fila de publicação", "Operações", "Contas", "Fontes", "Categorias", "Análises", "Revisão de decisões", "Configurações", "Gerenciamento de chaves", "Automação", "Estilo de escrita", "Perfil de compartilhamento", "Segurança da conta", "Sair", "Saindo…", "Não foi possível sair. Tente novamente.", "Central de pesquisa e publicação", "Idioma", "Abrir menu", "Idioma e aparência", "Sucessos verificados"],
    landing: ["Ispatla — Adicione sua chave de IA, escolha uma oportunidade com fonte e edite o rascunho.", "Transforme sinais reais do 𝕏 em rascunhos com sua voz. Escolha a oportunidade, aprove a publicação e veja as evidências do resultado.", "Menu principal", "Ispatla", "Social AI HitMaker", "Pare de implorar ao algoritmo.", "Faça seu próximo passo valer.", "Transforme sinais reais do 𝕏 em rascunhos com sua voz. Escolha a oportunidade, aprove a publicação e veja as evidências do resultado.", "Criar uma conta", "Código-fonte", "Fluxo de exemplo · tour do produto", "Fonte → decisão → publicação", "evidência visível", "Post de origem", "link original e fonte preservados", "Oportunidade", "revisar relevância e evidências", "Rascunho", "texto editável com a voz da sua conta", "Resultado da publicação", "status local e evidências do 𝕏 permanecem distintos", "Conecte seu 𝕏", "Revise os temas detectados no perfil e nas publicações. Escolha idioma e estilo.", "Dê sua voz ao sinal", "Adicione sua chave de IA, escolha uma oportunidade com fonte e edite o rascunho.", "Aprove. Publique. Aprenda.", "Revise o texto final antes de publicar. Acompanhe publicações confirmadas e métricas fornecidas pelo 𝕏.", "Execute localmente e inspecione a fonte", "Veja como funciona a central de controle.", "Explore fontes, rascunhos e comprovantes em uma demonstração que não exige credenciais. O início da conexão da conta e da permissão de publicação fica visível.", "Documentação e demonstração", "Ispatla · pesquisa e publicação no 𝕏", "Confiança e informações do produto", "Segurança", "Privacidade", "Termos", ""],
  },
  ru: {
    partial: "Некоторые разделы продукта всё ещё переводятся.",
    nav: ["Обзор продукта", "Войти", "Начать", "Рабочее пространство", "Панель управления", "Возможности", "Редактор черновиков", "Очередь публикаций", "Операции", "Аккаунты", "Источники", "Категории", "Аналитика", "Проверка решений", "Настройки", "Управление ключами", "Автоматизация", "Стиль письма", "Профиль для публикаций", "Безопасность аккаунта", "Выйти", "Выход…", "Не удалось выйти. Попробуйте ещё раз.", "Рабочее место для исследований и публикаций", "Язык", "Открыть меню", "Язык и оформление", "Подтверждённые успехи"],
    landing: ["Ispatla — Добавьте свой ключ ИИ, выберите возможность с источником и отредактируйте черновик.", "Превращайте реальные сигналы 𝕏 в черновики своим голосом. Выбирайте возможности, утверждайте публикации и изучайте доказательства результата.", "Главное меню", "Ispatla", "Social AI HitMaker", "Хватит умолять алгоритм.", "Пусть следующий шаг будет осмысленным.", "Превращайте реальные сигналы 𝕏 в черновики своим голосом. Выбирайте возможности, утверждайте публикации и изучайте доказательства результата.", "Создать аккаунт", "Исходный код", "Пример процесса · обзор продукта", "Источник → решение → публикация", "доказательства видны", "Исходная публикация", "исходная ссылка и источник сохранены", "Возможность", "оценить релевантность и доказательства", "Черновик", "редактируемый текст в стиле аккаунта", "Результат публикации", "локальный статус и данные 𝕏 разделены", "Подключите свой 𝕏", "Проверьте темы из профиля и публикаций. Выберите язык и стиль.", "Придайте сигналу свой голос", "Добавьте свой ключ ИИ, выберите возможность с источником и отредактируйте черновик.", "Утвердите. Опубликуйте. Учитесь.", "Проверьте итоговый текст перед публикацией. Следите за подтверждёнными публикациями и доступными метриками 𝕏.", "Запустите локально и изучите источник", "Посмотрите, как работает центр управления.", "Изучайте источники, черновики и квитанции в демо без учётных данных. Граница подключения аккаунта и разрешения на публикацию остаётся видимой.", "Документация и демо", "Ispatla · исследования и публикации в 𝕏", "Доверие и информация о продукте", "Безопасность", "Конфиденциальность", "Условия", ""],
  },
  id: {
    partial: "Beberapa bagian produk ini masih dalam proses penerjemahan.",
    nav: ["Tur produk", "Masuk", "Mulai", "Ruang kerja", "Dasbor", "Peluang", "Studio draf", "Antrean publikasi", "Operasi", "Akun", "Sumber", "Kategori", "Analitik", "Tinjauan keputusan", "Pengaturan", "Pengelolaan kunci", "Otomatisasi", "Gaya penulisan", "Profil berbagi", "Keamanan akun", "Keluar", "Sedang keluar…", "Tidak dapat keluar. Coba lagi.", "Meja riset dan publikasi", "Bahasa", "Buka menu", "Bahasa dan tampilan", "Hasil terverifikasi"],
    landing: ["Ispatla — Tambahkan kunci AI sendiri, pilih peluang bersumber, dan sunting draf.", "Ubah sinyal nyata 𝕏 menjadi draf dengan suaramu. Pilih peluang, setujui postingan, dan lihat bukti hasilnya.", "Menu utama", "Ispatla", "Social AI HitMaker", "Berhenti memohon pada algoritma.", "Buat langkah berikutnya berarti.", "Ubah sinyal nyata 𝕏 menjadi draf dengan suaramu. Pilih peluang, setujui postingan, dan lihat bukti hasilnya.", "Buat akun", "Kode sumber", "Alur contoh · tur produk", "Sumber → keputusan → publikasi", "bukti terlihat", "Kiriman sumber", "tautan asli dan sumber tetap tersimpan", "Peluang", "tinjau relevansi dan bukti", "Draf", "teks yang dapat diedit dengan gaya akun Anda", "Hasil publikasi", "status lokal dan bukti 𝕏 tetap terpisah", "Hubungkan 𝕏-mu", "Tinjau topik dari profil dan postingan. Pilih bahasa dan gaya tulisan.", "Beri sinyal suaramu", "Tambahkan kunci AI sendiri, pilih peluang bersumber, dan sunting draf.", "Setujui. Terbitkan. Pelajari.", "Tinjau teks akhir sebelum terbit. Ikuti publikasi terkonfirmasi dan metrik yang disediakan 𝕏.", "Jalankan secara lokal dan periksa sumber", "Lihat cara kerja pusat kendali.", "Jelajahi sumber, draf, dan tanda terima dalam demo tanpa kredensial. Titik dimulainya koneksi akun dan izin publikasi tetap terlihat.", "Dokumentasi dan demo", "Ispatla · riset dan publikasi 𝕏", "Kepercayaan dan informasi produk", "Keamanan", "Privasi", "Ketentuan", ""],
  },
  ur: {
    partial: "اس پروڈکٹ کے کچھ حصوں کا ترجمہ ابھی جاری ہے۔",
    nav: ["پروڈکٹ کا تعارف", "سائن اِن", "شروع کریں", "کام کی جگہ", "ڈیش بورڈ", "مواقع", "مسودہ اسٹوڈیو", "اشاعت کی قطار", "آپریشنز", "اکاؤنٹس", "ذرائع", "زمرے", "تجزیات", "فیصلوں کا جائزہ", "ترتیبات", "کلیدوں کا انتظام", "خودکاری", "تحریری انداز", "شیئرنگ پروفائل", "اکاؤنٹ سیکیورٹی", "سائن آؤٹ", "سائن آؤٹ ہو رہا ہے…", "سائن آؤٹ نہیں ہو سکا۔ دوبارہ کوشش کریں۔", "تحقیق اور اشاعت کی میز", "زبان", "مینو کھولیں", "زبان اور ظاہری شکل", "تصدیق شدہ کامیاب پوسٹس"],
    landing: ["Ispatla — اپنی AI کلید شامل کریں، ماخذ والا موقع چنیں اور مسودہ ترمیم کریں۔", "𝕏 کے حقیقی اشاروں سے اپنی آواز میں مسودے بنائیں۔ موقع چنیں، پوسٹ منظور کریں اور نتیجے کے شواہد دیکھیں۔", "مرکزی مینو", "Ispatla", "Social AI HitMaker", "الگورتھم سے منتیں کرنا بند کریں۔", "اپنے اگلے قدم کو معنی دیں۔", "𝕏 کے حقیقی اشاروں سے اپنی آواز میں مسودے بنائیں۔ موقع چنیں، پوسٹ منظور کریں اور نتیجے کے شواہد دیکھیں۔", "اکاؤنٹ بنائیں", "ماخذ کوڈ", "مثالی طریقۂ کار · پروڈکٹ کا تعارف", "ذریعہ → فیصلہ → اشاعت", "شواہد واضح ہیں", "ماخذ پوسٹ", "اصل لنک اور ذریعہ محفوظ ہیں", "موقع", "تعلق اور شواہد کا جائزہ", "مسودہ", "آپ کے اکاؤنٹ کے انداز میں قابلِ ترمیم متن", "اشاعت کا نتیجہ", "مقامی حالت اور 𝕏 شواہد الگ رہتے ہیں", "اپنا 𝕏 جوڑیں", "پروفائل اور پوسٹوں سے ملے موضوعات دیکھیں۔ زبان اور انداز منتخب کریں۔", "اشارے کو اپنی آواز دیں", "اپنی AI کلید شامل کریں، ماخذ والا موقع چنیں اور مسودہ ترمیم کریں۔", "منظور کریں۔ شائع کریں۔ سیکھیں۔", "اشاعت سے پہلے آخری متن دیکھیں۔ تصدیق شدہ اشاعت اور 𝕏 کے فراہم کردہ اعداد دیکھیں۔", "مقامی طور پر چلائیں اور ذریعہ دیکھیں", "دیکھیں کہ کنٹرول روم کیسے کام کرتا ہے۔", "ایسے ڈیمو میں ذرائع، مسودے اور رسیدیں دیکھیں جسے اسناد کی ضرورت نہیں۔ اکاؤنٹ جوڑنے اور اشاعت کی اجازت شروع ہونے کی جگہ واضح رہتی ہے۔", "دستاویزات اور ڈیمو", "Ispatla · 𝕏 تحقیق اور اشاعت کی میز", "اعتماد اور پروڈکٹ کی معلومات", "سیکیورٹی", "رازداری", "شرائط", ""],
  },
  de: {
    partial: "Einige Bereiche dieses Produkts werden noch übersetzt.",
    nav: ["Produkttour", "Anmelden", "Loslegen", "Arbeitsbereich", "Übersicht", "Chancen", "Entwurfsstudio", "Veröffentlichungswarteschlange", "Betrieb", "Konten", "Quellen", "Kategorien", "Analysen", "Entscheidungsprüfung", "Einstellungen", "Schlüsselverwaltung", "Automatisierung", "Schreibstil", "Freigabeprofil", "Kontosicherheit", "Abmelden", "Abmeldung läuft…", "Abmeldung fehlgeschlagen. Bitte erneut versuchen.", "Arbeitsplatz für Recherche und Veröffentlichung", "Sprache", "Menü öffnen", "Sprache und Darstellung", "Verifizierte Erfolge"],
    landing: ["Ispatla — Füge deinen KI-Schlüssel hinzu, wähle eine belegte Chance und bearbeite den Entwurf.", "Mach aus echten 𝕏-Signalen Entwürfe in deiner Stimme. Wähle die Chance, bestätige den Beitrag und prüfe die Belege des Ergebnisses.", "Hauptmenü", "Ispatla", "Social AI HitMaker", "Hör auf, den Algorithmus anzuflehen.", "Gib deinem nächsten Schritt Gewicht.", "Mach aus echten 𝕏-Signalen Entwürfe in deiner Stimme. Wähle die Chance, bestätige den Beitrag und prüfe die Belege des Ergebnisses.", "Konto erstellen", "Quellcode", "Beispielablauf · Produkttour", "Quelle → Entscheidung → Veröffentlichung", "Belege sichtbar", "Quellbeitrag", "Original-Link und Quelle bleiben erhalten", "Chance", "Relevanz und Belege prüfen", "Entwurf", "bearbeitbarer Text im Stil Ihres Kontos", "Veröffentlichungsergebnis", "lokaler Status und 𝕏-Belege bleiben getrennt", "Verbinde dein 𝕏", "Prüfe erkannte Themen aus Profil und Beiträgen. Wähle Sprache und Schreibstil.", "Gib dem Signal deine Stimme", "Füge deinen KI-Schlüssel hinzu, wähle eine belegte Chance und bearbeite den Entwurf.", "Prüfen. Veröffentlichen. Lernen.", "Prüfe den fertigen Text. Verfolge bestätigte Veröffentlichungen und die von 𝕏 bereitgestellten Kennzahlen.", "Lokal ausführen und Quelle prüfen", "Erfahren Sie, wie die Schaltzentrale funktioniert.", "Entdecken Sie Quellen, Entwürfe und Belege in einer Demo ohne Zugangsdaten. Der Beginn der Kontoverbindung und der Veröffentlichungsfreigabe bleibt sichtbar.", "Dokumentation und Demo", "Ispatla · Recherche und Veröffentlichung auf 𝕏", "Vertrauen und Produktinformationen", "Sicherheit", "Datenschutz", "Bedingungen", ""],
  },
  ja: {
    partial: "製品の一部は現在翻訳中です。",
    nav: ["製品ツアー", "ログイン", "利用を開始", "ワークスペース", "ダッシュボード", "機会", "下書きスタジオ", "公開キュー", "運用", "アカウント", "ソース", "カテゴリ", "分析", "判断の確認", "設定", "キー管理", "自動化", "文章スタイル", "共有プロフィール", "アカウントのセキュリティ", "ログアウト", "ログアウト中…", "ログアウトできませんでした。もう一度お試しください。", "リサーチと公開のデスク", "言語", "メニューを開く", "言語と外観", "検証済みの成果"],
    landing: ["Ispatla — 自分のAIキーを追加し、出典のある機会を選んで下書きを編集します。", "実際の𝕏の動きから、あなたの声で下書きを作成。機会を選び、投稿を承認し、結果の根拠を確認できます。", "メインメニュー", "Ispatla", "Social AI HitMaker", "アルゴリズムに媚びるのは終わり。", "次の一手に根拠を。", "実際の𝕏の動きから、あなたの声で下書きを作成。機会を選び、投稿を承認し、結果の根拠を確認できます。", "アカウントを作成", "ソースコード", "ワークフロー例 · 製品ツアー", "ソース → 判断 → 公開", "根拠を表示", "ソース投稿", "元のリンクとソースを保持", "機会", "関連性と根拠を確認", "下書き", "アカウントの文体で編集できる文章", "公開結果", "ローカルの状態と 𝕏 の根拠は別々に表示", "𝕏アカウントを接続", "プロフィールと投稿から検出したテーマを確認。言語と文体を設定します。", "シグナルをあなたの声に", "自分のAIキーを追加し、出典のある機会を選んで下書きを編集します。", "確認。投稿。学習。", "投稿前に最終文面を確認。確定した投稿と𝕏が提供する指標を追跡します。", "ローカルで実行してソースを確認", "コントロールルームの仕組みをご覧ください。", "認証情報なしのデモでソース、下書き、受領記録を確認できます。アカウント接続と公開許可の開始点も明示されます。", "ドキュメントとデモ", "Ispatla · 𝕏 リサーチ・公開デスク", "信頼と製品情報", "セキュリティ", "プライバシー", "利用規約", ""],
  },
  sw: {
    partial: "Baadhi ya sehemu za bidhaa hii bado zinatafsiriwa.",
    nav: ["Utambulisho wa bidhaa", "Ingia", "Anza", "Nafasi ya kazi", "Dashibodi", "Fursa", "Studio ya rasimu", "Foleni ya uchapishaji", "Shughuli", "Akaunti", "Vyanzo", "Kategoria", "Uchanganuzi", "Kagua maamuzi", "Mipangilio", "Usimamizi wa funguo", "Uendeshaji otomatiki", "Mtindo wa uandishi", "Wasifu wa kushiriki", "Usalama wa akaunti", "Ondoka", "Unatoka…", "Imeshindwa kutoka. Jaribu tena.", "Dawati la utafiti na uchapishaji", "Lugha", "Fungua menyu", "Lugha na mwonekano", "Mafanikio yaliyothibitishwa"],
    landing: ["Ispatla — Ongeza ufunguo wako wa AI, chagua fursa yenye chanzo, na hariri rasimu.", "Geuza ishara halisi za 𝕏 kuwa rasimu kwa sauti yako. Chagua fursa, idhinisha chapisho, na uone ushahidi wa matokeo.", "Menyu kuu", "Ispatla", "Social AI HitMaker", "Acha kuisihi algoriti.", "Fanya hatua yako ijayo iwe na maana.", "Geuza ishara halisi za 𝕏 kuwa rasimu kwa sauti yako. Chagua fursa, idhinisha chapisho, na uone ushahidi wa matokeo.", "Fungua akaunti", "Msimbo chanzo", "Mtiririko wa mfano · utambulisho wa bidhaa", "Chanzo → uamuzi → uchapishaji", "ushahidi unaonekana", "Chapisho la chanzo", "kiungo asili na chanzo vimehifadhiwa", "Fursa", "kagua umuhimu na ushahidi", "Rasimu", "maandishi yanayoweza kuhaririwa kwa sauti ya akaunti yako", "Matokeo ya uchapishaji", "hali ya ndani na ushahidi wa 𝕏 vinabaki tofauti", "Unganisha 𝕏 yako", "Kagua mada zilizotambuliwa katika wasifu na machapisho. Chagua lugha na mtindo.", "Ipe ishara sauti yako", "Ongeza ufunguo wako wa AI, chagua fursa yenye chanzo, na hariri rasimu.", "Idhinisha. Chapisha. Jifunze.", "Kagua maandishi ya mwisho kabla ya kuchapisha. Fuatilia machapisho yaliyothibitishwa na vipimo vinavyotolewa na 𝕏.", "Endesha hapa na kagua chanzo", "Angalia jinsi chumba cha udhibiti kinavyofanya kazi.", "Chunguza vyanzo, rasimu na stakabadhi kwenye onyesho lisilohitaji vitambulisho. Mwanzo wa kuunganisha akaunti na ruhusa ya kuchapisha unaonekana wazi.", "Hati na onyesho", "Ispatla · dawati la utafiti na uchapishaji wa 𝕏", "Uaminifu na taarifa za bidhaa", "Usalama", "Faragha", "Masharti", ""],
  },
  mr: {
    partial: "या उत्पादनातील काही विभागांचे भाषांतर अजून सुरू आहे.",
    nav: ["उत्पादन परिचय", "साइन इन", "सुरू करा", "कार्यस्थळ", "डॅशबोर्ड", "संधी", "मसुदा स्टुडिओ", "प्रकाशन रांग", "कामकाज", "खाती", "स्रोत", "श्रेणी", "विश्लेषण", "निर्णय पुनरावलोकन", "सेटिंग्ज", "की व्यवस्थापन", "स्वयंचलन", "लेखनशैली", "शेअर प्रोफाइल", "खाते सुरक्षा", "साइन आउट", "साइन आउट होत आहे…", "साइन आउट झाले नाही. पुन्हा प्रयत्न करा.", "संशोधन आणि प्रकाशन डेस्क", "भाषा", "मेनू उघडा", "भाषा आणि स्वरूप", "पडताळलेल्या यशस्वी पोस्ट"],
    landing: ["Ispatla — स्वतःची AI की जोडा, स्रोत असलेली संधी निवडा आणि मसुदा संपादित करा.", "खऱ्या 𝕏 संकेतांपासून तुमच्या आवाजात मसुदे बनवा. संधी निवडा, पोस्ट मंजूर करा आणि निकालाचे पुरावे पाहा.", "मुख्य मेनू", "Ispatla", "Social AI HitMaker", "अल्गोरिदमला विनवणे थांबवा.", "पुढच्या पावलाला अर्थ द्या.", "खऱ्या 𝕏 संकेतांपासून तुमच्या आवाजात मसुदे बनवा. संधी निवडा, पोस्ट मंजूर करा आणि निकालाचे पुरावे पाहा.", "खाते तयार करा", "स्रोत कोड", "नमुना कार्यप्रवाह · उत्पादन परिचय", "स्रोत → निर्णय → प्रकाशन", "पुरावा दिसतो", "स्रोत पोस्ट", "मूळ दुवा आणि स्रोत जतन", "संधी", "सुसंगतता आणि पुरावा तपासा", "मसुदा", "तुमच्या खात्याच्या शैलीतील संपादनयोग्य मजकूर", "प्रकाशनाचा परिणाम", "स्थानिक स्थिती आणि 𝕏 पुरावे वेगळे राहतात", "तुमचे 𝕏 जोडा", "प्रोफाइल आणि पोस्टमधून ओळखलेले विषय तपासा. भाषा आणि लेखनशैली निवडा.", "संकेताला तुमचा आवाज द्या", "स्वतःची AI की जोडा, स्रोत असलेली संधी निवडा आणि मसुदा संपादित करा.", "मंजूर करा. प्रकाशित करा. शिका.", "प्रकाशनापूर्वी अंतिम मजकूर तपासा. खात्रीशीर प्रकाशने आणि 𝕏 ने दिलेली मोजमापे पाहा.", "स्थानिकपणे चालवा आणि स्रोत तपासा", "नियंत्रण कक्ष कसा काम करतो ते पाहा.", "ओळखपत्रांशिवाय चालणाऱ्या डेमोमध्ये स्रोत, मसुदे आणि पावत्या पाहा. खाते जोडणे आणि प्रकाशन परवानगी कुठे सुरू होते ते स्पष्ट दिसते.", "दस्तऐवज आणि डेमो", "Ispatla · 𝕏 संशोधन आणि प्रकाशन डेस्क", "विश्वास आणि उत्पादन माहिती", "सुरक्षा", "गोपनीयता", "अटी", ""],
  },
  te: {
    partial: "ఈ ఉత్పత్తిలోని కొన్ని భాగాల అనువాదం ఇంకా కొనసాగుతోంది.",
    nav: ["ఉత్పత్తి పరిచయం", "సైన్ ఇన్", "ప్రారంభించండి", "పని ప్రదేశం", "డ్యాష్‌బోర్డ్", "అవకాశాలు", "డ్రాఫ్ట్ స్టూడియో", "ప్రచురణ క్యూ", "కార్యకలాపాలు", "ఖాతాలు", "మూలాలు", "వర్గాలు", "విశ్లేషణలు", "నిర్ణయ సమీక్ష", "సెట్టింగ్‌లు", "కీ నిర్వహణ", "ఆటోమేషన్", "రచనా శైలి", "షేరింగ్ ప్రొఫైల్", "ఖాతా భద్రత", "సైన్ అవుట్", "సైన్ అవుట్ అవుతోంది…", "సైన్ అవుట్ కాలేదు. మళ్లీ ప్రయత్నించండి.", "పరిశోధన మరియు ప్రచురణ డెస్క్", "భాష", "మెనూ తెరవండి", "భాష మరియు రూపం", "ధృవీకరించిన విజయాలు"],
    landing: ["Ispatla — మీ AI కీ జోడించి, మూలం ఉన్న అవకాశం ఎంచుకుని డ్రాఫ్ట్ సవరించండి.", "నిజమైన 𝕏 సంకేతాలను మీ స్వరంలో డ్రాఫ్ట్‌లుగా మార్చండి. అవకాశం ఎంచుకోండి, పోస్ట్ ఆమోదించండి, ఫలితానికి ఆధారాలు చూడండి.", "ప్రధాన మెనూ", "Ispatla", "Social AI HitMaker", "అల్గోరిథమ్‌ను వేడుకోవడం ఆపండి.", "మీ తదుపరి అడుగుకు అర్థం ఇవ్వండి.", "నిజమైన 𝕏 సంకేతాలను మీ స్వరంలో డ్రాఫ్ట్‌లుగా మార్చండి. అవకాశం ఎంచుకోండి, పోస్ట్ ఆమోదించండి, ఫలితానికి ఆధారాలు చూడండి.", "ఖాతా సృష్టించండి", "సోర్స్ కోడ్", "నమూనా పని విధానం · ఉత్పత్తి పరిచయం", "మూలం → నిర్ణయం → ప్రచురణ", "ఆధారం కనిపిస్తుంది", "మూల పోస్ట్", "అసలు లింక్ మరియు మూలం భద్రం", "అవకాశం", "సంబంధితత మరియు ఆధారాలను పరిశీలించండి", "డ్రాఫ్ట్", "మీ ఖాతా స్వరంలో సవరించగల వచనం", "ప్రచురణ ఫలితం", "స్థానిక స్థితి మరియు 𝕏 ఆధారాలు వేరుగా ఉంటాయి", "మీ 𝕏ను కనెక్ట్ చేయండి", "ప్రొఫైల్, పోస్టుల నుంచి గుర్తించిన అంశాలను చూడండి. భాష, రచనా శైలి ఎంచుకోండి.", "సంకేతానికి మీ స్వరం ఇవ్వండి", "మీ AI కీ జోడించి, మూలం ఉన్న అవకాశం ఎంచుకుని డ్రాఫ్ట్ సవరించండి.", "ఆమోదించండి. ప్రచురించండి. నేర్చుకోండి.", "ప్రచురణకు ముందు తుది వచనాన్ని చూడండి. ధృవీకరించిన ప్రచురణలు, 𝕏 అందించే గణాంకాలు అనుసరించండి.", "స్థానికంగా నడిపి మూలాన్ని పరిశీలించండి", "కంట్రోల్ రూమ్ ఎలా పనిచేస్తుందో చూడండి.", "ఆధారాలు అవసరం లేని డెమోలో మూలాలు, డ్రాఫ్ట్‌లు, రసీదులను చూడండి. ఖాతా అనుసంధానం మరియు ప్రచురణ అనుమతి ఎక్కడ మొదలవుతాయో స్పష్టంగా ఉంటుంది.", "డాక్యుమెంటేషన్ మరియు డెమో", "Ispatla · 𝕏 పరిశోధన మరియు ప్రచురణ డెస్క్", "నమ్మకం మరియు ఉత్పత్తి సమాచారం", "భద్రత", "గోప్యత", "నిబంధనలు", ""],
  },
  tr: {
    partial: "Ürünün bazı bölümlerinin çevirisi sürüyor.",
    nav: ["Ürün turu", "Giriş yap", "Başla", "Çalışma alanı", "Kontrol paneli", "Fırsatlar", "Taslak stüdyosu", "Yayın kuyruğu", "Operasyonlar", "Hesaplar", "Kaynaklar", "Kategoriler", "Analitik", "Karar incelemesi", "Ayarlar", "Anahtar yönetimi", "Otomasyon", "Yazım tarzı", "Paylaşım profili", "Hesap güvenliği", "Çıkış yap", "Çıkış yapılıyor…", "Çıkış yapılamadı. Yeniden dene.", "Araştırma ve yayın masası", "Dil", "Menüyü aç", "Dil ve görünüm", "Doğrulanmış hitler"],
    landing: ["Ispatla — Kendi AI anahtarını ekle, kaynağı belli bir fırsat seç ve taslağı şekillendir.", "Gerçek 𝕏 sinyallerini kendi sesinde taslaklara çevir. Fırsatı sen seç, yayını sen onayla. Sonucun arkasındaki kanıtı gör.", "Ana menü", "İspatla", "Social AI HitMaker", "Algoritmaya yalvarma.", "Kendi oyununu kur.", "Gerçek 𝕏 sinyallerini kendi sesinde taslaklara çevir. Fırsatı sen seç, yayını sen onayla. Sonucun arkasındaki kanıtı gör.", "Hesap oluştur", "Kaynak kodu", "Örnek akış · ürün turu", "Kaynak → karar → yayın", "kanıt görünür", "Kaynak gönderi", "özgün bağlantı ve kaynak korunur", "Fırsat", "uygunluk ve kanıtı incele", "Taslak", "hesabının üslubunda düzenlenebilir metin", "Yayın sonucu", "yerel durum ve 𝕏 kanıtı ayrı tutulur", "𝕏 hesabını bağla", "Profilinden ve gönderilerinden bulunan konuları gözden geçir. Dilini ve yazım tarzını seç.", "Sinyale kendi sesini kat", "Kendi AI anahtarını ekle, kaynağı belli bir fırsat seç ve taslağı şekillendir.", "Onayla. Yayınla. Öğren.", "Yayınlamadan önce son metni incele. Doğrulanan yayınları ve 𝕏’in gerçekten sağladığı metrikleri izle.", "Yerelde çalıştır ve kaynağı incele", "Kontrol masasının nasıl çalıştığını gör.", "Kimlik bilgisi gerektirmeyen demoda kaynakları, taslakları ve makbuzları incele. Hesap bağlantısının ve yayın izninin nerede başladığı açıkça görünür.", "Dokümantasyon ve demo", "İspatla · 𝕏 araştırma ve yayın masası", "Güven ve ürün bilgileri", "Güvenlik", "Gizlilik", "Koşullar", ""],
  },
  ta: {
    partial: "இந்தத் தயாரிப்பின் சில பகுதிகள் இன்னும் மொழிபெயர்க்கப்பட்டு வருகின்றன.",
    nav: ["தயாரிப்பு அறிமுகம்", "உள்நுழை", "தொடங்கு", "பணியிடம்", "முகப்புப் பலகை", "வாய்ப்புகள்", "வரைவு அரங்கு", "வெளியீட்டு வரிசை", "செயல்பாடுகள்", "கணக்குகள்", "மூலங்கள்", "வகைகள்", "பகுப்பாய்வு", "முடிவு மதிப்பாய்வு", "அமைப்புகள்", "விசை நிர்வாகம்", "தானியக்கம்", "எழுத்து நடை", "பகிர்வு சுயவிவரம்", "கணக்கு பாதுகாப்பு", "வெளியேறு", "வெளியேறுகிறது…", "வெளியேற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.", "ஆய்வு மற்றும் வெளியீட்டு மேசை", "மொழி", "பட்டியலைத் திற", "மொழி மற்றும் தோற்றம்", "சரிபார்க்கப்பட்ட வெற்றிகள்"],
    landing: ["Ispatla — உங்கள் AI விசையைச் சேர்த்து, மூலம் உள்ள வாய்ப்பைத் தேர்ந்து வரைவைத்திருத்தவும்.", "உண்மையான 𝕏 சைகைகளை உங்கள் குரலில் வரைவுகளாக்குங்கள். வாய்ப்பைத் தேர்ந்து, பதிவை ஒப்புதல் அளித்து, முடிவின் ஆதாரத்தைப் பாருங்கள்.", "முதன்மை பட்டியல்", "Ispatla", "Social AI HitMaker", "அல்கோரிதத்திடம் கெஞ்சுவதை நிறுத்துங்கள்.", "அடுத்த படிக்கு அர்த்தம் கொடுங்கள்.", "உண்மையான 𝕏 சைகைகளை உங்கள் குரலில் வரைவுகளாக்குங்கள். வாய்ப்பைத் தேர்ந்து, பதிவை ஒப்புதல் அளித்து, முடிவின் ஆதாரத்தைப் பாருங்கள்.", "கணக்கை உருவாக்கு", "மூலக் குறியீடு", "மாதிரி நடைமுறை · தயாரிப்பு அறிமுகம்", "மூலம் → முடிவு → வெளியீடு", "ஆதாரம் தெரியும்", "மூலப் பதிவு", "அசல் இணைப்பும் மூலமும் பாதுகாக்கப்படும்", "வாய்ப்பு", "பொருத்தம் மற்றும் ஆதாரத்தைப் பாருங்கள்", "வரைவு", "உங்கள் கணக்கின் குரலில் திருத்தக்கூடிய உரை", "வெளியீட்டு முடிவு", "உள்ளூர் நிலையும் 𝕏 ஆதாரமும் தனித்தனியாக இருக்கும்", "உங்கள் 𝕏ஐ இணைக்கவும்", "சுயவிவரம், பதிவுகளில் கண்ட தலைப்புகளைச் சரிபார்க்கவும். மொழி, எழுத்து நடையைத் தேர்வுசெய்யவும்.", "சைகைக்கு உங்கள் குரலைத் தாருங்கள்", "உங்கள் AI விசையைச் சேர்த்து, மூலம் உள்ள வாய்ப்பைத் தேர்ந்து வரைவைத்திருத்தவும்.", "ஒப்புதல். வெளியீடு. கற்றல்.", "வெளியீட்டுக்கு முன் இறுதி உரையைப் பாருங்கள். உறுதியான வெளியீடுகள் மற்றும் 𝕏 வழங்கும் அளவீடுகளைப் பின்தொடருங்கள்.", "உள்ளூரில் இயக்கி மூலத்தைப் பாருங்கள்", "கட்டுப்பாட்டு அறை எப்படிச் செயல்படுகிறது எனப் பாருங்கள்.", "சான்றுகள் தேவையில்லாத செயல்விளக்கத்தில் மூலங்கள், வரைவுகள், ரசீதுகளைப் பாருங்கள். கணக்கு இணைப்பும் வெளியீட்டு அனுமதியும் தொடங்கும் இடம் தெளிவாகத் தெரியும்.", "ஆவணங்களும் செயல்விளக்கமும்", "Ispatla · 𝕏 ஆய்வு மற்றும் வெளியீட்டு மேசை", "நம்பிக்கை மற்றும் தயாரிப்பு விவரங்கள்", "பாதுகாப்பு", "தனியுரிமை", "விதிமுறைகள்", ""],
  },
  vi: {
    partial: "Một số mục của sản phẩm vẫn đang được dịch.",
    nav: ["Giới thiệu sản phẩm", "Đăng nhập", "Bắt đầu", "Không gian làm việc", "Bảng điều khiển", "Cơ hội", "Studio bản nháp", "Hàng đợi xuất bản", "Vận hành", "Tài khoản", "Nguồn", "Danh mục", "Phân tích", "Đánh giá quyết định", "Cài đặt", "Quản lý khóa", "Tự động hóa", "Phong cách viết", "Hồ sơ chia sẻ", "Bảo mật tài khoản", "Đăng xuất", "Đang đăng xuất…", "Không thể đăng xuất. Hãy thử lại.", "Bàn nghiên cứu và xuất bản", "Ngôn ngữ", "Mở menu", "Ngôn ngữ và giao diện", "Thành công đã xác minh"],
    landing: ["Ispatla — Thêm khóa AI riêng, chọn cơ hội có nguồn và chỉnh sửa bản nháp.", "Biến tín hiệu thật từ 𝕏 thành bản nháp mang giọng của bạn. Chọn cơ hội, duyệt bài đăng và xem bằng chứng của kết quả.", "Menu chính", "Ispatla", "Social AI HitMaker", "Đừng cầu xin thuật toán nữa.", "Để bước tiếp theo có ý nghĩa.", "Biến tín hiệu thật từ 𝕏 thành bản nháp mang giọng của bạn. Chọn cơ hội, duyệt bài đăng và xem bằng chứng của kết quả.", "Tạo tài khoản", "Mã nguồn", "Quy trình mẫu · giới thiệu sản phẩm", "Nguồn → quyết định → xuất bản", "bằng chứng hiển thị", "Bài đăng nguồn", "giữ lại liên kết và nguồn ban đầu", "Cơ hội", "xem xét mức liên quan và bằng chứng", "Bản nháp", "văn bản có thể chỉnh sửa theo giọng điệu tài khoản", "Kết quả xuất bản", "trạng thái cục bộ và bằng chứng 𝕏 được tách riêng", "Kết nối 𝕏 của bạn", "Xem chủ đề nhận diện từ hồ sơ và bài đăng. Chọn ngôn ngữ và phong cách.", "Đưa tiếng nói vào tín hiệu", "Thêm khóa AI riêng, chọn cơ hội có nguồn và chỉnh sửa bản nháp.", "Duyệt. Đăng. Học hỏi.", "Xem nội dung cuối trước khi đăng. Theo dõi bài đăng xác nhận và số liệu 𝕏 cung cấp.", "Chạy cục bộ và kiểm tra nguồn", "Tìm hiểu cách phòng điều khiển hoạt động.", "Khám phá nguồn, bản nháp và biên nhận trong bản demo không cần thông tin xác thực. Điểm bắt đầu kết nối tài khoản và cấp quyền đăng bài luôn được hiển thị.", "Tài liệu và bản demo", "Ispatla · nghiên cứu và xuất bản trên 𝕏", "Niềm tin và thông tin sản phẩm", "Bảo mật", "Quyền riêng tư", "Điều khoản", ""],
  },
  ko: {
    partial: "제품의 일부 영역은 아직 번역 중입니다.",
    nav: ["제품 둘러보기", "로그인", "시작하기", "작업 공간", "대시보드", "기회", "초안 작업실", "게시 대기열", "운영", "계정", "소스", "카테고리", "분석", "의사결정 검토", "설정", "키 관리", "자동화", "글쓰기 스타일", "공유 프로필", "계정 보안", "로그아웃", "로그아웃 중…", "로그아웃할 수 없습니다. 다시 시도하세요.", "리서치 및 게시 데스크", "언어", "메뉴 열기", "언어 및 화면 설정", "검증된 성과"],
    landing: ["Ispatla — 내 AI 키를 추가하고 출처가 있는 기회를 골라 초안을 편집하세요.", "실제 𝕏 신호를 내 목소리의 초안으로 만드세요. 기회를 고르고, 게시를 승인하고, 결과의 근거를 확인하세요.", "주 메뉴", "Ispatla", "Social AI HitMaker", "알고리즘에 매달리지 마세요.", "다음 행동에 근거를 더하세요.", "실제 𝕏 신호를 내 목소리의 초안으로 만드세요. 기회를 고르고, 게시를 승인하고, 결과의 근거를 확인하세요.", "계정 만들기", "소스 코드", "예시 흐름 · 제품 둘러보기", "소스 → 판단 → 게시", "근거 표시", "소스 게시물", "원본 링크와 출처 보존", "기회", "관련성과 근거 검토", "초안", "계정의 말투에 맞춘 편집 가능한 글", "게시 결과", "로컬 상태와 𝕏 근거는 구분됩니다", "내 𝕏 연결하기", "프로필과 게시물에서 찾은 주제를 검토하세요. 언어와 문체를 고르세요.", "신호에 내 목소리 담기", "내 AI 키를 추가하고 출처가 있는 기회를 골라 초안을 편집하세요.", "승인. 게시. 학습.", "게시 전에 최종 문안을 확인하세요. 확정된 게시와 𝕏가 제공하는 지표를 살펴보세요.", "로컬에서 실행하고 소스 확인", "컨트롤 룸이 어떻게 작동하는지 살펴보세요.", "인증 정보가 필요 없는 데모에서 소스, 초안, 영수증을 확인하세요. 계정 연결과 게시 권한이 시작되는 지점도 표시됩니다.", "문서 및 데모", "Ispatla · 𝕏 리서치 및 게시 데스크", "신뢰 및 제품 정보", "보안", "개인정보", "약관", ""],
  },
};

const onboardingCopy: Record<Locale, readonly string[]> = {
  en: ["Profile", "Edit your sharing profile", "𝕏 account", "Connect your account to scan sources automatically", "AI provider", "Optionally connect your own provider", "Appearance", "Choose your language, theme, and accent color", "Go to workspace", "First steps", "Set up your workspace", "Save your sharing profile first. Other connections are optional, and you can return to setup later.", "Setup steps", "Set up your sharing profile", "Review details imported from 𝕏 and choose profile visibility.", "Edit your profile details and choose who can see it.", "𝕏 profile photo", "Add a display name", "Display name", "Bio", "Profile visibility", "Public", "Your display name, bio, photo, and 𝕏 account will be visible to everyone.", "Private", "Your sharing profile will not be shown publicly.", "Could not save profile.", "The profile response did not confirm setup completion. Try again.", "Saving…", "Save profile", "Save and continue", "Connect your 𝕏 account", "When connected, we scan your sources and create starter categories automatically. You can change permissions later in settings.", "Connected 𝕏 account found.", "No 𝕏 account connected yet.", "Back", "Manage accounts", "Continue", "AI provider", "Connect your own OpenAI, Claude, or compatible provider key, or skip this step for now.", "An AI provider is active.", "No verified provider is configured yet.", "Manage providers", "Open workspace"],
  "zh-CN": ["个人资料", "编辑分享资料", "𝕏 账号", "连接账号后自动扫描来源", "AI 服务商", "可选连接自己的服务商", "外观", "选择语言、主题和强调色", "进入工作区", "开始设置", "设置你的工作区", "请先保存分享资料。其他连接均为可选项，你也可以稍后继续设置。", "设置步骤", "设置分享资料", "查看从 𝕏 导入的信息并选择资料可见范围。", "编辑资料并选择谁可以查看。", "𝕏 头像", "添加显示名称", "显示名称", "简介", "资料可见范围", "公开", "所有人都可以看到你的显示名称、简介、头像和 𝕏 账号。", "私密", "你的分享资料不会公开显示。", "无法保存资料。", "资料响应未确认设置已完成，请重试。", "正在保存…", "保存资料", "保存并继续", "连接 𝕏 账号", "连接后，我们会扫描你的来源并自动创建初始类别。你可以稍后在设置中更改权限。", "已找到已连接的 𝕏 账号。", "尚未连接 𝕏 账号。", "返回", "管理账号", "继续", "AI 服务商", "你可以连接自己的 OpenAI、Claude 或兼容服务商密钥，也可以暂时跳过此步骤。", "AI 服务商已启用。", "尚未配置经过验证的服务商。", "管理服务商", "进入工作区"],
  hi: ["प्रोफ़ाइल", "साझा प्रोफ़ाइल संपादित करें", "𝕏 खाता", "स्रोतों को अपने आप स्कैन करने के लिए खाता जोड़ें", "AI प्रदाता", "वैकल्पिक रूप से अपना प्रदाता जोड़ें", "दिखावट", "भाषा, थीम और रंग चुनें", "कार्यस्थल पर जाएँ", "पहले कदम", "अपना कार्यस्थल सेट करें", "पहले साझा प्रोफ़ाइल सहेजें। अन्य कनेक्शन वैकल्पिक हैं और आप बाद में सेटअप पर लौट सकते हैं।", "सेटअप चरण", "साझा प्रोफ़ाइल सेट करें", "𝕏 से आयात की गई जानकारी देखें और प्रोफ़ाइल की दृश्यता चुनें।", "प्रोफ़ाइल विवरण बदलें और चुनें कि इसे कौन देख सकता है।", "𝕏 प्रोफ़ाइल फ़ोटो", "दिखने वाला नाम जोड़ें", "दिखने वाला नाम", "बायो", "प्रोफ़ाइल दृश्यता", "सार्वजनिक", "आपका नाम, बायो, फ़ोटो और 𝕏 खाता सभी को दिखाई देंगे।", "निजी", "आपकी साझा प्रोफ़ाइल सार्वजनिक रूप से नहीं दिखाई जाएगी।", "प्रोफ़ाइल सहेजी नहीं जा सकी।", "प्रोफ़ाइल जवाब ने सेटअप पूरा होने की पुष्टि नहीं की। फिर कोशिश करें।", "सहेजा जा रहा है…", "प्रोफ़ाइल सहेजें", "सहेजें और आगे बढ़ें", "अपना 𝕏 खाता जोड़ें", "जुड़ने पर हम आपके स्रोत स्कैन करके शुरुआती श्रेणियाँ अपने आप बनाएँगे। अनुमतियाँ बाद में सेटिंग में बदलें।", "जुड़ा हुआ 𝕏 खाता मिला।", "अभी कोई 𝕏 खाता नहीं जुड़ा है।", "वापस", "खाते प्रबंधित करें", "आगे बढ़ें", "AI प्रदाता", "अपनी OpenAI, Claude या संगत प्रदाता कुंजी जोड़ें, या अभी इस चरण को छोड़ दें।", "AI प्रदाता सक्रिय है।", "अभी किसी सत्यापित प्रदाता का कॉन्फ़िगरेशन नहीं है।", "प्रदाता प्रबंधित करें", "कार्यस्थल खोलें"],
  es: ["Perfil", "Edita tu perfil para compartir", "Cuenta de 𝕏", "Conecta tu cuenta para analizar fuentes automáticamente", "Proveedor de IA", "Puedes conectar tu propio proveedor si quieres", "Apariencia", "Elige idioma, tema y color de acento", "Ir al espacio de trabajo", "Primeros pasos", "Configura tu espacio de trabajo", "Guarda primero tu perfil para compartir. Las demás conexiones son opcionales; puedes volver más tarde.", "Pasos de configuración", "Configura tu perfil para compartir", "Revisa la información importada de 𝕏 y elige la visibilidad del perfil.", "Edita tu perfil y decide quién puede verlo.", "Foto de perfil de 𝕏", "Añadir nombre visible", "Nombre visible", "Biografía", "Visibilidad del perfil", "Público", "Tu nombre, biografía, foto y cuenta de 𝕏 serán visibles para todos.", "Privado", "Tu perfil para compartir no se mostrará públicamente.", "No se pudo guardar el perfil.", "La respuesta no confirmó que la configuración haya terminado. Inténtalo de nuevo.", "Guardando…", "Guardar perfil", "Guardar y continuar", "Conecta tu cuenta de 𝕏", "Al conectarla, analizaremos tus fuentes y crearemos categorías iniciales automáticamente. Puedes cambiar los permisos en ajustes.", "Se encontró una cuenta de 𝕏 conectada.", "Aún no hay ninguna cuenta de 𝕏 conectada.", "Atrás", "Gestionar cuentas", "Continuar", "Proveedor de IA", "Conecta tu propia clave de OpenAI, Claude o un proveedor compatible, o salta este paso por ahora.", "Hay un proveedor de IA activo.", "Aún no hay ningún proveedor verificado configurado.", "Gestionar proveedores", "Abrir espacio de trabajo"],
  fr: ["Profil", "Modifier le profil de partage", "Compte 𝕏", "Connectez votre compte pour analyser automatiquement les sources", "Fournisseur d’IA", "Vous pouvez connecter votre propre fournisseur", "Apparence", "Choisissez la langue, le thème et la couleur", "Ouvrir l’espace de travail", "Premiers pas", "Configurez votre espace de travail", "Enregistrez d’abord le profil de partage. Les autres connexions sont facultatives ; vous pourrez revenir ici plus tard.", "Étapes de configuration", "Configurer le profil de partage", "Vérifiez les informations importées de 𝕏 et choisissez la visibilité du profil.", "Modifiez le profil et choisissez qui peut le voir.", "Photo de profil 𝕏", "Ajouter un nom affiché", "Nom affiché", "Bio", "Visibilité du profil", "Public", "Votre nom, votre bio, votre photo et votre compte 𝕏 seront visibles par tous.", "Privé", "Votre profil de partage ne sera pas affiché publiquement.", "Impossible d’enregistrer le profil.", "La réponse ne confirme pas la fin de la configuration. Réessayez.", "Enregistrement…", "Enregistrer le profil", "Enregistrer et continuer", "Connecter votre compte 𝕏", "Une fois connecté, nous analyserons vos sources et créerons automatiquement des catégories initiales. Vous pourrez modifier les autorisations dans les paramètres.", "Compte 𝕏 connecté détecté.", "Aucun compte 𝕏 n’est encore connecté.", "Retour", "Gérer les comptes", "Continuer", "Fournisseur d’IA", "Connectez votre clé OpenAI, Claude ou compatible, ou ignorez cette étape pour le moment.", "Un fournisseur d’IA est actif.", "Aucun fournisseur vérifié n’est configuré.", "Gérer les fournisseurs", "Ouvrir l’espace de travail"],
  ar: ["الملف الشخصي", "تعديل الملف العام", "حساب 𝕏", "اربط حسابك لفحص المصادر تلقائياً", "مزود الذكاء الاصطناعي", "يمكنك ربط مزودك اختيارياً", "المظهر", "اختر اللغة والسمة واللون", "فتح مساحة العمل", "الخطوات الأولى", "إعداد مساحة العمل", "احفظ ملفك العام أولاً. الاتصالات الأخرى اختيارية ويمكنك العودة إلى الإعداد لاحقاً.", "خطوات الإعداد", "إعداد الملف العام", "راجع المعلومات المستوردة من 𝕏 واختر مستوى ظهور الملف.", "عدّل ملفك واختر من يمكنه رؤيته.", "صورة ملف 𝕏", "أضف اسماً ظاهراً", "الاسم الظاهر", "النبذة", "ظهور الملف الشخصي", "عام", "سيظهر اسمك ونبذتك وصورتك وحساب 𝕏 للجميع.", "خاص", "لن يظهر ملفك العام للآخرين.", "تعذر حفظ الملف.", "لم يؤكد الرد اكتمال الإعداد. حاول مجدداً.", "جارٍ الحفظ…", "حفظ الملف", "حفظ ومتابعة", "اربط حساب 𝕏", "بعد الربط سنفحص مصادرك وننشئ فئات أولية تلقائياً. يمكنك تغيير الأذونات لاحقاً من الإعدادات.", "تم العثور على حساب 𝕏 مرتبط.", "لا يوجد حساب 𝕏 مرتبط بعد.", "رجوع", "إدارة الحسابات", "متابعة", "مزود الذكاء الاصطناعي", "اربط مفتاحك الخاص من OpenAI أو Claude أو مزود متوافق، أو تخطَّ هذه الخطوة الآن.", "يوجد مزود ذكاء اصطناعي نشط.", "لم يتم إعداد مزود تم التحقق منه بعد.", "إدارة المزودين", "فتح مساحة العمل"],
  bn: ["প্রোফাইল", "শেয়ার প্রোফাইল সম্পাদনা করুন", "𝕏 অ্যাকাউন্ট", "উৎস স্বয়ংক্রিয়ভাবে স্ক্যান করতে অ্যাকাউন্ট যুক্ত করুন", "AI প্রদানকারী", "ইচ্ছা হলে নিজের প্রদানকারী যুক্ত করুন", "চেহারা", "ভাষা, থিম ও রঙ বেছে নিন", "কর্মক্ষেত্রে যান", "প্রথম ধাপ", "আপনার কর্মক্ষেত্র সাজান", "আগে শেয়ার প্রোফাইল সংরক্ষণ করুন। অন্য সংযোগগুলো ঐচ্ছিক; পরে আবার সেটআপে ফিরতে পারবেন।", "সেটআপের ধাপ", "শেয়ার প্রোফাইল সাজান", "𝕏 থেকে আনা তথ্য পর্যালোচনা করুন এবং প্রোফাইলের দৃশ্যমানতা বেছে নিন।", "প্রোফাইলের তথ্য সম্পাদনা করুন এবং কে দেখতে পারবে তা বেছে নিন।", "𝕏 প্রোফাইলের ছবি", "প্রদর্শিত নাম যোগ করুন", "প্রদর্শিত নাম", "পরিচিতি", "প্রোফাইলের দৃশ্যমানতা", "সর্বজনীন", "আপনার নাম, পরিচিতি, ছবি ও 𝕏 অ্যাকাউন্ট সবাই দেখতে পাবে।", "ব্যক্তিগত", "আপনার শেয়ার প্রোফাইল সর্বজনীনভাবে দেখানো হবে না।", "প্রোফাইল সংরক্ষণ করা যায়নি।", "সেটআপ সম্পূর্ণ হয়েছে বলে প্রোফাইলের উত্তরে নিশ্চিত করা যায়নি। আবার চেষ্টা করুন।", "সংরক্ষণ হচ্ছে…", "প্রোফাইল সংরক্ষণ", "সংরক্ষণ করে এগিয়ে যান", "আপনার 𝕏 অ্যাকাউন্ট যুক্ত করুন", "সংযুক্ত হলে আমরা আপনার উৎস স্ক্যান করে প্রাথমিক বিভাগ তৈরি করব। পরে সেটিংস থেকে অনুমতি বদলাতে পারবেন।", "সংযুক্ত 𝕏 অ্যাকাউন্ট পাওয়া গেছে।", "এখনও কোনো 𝕏 অ্যাকাউন্ট সংযুক্ত নেই।", "পেছনে", "অ্যাকাউন্ট পরিচালনা", "এগিয়ে যান", "AI প্রদানকারী", "নিজের OpenAI, Claude বা সামঞ্জস্যপূর্ণ প্রদানকারীর কী যুক্ত করুন, অথবা আপাতত এই ধাপটি এড়িয়ে যান।", "একটি AI প্রদানকারী সক্রিয় আছে।", "এখনও যাচাইকৃত কোনো প্রদানকারী সেট করা হয়নি।", "প্রদানকারী পরিচালনা", "কর্মক্ষেত্র খুলুন"],
  "pt-BR": ["Perfil", "Edite seu perfil público", "Conta do 𝕏", "Conecte sua conta para verificar fontes automaticamente", "Provedor de IA", "Se quiser, conecte seu próprio provedor", "Aparência", "Escolha idioma, tema e cor de destaque", "Abrir espaço de trabalho", "Primeiros passos", "Configure seu espaço de trabalho", "Salve primeiro seu perfil público. As outras conexões são opcionais e você pode voltar depois.", "Etapas da configuração", "Configure seu perfil público", "Confira os dados importados do 𝕏 e escolha a visibilidade do perfil.", "Edite seu perfil e escolha quem pode vê-lo.", "Foto do perfil do 𝕏", "Adicionar nome de exibição", "Nome de exibição", "Bio", "Visibilidade do perfil", "Público", "Seu nome, bio, foto e conta do 𝕏 ficarão visíveis para todos.", "Privado", "Seu perfil público não será exibido.", "Não foi possível salvar o perfil.", "A resposta não confirmou que a configuração terminou. Tente novamente.", "Salvando…", "Salvar perfil", "Salvar e continuar", "Conecte sua conta do 𝕏", "Depois de conectar, vamos verificar suas fontes e criar categorias iniciais automaticamente. Você pode alterar as permissões nas configurações.", "Conta do 𝕏 conectada encontrada.", "Ainda não há uma conta do 𝕏 conectada.", "Voltar", "Gerenciar contas", "Continuar", "Provedor de IA", "Conecte sua própria chave OpenAI, Claude ou compatível, ou pule esta etapa por enquanto.", "Há um provedor de IA ativo.", "Nenhum provedor verificado foi configurado ainda.", "Gerenciar provedores", "Abrir espaço de trabalho"],
  ru: ["Профиль", "Изменить публичный профиль", "Аккаунт 𝕏", "Подключите аккаунт для автоматического сканирования источников", "Провайдер ИИ", "При желании подключите своего провайдера", "Внешний вид", "Выберите язык, тему и акцентный цвет", "Перейти в рабочую область", "Первые шаги", "Настройте рабочую область", "Сначала сохраните публичный профиль. Остальные подключения необязательны; к настройке можно вернуться позже.", "Этапы настройки", "Настройте публичный профиль", "Проверьте данные из 𝕏 и выберите видимость профиля.", "Измените данные профиля и выберите, кто сможет его видеть.", "Фото профиля 𝕏", "Добавить отображаемое имя", "Отображаемое имя", "Описание", "Видимость профиля", "Публичный", "Ваше имя, описание, фото и аккаунт 𝕏 будут видны всем.", "Приватный", "Публичный профиль не будет показываться другим.", "Не удалось сохранить профиль.", "Ответ не подтвердил завершение настройки. Попробуйте ещё раз.", "Сохранение…", "Сохранить профиль", "Сохранить и продолжить", "Подключить аккаунт 𝕏", "После подключения мы просканируем источники и автоматически создадим начальные категории. Разрешения можно изменить позже в настройках.", "Найден подключённый аккаунт 𝕏.", "Аккаунт 𝕏 ещё не подключён.", "Назад", "Управление аккаунтами", "Продолжить", "Провайдер ИИ", "Подключите свой ключ OpenAI, Claude или совместимого провайдера либо пока пропустите этот шаг.", "Провайдер ИИ активен.", "Проверенный провайдер ещё не настроен.", "Управление провайдерами", "Открыть рабочую область"],
  id: ["Profil", "Edit profil berbagi", "Akun 𝕏", "Hubungkan akun agar sumber dipindai otomatis", "Penyedia AI", "Hubungkan penyedia sendiri jika mau", "Tampilan", "Pilih bahasa, tema, dan warna aksen", "Buka ruang kerja", "Langkah awal", "Atur ruang kerja", "Simpan profil berbagi terlebih dahulu. Koneksi lain bersifat opsional dan dapat diatur nanti.", "Langkah penyiapan", "Atur profil berbagi", "Periksa informasi dari 𝕏 dan pilih visibilitas profil.", "Edit detail profil dan tentukan siapa yang dapat melihatnya.", "Foto profil 𝕏", "Tambahkan nama tampilan", "Nama tampilan", "Bio", "Visibilitas profil", "Publik", "Nama, bio, foto, dan akun 𝕏 Anda akan terlihat oleh semua orang.", "Pribadi", "Profil berbagi Anda tidak akan ditampilkan secara publik.", "Profil gagal disimpan.", "Respons profil belum mengonfirmasi penyiapan selesai. Coba lagi.", "Menyimpan…", "Simpan profil", "Simpan dan lanjutkan", "Hubungkan akun 𝕏", "Setelah terhubung, sumber Anda akan dipindai dan kategori awal dibuat otomatis. Izin dapat diubah nanti di pengaturan.", "Akun 𝕏 yang terhubung ditemukan.", "Belum ada akun 𝕏 yang terhubung.", "Kembali", "Kelola akun", "Lanjutkan", "Penyedia AI", "Hubungkan kunci OpenAI, Claude, atau penyedia kompatibel milik Anda, atau lewati langkah ini dulu.", "Penyedia AI aktif.", "Belum ada penyedia terverifikasi yang dikonfigurasi.", "Kelola penyedia", "Buka ruang kerja"],
  ur: ["پروفائل", "شیئرنگ پروفائل میں ترمیم کریں", "𝕏 اکاؤنٹ", "ذرائع خودکار طور پر دیکھنے کے لیے اکاؤنٹ جوڑیں", "AI فراہم کنندہ", "چاہیں تو اپنا فراہم کنندہ جوڑیں", "ظاہری شکل", "زبان، تھیم اور نمایاں رنگ منتخب کریں", "ورک اسپیس کھولیں", "پہلے اقدامات", "اپنی ورک اسپیس ترتیب دیں", "پہلے شیئرنگ پروفائل محفوظ کریں۔ دوسرے کنکشن اختیاری ہیں اور آپ بعد میں سیٹ اپ پر واپس آ سکتے ہیں۔", "سیٹ اپ کے مراحل", "شیئرنگ پروفائل ترتیب دیں", "𝕏 سے درآمد شدہ معلومات دیکھیں اور پروفائل کی نمائش منتخب کریں۔", "پروفائل کی تفصیلات بدلیں اور منتخب کریں کہ کون اسے دیکھ سکتا ہے۔", "𝕏 پروفائل تصویر", "ظاہری نام شامل کریں", "ظاہری نام", "تعارف", "پروفائل کی نمائش", "عوامی", "آپ کا نام، تعارف، تصویر اور 𝕏 اکاؤنٹ سب کو نظر آئے گا۔", "نجی", "آپ کا شیئرنگ پروفائل عوامی طور پر نہیں دکھایا جائے گا۔", "پروفائل محفوظ نہیں ہو سکا۔", "جواب نے سیٹ اپ مکمل ہونے کی تصدیق نہیں کی۔ دوبارہ کوشش کریں۔", "محفوظ ہو رہا ہے…", "پروفائل محفوظ کریں", "محفوظ کرکے جاری رکھیں", "اپنا 𝕏 اکاؤنٹ جوڑیں", "جڑنے کے بعد ہم آپ کے ذرائع دیکھ کر ابتدائی زمرے خود بنائیں گے۔ اجازتیں بعد میں ترتیبات میں بدل سکتے ہیں۔", "منسلک 𝕏 اکاؤنٹ مل گیا۔", "ابھی کوئی 𝕏 اکاؤنٹ منسلک نہیں۔", "واپس", "اکاؤنٹس سنبھالیں", "جاری رکھیں", "AI فراہم کنندہ", "اپنی OpenAI، Claude یا مطابقت رکھنے والے فراہم کنندہ کی کلید جوڑیں، یا فی الحال یہ مرحلہ چھوڑ دیں۔", "AI فراہم کنندہ فعال ہے۔", "ابھی کوئی تصدیق شدہ فراہم کنندہ ترتیب نہیں دیا گیا۔", "فراہم کنندگان سنبھالیں", "ورک اسپیس کھولیں"],
  de: ["Profil", "Öffentliches Profil bearbeiten", "𝕏-Konto", "Verbinde dein Konto, damit Quellen automatisch durchsucht werden", "KI-Anbieter", "Verbinde optional deinen eigenen Anbieter", "Darstellung", "Sprache, Design und Akzentfarbe wählen", "Zum Arbeitsbereich", "Erste Schritte", "Richte deinen Arbeitsbereich ein", "Speichere zuerst dein öffentliches Profil. Weitere Verbindungen sind optional und können später eingerichtet werden.", "Einrichtungsschritte", "Öffentliches Profil einrichten", "Prüfe aus 𝕏 importierte Angaben und wähle die Sichtbarkeit des Profils.", "Bearbeite dein Profil und entscheide, wer es sehen darf.", "𝕏-Profilbild", "Anzeigenamen hinzufügen", "Anzeigename", "Bio", "Profilsichtbarkeit", "Öffentlich", "Dein Name, deine Bio, dein Foto und dein 𝕏-Konto sind für alle sichtbar.", "Privat", "Dein öffentliches Profil wird nicht angezeigt.", "Profil konnte nicht gespeichert werden.", "Die Antwort hat den Abschluss der Einrichtung nicht bestätigt. Bitte erneut versuchen.", "Wird gespeichert…", "Profil speichern", "Speichern und weiter", "𝕏-Konto verbinden", "Nach dem Verbinden durchsuchen wir deine Quellen und erstellen automatisch erste Kategorien. Berechtigungen kannst du später in den Einstellungen ändern.", "Verbundenes 𝕏-Konto gefunden.", "Noch kein 𝕏-Konto verbunden.", "Zurück", "Konten verwalten", "Weiter", "KI-Anbieter", "Verbinde deinen eigenen OpenAI-, Claude- oder kompatiblen Anbieterschlüssel oder überspringe diesen Schritt vorerst.", "Ein KI-Anbieter ist aktiv.", "Noch ist kein geprüfter Anbieter eingerichtet.", "Anbieter verwalten", "Arbeitsbereich öffnen"],
  ja: ["プロフィール", "共有プロフィールを編集", "𝕏 アカウント", "アカウントを接続するとソースを自動で確認します", "AI プロバイダー", "必要なら自分のプロバイダーを接続できます", "外観", "言語、テーマ、アクセントカラーを選択", "ワークスペースへ", "最初のステップ", "ワークスペースを設定", "まず共有プロフィールを保存してください。他の接続は任意で、設定は後から再開できます。", "設定手順", "共有プロフィールを設定", "𝕏 から取り込んだ情報を確認し、プロフィールの公開範囲を選択します。", "プロフィールを編集し、閲覧できる人を選択します。", "𝕏 プロフィール写真", "表示名を追加", "表示名", "自己紹介", "プロフィールの公開範囲", "公開", "名前、自己紹介、写真、𝕏 アカウントが全員に表示されます。", "非公開", "共有プロフィールは公開されません。", "プロフィールを保存できませんでした。", "設定の完了を確認できませんでした。もう一度お試しください。", "保存中…", "プロフィールを保存", "保存して続行", "𝕏 アカウントを接続", "接続するとソースを確認して初期カテゴリーを自動作成します。権限は後から設定で変更できます。", "接続済みの 𝕏 アカウントが見つかりました。", "𝕏 アカウントはまだ接続されていません。", "戻る", "アカウントを管理", "続行", "AI プロバイダー", "OpenAI、Claude、または互換プロバイダーの自分のキーを接続するか、今はこの手順をスキップできます。", "AI プロバイダーが有効です。", "確認済みのプロバイダーはまだ設定されていません。", "プロバイダーを管理", "ワークスペースを開く"],
  sw: ["Wasifu", "Hariri wasifu ya kushiriki", "Akaunti ya 𝕏", "Unganisha akaunti ili kuchanganua vyanzo kiotomatiki", "Mtoa huduma wa AI", "Unaweza kuunganisha mtoa huduma wako", "Mwonekano", "Chagua lugha, mandhari na rangi", "Fungua nafasi ya kazi", "Hatua za kwanza", "Sanidi nafasi yako ya kazi", "Hifadhi kwanza wasifu wa kushiriki. Miunganisho mingine ni hiari na unaweza kurudi baadaye.", "Hatua za usanidi", "Sanidi wasifu wa kushiriki", "Kagua maelezo kutoka 𝕏 na uchague mwonekano wa wasifu.", "Hariri maelezo ya wasifu na uchague anayeweza kuuona.", "Picha ya wasifu ya 𝕏", "Ongeza jina linaloonekana", "Jina linaloonekana", "Wasifu mfupi", "Mwonekano wa wasifu", "Wazi", "Jina, wasifu mfupi, picha na akaunti yako ya 𝕏 vitaonekana kwa kila mtu.", "Faragha", "Wasifu wako wa kushiriki hautaonyeshwa hadharani.", "Wasifu haukuhifadhiwa.", "Jibu halikuthibitisha kuwa usanidi umekamilika. Jaribu tena.", "Inahifadhi…", "Hifadhi wasifu", "Hifadhi na uendelee", "Unganisha akaunti yako ya 𝕏", "Baada ya kuunganisha, tutachanganua vyanzo na kuunda kategoria za mwanzo kiotomatiki. Badilisha ruhusa baadaye kwenye mipangilio.", "Akaunti ya 𝕏 iliyounganishwa imepatikana.", "Bado hakuna akaunti ya 𝕏 iliyounganishwa.", "Rudi", "Dhibiti akaunti", "Endelea", "Mtoa huduma wa AI", "Unganisha ufunguo wako wa OpenAI, Claude au mtoa huduma mwingine anayeendana, au ruka hatua hii sasa.", "Mtoa huduma wa AI anatumika.", "Bado hakuna mtoa huduma aliyethibitishwa.", "Dhibiti watoa huduma", "Fungua nafasi ya kazi"],
  mr: ["प्रोफ़ाइल", "शेअर प्रोफ़ाइल संपादित करा", "𝕏 खाते", "स्रोत आपोआप तपासण्यासाठी खाते जोडा", "AI प्रदाता", "इच्छेनुसार स्वतःचा प्रदाता जोडा", "दिसणे", "भाषा, थीम आणि रंग निवडा", "कार्यस्थळ उघडा", "पहिली पावले", "तुमचे कार्यस्थळ सेट करा", "आधी शेअर प्रोफ़ाइल जतन करा. इतर जोडण्या ऐच्छिक आहेत; तुम्ही नंतर सेटअपवर परत येऊ शकता.", "सेटअपच्या पायऱ्या", "शेअर प्रोफ़ाइल सेट करा", "𝕏 मधून आलेली माहिती तपासा आणि प्रोफ़ाइलची दृश्यमानता निवडा.", "प्रोफ़ाइल तपशील संपादित करा आणि ती कोण पाहू शकते ते निवडा.", "𝕏 प्रोफ़ाइल फोटो", "दिसणारे नाव जोडा", "दिसणारे नाव", "परिचय", "प्रोफ़ाइल दृश्यमानता", "सार्वजनिक", "तुमचे नाव, परिचय, फोटो आणि 𝕏 खाते सर्वांना दिसेल.", "खाजगी", "तुमची शेअर प्रोफ़ाइल सार्वजनिकरीत्या दिसणार नाही.", "प्रोफ़ाइल जतन करता आली नाही.", "सेटअप पूर्ण झाल्याची प्रोफ़ाइल प्रतिसादाने पुष्टी केली नाही. पुन्हा प्रयत्न करा.", "जतन करत आहे…", "प्रोफ़ाइल जतन करा", "जतन करून पुढे जा", "तुमचे 𝕏 खाते जोडा", "जोडल्यानंतर आम्ही स्रोत तपासून सुरुवातीच्या श्रेणी आपोआप तयार करू. परवानग्या नंतर सेटिंगमध्ये बदला.", "जोडलेले 𝕏 खाते सापडले.", "अजून कोणतेही 𝕏 खाते जोडलेले नाही.", "मागे", "खाती व्यवस्थापित करा", "पुढे जा", "AI प्रदाता", "तुमची OpenAI, Claude किंवा सुसंगत प्रदात्याची की जोडा किंवा हा टप्पा आत्ता वगळा.", "AI प्रदाता सक्रिय आहे.", "अद्याप सत्यापित प्रदाता सेट केलेला नाही.", "प्रदाते व्यवस्थापित करा", "कार्यस्थळ उघडा"],
  te: ["ప్రొఫైల్", "భాగస్వామ్య ప్రొఫైల్‌ను సవరించండి", "𝕏 ఖాతా", "మూలాలను స్వయంచాలకంగా స్కాన్ చేయడానికి ఖాతాను కనెక్ట్ చేయండి", "AI ప్రొవైడర్", "కావాలంటే మీ ప్రొవైడర్‌ను కనెక్ట్ చేయండి", "రూపం", "భాష, థీమ్, రంగును ఎంచుకోండి", "పని ప్రదేశాన్ని తెరవండి", "మొదటి అడుగులు", "మీ పని ప్రదేశాన్ని సెటప్ చేయండి", "ముందుగా భాగస్వామ్య ప్రొఫైల్‌ను సేవ్ చేయండి. మిగతా కనెక్షన్‌లు ఐచ్ఛికం; తర్వాత మళ్లీ సెటప్‌కు రావచ్చు.", "సెటప్ దశలు", "భాగస్వామ్య ప్రొఫైల్‌ను సెటప్ చేయండి", "𝕏 నుంచి దిగుమతి చేసిన వివరాలను పరిశీలించి ప్రొఫైల్ కనిపించే విధానాన్ని ఎంచుకోండి.", "ప్రొఫైల్ వివరాలను మార్చి ఎవరు చూడగలరో ఎంచుకోండి.", "𝕏 ప్రొఫైల్ ఫోటో", "ప్రదర్శన పేరును జోడించండి", "ప్రదర్శన పేరు", "బయో", "ప్రొఫైల్ కనిపించే విధానం", "పబ్లిక్", "మీ పేరు, బయో, ఫోటో, 𝕏 ఖాతా అందరికీ కనిపిస్తాయి.", "ప్రైవేట్", "మీ భాగస్వామ్య ప్రొఫైల్ పబ్లిక్‌గా చూపబడదు.", "ప్రొఫైల్‌ను సేవ్ చేయలేకపోయాం.", "సెటప్ పూర్తయిందని ప్రొఫైల్ స్పందన నిర్ధారించలేదు. మళ్లీ ప్రయత్నించండి.", "సేవ్ అవుతోంది…", "ప్రొఫైల్‌ను సేవ్ చేయండి", "సేవ్ చేసి కొనసాగండి", "మీ 𝕏 ఖాతాను కనెక్ట్ చేయండి", "కనెక్ట్ చేసిన తర్వాత మూలాలను స్కాన్ చేసి ప్రారంభ వర్గాలను స్వయంచాలకంగా సృష్టిస్తాం. అనుమతులను తర్వాత సెట్టింగ్‌లలో మార్చవచ్చు.", "కనెక్ట్ చేసిన 𝕏 ఖాతా కనుగొనబడింది.", "ఇంకా 𝕏 ఖాతా కనెక్ట్ కాలేదు.", "వెనక్కి", "ఖాతాలను నిర్వహించండి", "కొనసాగండి", "AI ప్రొవైడర్", "మీ OpenAI, Claude లేదా అనుకూల ప్రొవైడర్ కీని కనెక్ట్ చేయండి లేదా ఈ దశను ఇప్పటికి దాటవేయండి.", "AI ప్రొవైడర్ సక్రియంగా ఉంది.", "ధృవీకరించిన ప్రొవైడర్ ఇంకా కాన్ఫిగర్ కాలేదు.", "ప్రొవైడర్లను నిర్వహించండి", "పని ప్రదేశాన్ని తెరవండి"],
  tr: ["Profil", "Paylaşım profilini düzenle", "𝕏 hesabı", "Kaynakların otomatik taranması için hesabını bağla", "Yapay zekâ", "İstersen kendi sağlayıcını bağla", "Görünüm", "Dil, tema ve vurgu rengini seç", "Çalışma alanına geç", "İlk adımlar", "Çalışma alanını kendine göre ayarla", "Önce paylaşım profilini kaydet. Diğer bağlantılar isteğe bağlı; istediğin zaman kuruluma geri dönebilirsin.", "Kurulum adımları", "Paylaşım profilini ayarla", "𝕏 hesabından içe aktarılan bilgileri gözden geçir ve profil görünürlüğünü seç.", "Profil bilgilerini düzenle ve profilinin kimlere açık olacağını seç.", "𝕏 profil fotoğrafı", "Görünen ad ekle", "Görünen ad", "Bio", "Profil görünürlüğü", "Herkese açık", "Görünen adın, bio’n, profil fotoğrafın ve 𝕏 hesabın herkese görünür.", "Gizli", "Paylaşım profilin herkese gösterilmez.", "Profil kaydedilemedi.", "Profil yanıtı kurulumun tamamlandığını doğrulamadı. Tekrar dene.", "Kaydediliyor…", "Profili kaydet", "Kaydet ve devam et", "𝕏 hesabını bağla", "Hesabın bağlandığında kaynaklarını tarayıp başlangıç kategorilerini otomatik oluştururuz. Yetkiyi daha sonra ayarlardan değiştirebilirsin.", "Bağlı 𝕏 hesabı bulundu.", "Henüz bağlı bir 𝕏 hesabı yok.", "Geri", "Hesapları yönet", "Devam", "Yapay zekâ sağlayıcısı", "Kendi OpenAI, Claude veya uyumlu sağlayıcı anahtarını bağlayabilir ya da bu adımı şimdi geçebilirsin.", "Yapay zekâ kullanımı için etkin bir sağlayıcı mevcut.", "Henüz doğrulanmış bir sağlayıcı ayarlanmamış.", "Sağlayıcıları yönet", "Çalışma alanını aç"],
  ta: ["சுயவிவரம்", "பகிர்வு சுயவிவரத்தைத் திருத்து", "𝕏 கணக்கு", "மூலங்களைத் தானாக ஆய்வு செய்ய கணக்கை இணைக்கவும்", "AI வழங்குநர்", "விரும்பினால் உங்கள் வழங்குநரை இணைக்கவும்", "தோற்றம்", "மொழி, தீம், வண்ணத்தைத் தேர்ந்தெடுக்கவும்", "பணியிடத்திற்குச் செல்", "முதல் படிகள்", "உங்கள் பணியிடத்தை அமைக்கவும்", "முதலில் பகிர்வு சுயவிவரத்தைச் சேமிக்கவும். மற்ற இணைப்புகள் விருப்பமானவை; பின்னர் அமைப்புக்குத் திரும்பலாம்.", "அமைப்பு படிகள்", "பகிர்வு சுயவிவரத்தை அமைக்கவும்", "𝕏 இலிருந்து இறக்குமதி செய்த விவரங்களைப் பார்த்து சுயவிவரத் தெரிவுநிலையைத் தேர்ந்தெடுக்கவும்.", "சுயவிவர விவரங்களைத் திருத்தி யார் பார்க்கலாம் எனத் தேர்ந்தெடுக்கவும்.", "𝕏 சுயவிவரப் படம்", "காண்பிக்கப்படும் பெயரைச் சேர்", "காண்பிக்கப்படும் பெயர்", "சுயவிவர விளக்கம்", "சுயவிவரத் தெரிவுநிலை", "பொது", "உங்கள் பெயர், விளக்கம், படம், 𝕏 கணக்கு அனைவருக்கும் தெரியும்.", "தனிப்பட்டது", "உங்கள் பகிர்வு சுயவிவரம் பொதுவில் காட்டப்படாது.", "சுயவிவரத்தைச் சேமிக்க முடியவில்லை.", "அமைப்பு முடிந்ததை பதில் உறுதிப்படுத்தவில்லை. மீண்டும் முயற்சிக்கவும்.", "சேமிக்கிறது…", "சுயவிவரத்தைச் சேமி", "சேமித்து தொடரவும்", "உங்கள் 𝕏 கணக்கை இணைக்கவும்", "இணைத்ததும் மூலங்களை ஆய்வு செய்து தொடக்க வகைகளைத் தானாக உருவாக்குவோம். அனுமதிகளை அமைப்புகளில் பின்னர் மாற்றலாம்.", "இணைக்கப்பட்ட 𝕏 கணக்கு கிடைத்தது.", "இன்னும் 𝕏 கணக்கு இணைக்கப்படவில்லை.", "பின்", "கணக்குகளை நிர்வகி", "தொடர்", "AI வழங்குநர்", "உங்கள் OpenAI, Claude அல்லது இணக்கமான வழங்குநர் விசையை இணைக்கவும்; அல்லது இப்போது இந்தப் படியைத் தவிர்க்கவும்.", "AI வழங்குநர் செயலில் உள்ளது.", "சரிபார்க்கப்பட்ட வழங்குநர் இன்னும் அமைக்கப்படவில்லை.", "வழங்குநர்களை நிர்வகி", "பணியிடத்தைத் திற"],
  vi: ["Hồ sơ", "Chỉnh sửa hồ sơ chia sẻ", "Tài khoản 𝕏", "Kết nối tài khoản để tự động quét nguồn", "Nhà cung cấp AI", "Bạn có thể kết nối nhà cung cấp riêng", "Giao diện", "Chọn ngôn ngữ, chủ đề và màu nhấn", "Mở không gian làm việc", "Bước đầu tiên", "Thiết lập không gian làm việc", "Trước tiên hãy lưu hồ sơ chia sẻ. Các kết nối khác không bắt buộc; bạn có thể quay lại sau.", "Các bước thiết lập", "Thiết lập hồ sơ chia sẻ", "Xem lại thông tin nhập từ 𝕏 và chọn chế độ hiển thị hồ sơ.", "Chỉnh sửa hồ sơ và chọn người có thể xem.", "Ảnh hồ sơ 𝕏", "Thêm tên hiển thị", "Tên hiển thị", "Tiểu sử", "Chế độ hiển thị hồ sơ", "Công khai", "Tên, tiểu sử, ảnh và tài khoản 𝕏 của bạn sẽ hiển thị với mọi người.", "Riêng tư", "Hồ sơ chia sẻ của bạn sẽ không hiển thị công khai.", "Không thể lưu hồ sơ.", "Phản hồi chưa xác nhận thiết lập đã hoàn tất. Hãy thử lại.", "Đang lưu…", "Lưu hồ sơ", "Lưu và tiếp tục", "Kết nối tài khoản 𝕏", "Sau khi kết nối, chúng tôi sẽ quét nguồn và tự động tạo danh mục ban đầu. Bạn có thể đổi quyền trong phần cài đặt sau.", "Đã tìm thấy tài khoản 𝕏 đã kết nối.", "Chưa có tài khoản 𝕏 nào được kết nối.", "Quay lại", "Quản lý tài khoản", "Tiếp tục", "Nhà cung cấp AI", "Kết nối khóa OpenAI, Claude hoặc nhà cung cấp tương thích của bạn, hoặc bỏ qua bước này lúc này.", "Nhà cung cấp AI đang hoạt động.", "Chưa cấu hình nhà cung cấp đã xác minh.", "Quản lý nhà cung cấp", "Mở không gian làm việc"],
  ko: ["프로필", "공유 프로필 편집", "𝕏 계정", "계정을 연결하면 소스를 자동으로 살펴봅니다", "AI 제공업체", "원하면 직접 제공업체를 연결하세요", "화면 설정", "언어, 테마, 강조 색상을 선택하세요", "작업 공간으로 이동", "첫 단계", "작업 공간 설정", "먼저 공유 프로필을 저장하세요. 다른 연결은 선택 사항이며 나중에 다시 설정할 수 있습니다.", "설정 단계", "공유 프로필 설정", "𝕏에서 가져온 정보를 확인하고 프로필 공개 범위를 선택하세요.", "프로필 정보를 편집하고 볼 수 있는 사람을 선택하세요.", "𝕏 프로필 사진", "표시 이름 추가", "표시 이름", "소개", "프로필 공개 범위", "공개", "이름, 소개, 사진, 𝕏 계정이 모두에게 표시됩니다.", "비공개", "공유 프로필은 공개되지 않습니다.", "프로필을 저장하지 못했습니다.", "설정 완료 여부를 확인하지 못했습니다. 다시 시도하세요.", "저장 중…", "프로필 저장", "저장 후 계속", "𝕏 계정 연결", "연결하면 소스를 살펴보고 시작 카테고리를 자동으로 만듭니다. 권한은 나중에 설정에서 변경할 수 있습니다.", "연결된 𝕏 계정을 찾았습니다.", "아직 연결된 𝕏 계정이 없습니다.", "뒤로", "계정 관리", "계속", "AI 제공업체", "OpenAI, Claude 또는 호환 제공업체의 개인 키를 연결하거나 지금은 이 단계를 건너뛰세요.", "AI 제공업체가 활성화되어 있습니다.", "아직 확인된 제공업체가 설정되지 않았습니다.", "제공업체 관리", "작업 공간 열기"],
};

function dictionaryFrom(locale: Locale, copy: LocaleCopy): Dictionary {
  if (copy.nav.length !== navKeys.length || copy.landing.length !== landingKeys.length || onboardingCopy[locale].length !== onboardingKeys.length) {
    throw new Error("locale dictionary does not match the registered key shape");
  }
  return {
    status: { partial: copy.partial },
    onboarding: Object.fromEntries(onboardingKeys.map((key, index) => [key, onboardingCopy[locale][index]])) as Dictionary["onboarding"],
    nav: Object.fromEntries(navKeys.map((key, index) => [key, copy.nav[index]])) as Dictionary["nav"],
    landing: Object.fromEntries(landingKeys.map((key, index) => [key, copy.landing[index]])) as Dictionary["landing"],
  };
}

export const dictionaries: Record<Locale, Dictionary> = Object.fromEntries(
  LOCALES.map((locale) => [locale, dictionaryFrom(locale, copy[locale])]),
) as Record<Locale, Dictionary>;

export function getDictionary(locale: Locale): Dictionary {
  return dictionaries[locale];
}
