import type { Locale } from "./config";

export const measurementPrivacy: Record<Locale, readonly [string, string]> = {
  tr: ["Toplu landing ölçümü", "Landing etkileşimleri günlük toplamlarla ölçülür. IP, kullanıcı kimliği, ham yönlendirme adresi veya parmak izi kaydedilmez; ölçüm isteği cookie göndermez. Yönlendirme yalnız doğrudan/𝕏/GitHub/diğer sınıfına indirgenir. Toplamlar 400 gün saklanır. Kayıt ve ilk saklanan taslağa kadar geçen süre mevcut kayıtlardan toplu hesaplanır; silinen kayıtlar sonucu değiştirir."],
  en: ["Aggregate landing measurement", "Landing interactions are counted as daily totals. No IP, user identifier, raw referrer URL or fingerprint is recorded; measurement requests omit cookies. Referrals become only direct/𝕏/GitHub/other categories. Totals are retained for 400 days. Signup and time to the first retained draft are aggregated from existing records; deletion changes the snapshot."],
  "zh-CN": ["汇总首页统计", "首页互动按每日总数统计，不记录 IP、用户标识、原始来源网址或指纹，统计请求不发送 Cookie。来源仅分为直接、𝕏、GitHub 或其他。总数保留 400 天。注册及到首份保留草稿的时间从现有记录汇总计算；删除记录会改变结果。"],
  hi: ["लैंडिंग के समेकित मापन", "लैंडिंग गतिविधियाँ दैनिक कुल के रूप में गिनी जाती हैं। IP, उपयोगकर्ता पहचान, मूल रेफरर URL या फिंगरप्रिंट नहीं रखा जाता; मापन अनुरोध कुकी नहीं भेजते। स्रोत केवल सीधा/𝕏/GitHub/अन्य होता है। कुल 400 दिन रखे जाते हैं। पंजीकरण और पहले सुरक्षित ड्राफ्ट तक का समय मौजूदा रिकॉर्ड से समेकित होता है; हटाने से परिणाम बदलता है।"],
  es: ["Medición agregada de la página", "Las interacciones se cuentan por día, sin IP, identidad, URL de origen ni huella digital; las solicitudes omiten cookies. El origen se reduce a directo/𝕏/GitHub/otro. Los totales se conservan 400 días. Los registros y el tiempo hasta el primer borrador conservado se agregan a partir de datos existentes; eliminarlos cambia el resultado."],
  fr: ["Mesure agrégée de la page", "Les interactions sont comptées par jour, sans IP, identifiant, URL référente brute ni empreinte ; les requêtes omettent les cookies. Les sources sont direct/𝕏/GitHub/autre. Les totaux sont conservés 400 jours. Les inscriptions et le délai jusqu’au premier brouillon conservé sont agrégés depuis les données existantes ; leur suppression modifie le résultat."],
  ar: ["قياس مجمّع للصفحة", "تُحسب التفاعلات كمجاميع يومية، دون تسجيل IP أو هوية المستخدم أو رابط الإحالة الخام أو بصمة رقمية؛ لا ترسل طلبات القياس ملفات تعريف الارتباط. تُختزل المصادر إلى مباشر/𝕏/GitHub/غير ذلك. تُحفظ المجاميع 400 يوم. تُحسب التسجيلات والزمن حتى أول مسودة محفوظة من السجلات الموجودة؛ الحذف يغيّر النتيجة."],
  bn: ["ল্যান্ডিংয়ের সমষ্টিগত পরিমাপ", "ল্যান্ডিংয়ের কাজ দৈনিক মোট হিসেবে গণনা করা হয়। IP, ব্যবহারকারী পরিচয়, মূল রেফারার URL বা ফিঙ্গারপ্রিন্ট রাখা হয় না; পরিমাপের অনুরোধ কুকি পাঠায় না। উৎস শুধু সরাসরি/𝕏/GitHub/অন্যান্য। মোট ৪০০ দিন রাখা হয়। নিবন্ধন ও প্রথম সংরক্ষিত খসড়া পর্যন্ত সময় বিদ্যমান রেকর্ড থেকে সমষ্টিগত হিসাব হয়; মুছে ফেললে ফল বদলায়।"],
  "pt-BR": ["Medição agregada da página", "As interações são contadas por dia, sem IP, identidade, URL de origem completa ou impressão digital; as requisições omitem cookies. A origem vira direto/𝕏/GitHub/outro. Os totais ficam por 400 dias. Cadastros e tempo até o primeiro rascunho mantido são agregados dos registros existentes; exclusões alteram o resultado."],
  ru: ["Сводные измерения страницы", "Взаимодействия считаются по дням без IP, идентификаторов, исходных URL перехода и цифровых отпечатков; запросы не отправляют cookie. Источник — прямой/𝕏/GitHub/другой. Итоги хранятся 400 дней. Регистрации и время до первого сохранённого черновика вычисляются по существующим записям; удаление меняет результат."],
  id: ["Pengukuran halaman secara agregat", "Interaksi dihitung sebagai total harian tanpa IP, identitas pengguna, URL rujukan asli atau sidik jari; permintaan pengukuran tidak mengirim cookie. Sumber hanya langsung/𝕏/GitHub/lainnya. Total disimpan 400 hari. Pendaftaran dan waktu menuju draf tersimpan pertama dihitung dari catatan yang ada; penghapusan mengubah hasil."],
  ur: ["صفحے کی مجموعی پیمائش", "تعاملات روزانہ کے مجموعوں میں گنے جاتے ہیں۔ IP، صارف کی شناخت، اصل حوالہ URL یا فنگرپرنٹ محفوظ نہیں ہوتے؛ پیمائش کی درخواست کوکی نہیں بھیجتی۔ ذریعہ صرف براہ راست/𝕏/GitHub/دیگر ہے۔ مجموعے 400 دن رہتے ہیں۔ اندراج اور پہلی محفوظ مسودے تک وقت موجودہ ریکارڈ سے مجموعی طور پر نکلتا ہے؛ حذف سے نتیجہ بدلتا ہے۔"],
  de: ["Aggregierte Seitenmessung", "Interaktionen werden täglich gezählt, ohne IP, Nutzerkennung, vollständige Herkunfts-URL oder Fingerabdruck; Messanfragen senden keine Cookies. Quellen sind direkt/𝕏/GitHub/andere. Summen bleiben 400 Tage gespeichert. Anmeldungen und Zeit bis zum ersten erhaltenen Entwurf werden aus bestehenden Datensätzen aggregiert; Löschungen ändern das Ergebnis."],
  ja: ["ランディングの集計計測", "操作は日別の合計で計測します。IP、ユーザー識別子、元の参照 URL、フィンガープリントは記録せず、計測リクエストは Cookie を送りません。流入元は直接/𝕏/GitHub/その他だけです。合計は400日保持します。登録と最初に残る下書きまでの時間は既存記録から集計し、削除により結果が変わります。"],
  sw: ["Vipimo vya jumla vya ukurasa", "Mwingiliano huhesabiwa kwa jumla za kila siku bila IP, kitambulisho cha mtumiaji, URL kamili ya rufaa au alama ya kifaa; maombi hayatumi cookie. Chanzo ni moja kwa moja/𝕏/GitHub/kingine. Jumla huhifadhiwa siku 400. Usajili na muda hadi rasimu ya kwanza iliyobaki huhesabiwa kutoka rekodi zilizopo; kufuta hubadili matokeo."],
  mr: ["लँडिंगचे एकत्रित मापन", "परस्परसंवाद रोजच्या एकूण संख्येत मोजले जातात. IP, वापरकर्ता ओळख, मूळ संदर्भ URL किंवा फिंगरप्रिंट जतन होत नाही; मापन विनंत्या कुकी पाठवत नाहीत. स्रोत थेट/𝕏/GitHub/इतर इतकाच असतो. बेरीज 400 दिवस ठेवली जाते. नोंदणी आणि पहिल्या जतन केलेल्या मसुद्यापर्यंतचा वेळ विद्यमान नोंदींतून मोजतो; हटवल्याने निकाल बदलतो."],
  te: ["ల్యాండింగ్ సమగ్ర కొలతలు", "పరస్పర చర్యలను రోజువారీ మొత్తాలుగా లెక్కిస్తాం. IP, వినియోగదారు గుర్తింపు, అసలు రిఫరర్ URL లేదా ఫింగర్‌ప్రింట్ నిల్వ చేయము; కొలత అభ్యర్థనలు కుకీలను పంపవు. మూలం ప్రత్యక్షం/𝕏/GitHub/ఇతర మాత్రమే. మొత్తాలు 400 రోజులు ఉంటాయి. నమోదు, మొదటి నిల్వ డ్రాఫ్ట్ వరకు సమయం ఉన్న రికార్డుల నుంచి సమగ్రంగా లెక్కిస్తాం; తొలగింపు ఫలితాన్ని మారుస్తుంది."],
  ta: ["முகப்பின் தொகுக்கப்பட்ட அளவீடு", "செயல்பாடுகள் தினசரி மொத்தமாக எண்ணப்படும். IP, பயனர் அடையாளம், முழு பரிந்துரை URL அல்லது கைரேகை பதிவாகாது; அளவீட்டு கோரிக்கைகள் குக்கிகளை அனுப்பாது. மூலம் நேரடி/𝕏/GitHub/மற்றவை மட்டும். மொத்தங்கள் 400 நாட்கள் இருக்கும். பதிவு மற்றும் முதல் தக்கவைக்கப்பட்ட வரைவுக்கான நேரம் உள்ள பதிவுகளிலிருந்து தொகுக்கப்படும்; நீக்குதல் முடிவை மாற்றும்."],
  vi: ["Đo lường tổng hợp trang", "Tương tác được đếm theo ngày, không lưu IP, mã người dùng, URL giới thiệu gốc hay dấu vân tay; yêu cầu đo lường không gửi cookie. Nguồn chỉ là trực tiếp/𝕏/GitHub/khác. Tổng số giữ 400 ngày. Đăng ký và thời gian đến bản nháp đầu tiên còn lưu được tổng hợp từ dữ liệu hiện có; xóa dữ liệu làm thay đổi kết quả."],
  ko: ["랜딩 페이지 집계 측정", "상호작용은 일별 합계로 계산합니다. IP, 사용자 식별자, 원래 유입 URL, 지문을 기록하지 않으며 측정 요청은 쿠키를 보내지 않습니다. 유입은 직접/𝕏/GitHub/기타로만 분류합니다. 합계는 400일 보관합니다. 가입과 처음 보존된 초안까지의 시간은 기존 기록에서 집계하며 삭제하면 결과가 바뀝니다."],
};
