import type { PartialEvidenceCopy } from "./public-evidence-copy-types";

// Non-default locale copy. Allegations remain attributed; vendor statements are not
// presented as independent verification, and missing evidence is never proof of absence.
export const publicEvidenceCopyExtra: PartialEvidenceCopy = {
  en: {
    pages: {
      openSource: { title:"Open code. Inspect the system.",description:"ISPATLA's public source, license, setup and operating limits.",summary:"The repository lets you inspect and modify the application. It does not make hosting, 𝕏 API access or AI usage free.",sections:[{heading:"Code and license",body:"The application repository is public under AGPL-3.0-or-later. Read the license and third-party notices before redistributing or operating a modified network service."},{heading:"What self-hosting means",body:"The repository documents a local synthetic demo and a separate normal setup. A local demo does not prove production readiness. Operators provide and pay for infrastructure, secrets, 𝕏 access and any AI provider."}] },
      transparency: { title:"Product state, in plain view.",description:"Current ISPATLA capabilities, limits, dependencies and evidence boundaries.",summary:"A visible feature is not automatically a live provider integration. Check implementation evidence and deployment-specific behavior separately.",sections:[{heading:"Feature state",body:"Use the implementation status and linked evidence to distinguish implemented, experimental, planned and unverified work. A repository or passing local test does not prove that a deployed provider flow works."},{heading:"Data, services and costs",body:"The deployment operator controls hosting and retention. 𝕏 API and AI providers can charge separately. Review the privacy, security and architecture documents for current data flows and safeguards."}] },
      noViral: { title:"No one can guarantee virality.",description:"A campaign about evidence, decisions and user control—not guaranteed reach.",summary:"ISPATLA cannot promise that a post will spread. It can make parts of the research and review process inspectable.",sections:[{heading:"No outcome guarantee",body:"A decision score describes the system's assessment under its current evidence. It is not a calibrated chance of virality, a prediction of reach or an observed result."},{heading:"What you can inspect",body:"Review the source, rationale and editable draft, then keep the publishing decision in your hands. A provider accepting a request is not proof that a remote post was confirmed."}] },
      research: { title:"Xpatla: dated public-source notes.",description:"An evidence-labeled summary of public user reports and company statements.",summary:"This record distinguishes individual user allegations, company statements and unresolved facts. It is not a court finding or independent product audit.",sections:[{heading:"How to read this record",body:"The summaries attribute claims to the people or company that made them. A complaint is not independently verified here, and it cannot establish a general customer experience or legal conclusion."},{heading:"Reports and company statements",body:"One user report describes difficulty finding a cancellation control. Other user accounts describe refund or guarantee concerns. Xpatla's own terms and platform pages provide the company's stated position and dated service status; those statements are not independent tests."},{heading:"Correction and response",body:"Use the linked public tracker to provide a source, correction or response. We omit personal identifiers and update the dated record when relevant evidence changes."}] },
    },
    common:{checked:"Sources checked",method:"Method and limits",source:"Open source",newTab:"opens in a new tab",disclaimer:"Features, prices and company statements can change. This page is not a legal finding or independent product test.",methodText:"We distinguish direct source statements from our interpretation. A missing public source does not prove that a feature is absent.",languageLink:"Read this page in English",correction:"Corrections and responses",correctionLink:"Submit a source or correction"},
    researchHook:"An allegedly hard-to-find cancel option and refund concerns appear in user accounts; these are allegations, not established findings.",
    complaintSummary:["A user reported difficulty finding a way to cancel a subscription. This is that user's account, not an independently verified finding.","A user described a payment and refund communication concern. The account is an allegation and does not establish company-wide practice.","Xpatla's public pages state that some services and new sales were paused as of the dated notice. This is a company statement."],
    complaintResponse:["Current terms describe cancellation of renewal. That alone does not verify or refute the earlier user's experience.","The terms refer to purchase-date conditions and applicable consumer rights. We did not independently review the user's transaction or correspondence.","The platform status page describes the company's stated service changes. Recheck the linked pages because status may change."],
  },
  "zh-CN": {
    pages: {
      openSource:{title:"开放代码，检查系统。",description:"ISPATLA 的公开源码、许可证、安装方式和运行限制。",summary:"你可以检查和修改应用代码。开放源码并不意味着托管、𝕏 API 或 AI 使用免费。",sections:[{heading:"代码与许可证",body:"应用仓库以 AGPL-3.0-or-later 公开。重新分发或运营修改后的网络服务前，请阅读许可证和第三方许可说明。"},{heading:"自托管的含义",body:"仓库分别说明本地合成演示和常规安装。本地演示不能证明生产环境已就绪。运营者负责提供并支付基础设施、机密信息、𝕏 接入及 AI 服务费用。"}]},
      transparency:{title:"清楚说明产品状态。",description:"ISPATLA 当前功能、限制、依赖和证据边界。",summary:"页面展示的功能不一定代表实时服务商集成。实现证据和具体部署行为需要分别核实。",sections:[{heading:"功能状态",body:"请结合实现状态和链接证据，区分已实现、实验中、计划中和未验证的工作。仓库代码或本地测试通过不能证明线上服务商流程有效。"},{heading:"数据、服务与费用",body:"托管和数据保留由部署运营者控制。𝕏 API 和 AI 服务商可能另行收费。请查看隐私、安全和架构文档了解数据流与保护措施。"}]},
      noViral:{title:"没人能保证内容走红。",description:"关注证据、判断和用户控制，而非触达保证。",summary:"ISPATLA 无法承诺帖子传播。它可以让研究和审核过程中的部分步骤可供检查。",sections:[{heading:"不保证结果",body:"判断分数描述系统基于当前证据作出的评估，不是走红概率、触达预测或已观察到的结果。"},{heading:"你可以检查什么",body:"查看来源、理由和可编辑草稿，并由你决定是否发布。服务商接受请求不等于远端帖子已得到确认。"}]},
      research:{title:"Xpatla：带日期的公开来源记录。",description:"对公开用户报告与公司声明进行证据标注的摘要。",summary:"本记录区分个人用户陈述、公司声明和未解决事实，不是法院裁决或独立产品审计。",sections:[{heading:"如何阅读",body:"摘要会标明说法来自用户还是公司。本页未独立验证投诉，不能据此推断普遍客户体验或法律结论。"},{heading:"用户报告与公司声明",body:"一位用户称难以找到取消订阅的入口。其他用户陈述提及退款或保证方面的疑虑。这些属于用户说法。Xpatla 自己的条款和平台页面呈现公司立场及有日期的服务状态，并非独立测试。"},{heading:"更正与回应",body:"请通过公开问题跟踪器提交来源、更正或回应。我们不重发个人身份信息，并会在相关证据变化时更新带日期的记录。"}]},
    },common:{checked:"来源核查日期",method:"方法与限制",source:"打开来源",newTab:"在新标签页打开",disclaimer:"功能、价格和公司声明可能变化。本页不是法律裁决或独立产品测试。",methodText:"我们区分来源的直接表述和自身解释。没有找到公开来源不能证明某项功能不存在。",languageLink:"阅读中文页面",correction:"更正与回应",correctionLink:"提交来源或更正"},
    researchHook:"用户陈述中提及取消入口难找和退款疑虑；这些是用户说法，并非已确认事实。",
    complaintSummary:["一位用户称难以找到取消订阅的方式。这是该用户的陈述，并非经独立核实的结论。","一位用户提及付款和退款沟通方面的问题。该陈述属于个人主张，不能证明公司的普遍做法。","Xpatla 公开页面称，根据所示日期的公告，部分服务和新销售已暂停。这是公司声明。"],
    complaintResponse:["当前条款说明可取消续订。仅凭这一点既不能证实，也不能否定该用户当时的经历。","条款提及购买时适用的条件和消费者法定权利。我们未独立核查该用户的交易或沟通记录。","平台状态页说明公司公布的服务变化。状态可能更新，请重新检查链接页面。"],
  },
  hi: {
    pages:{
      openSource:{title:"खुला कोड। सिस्टम की जाँच करें।",description:"ISPATLA का सार्वजनिक स्रोत, लाइसेंस, सेटअप और संचालन सीमाएँ।",summary:"आप ऐप का कोड देख और बदल सकते हैं। खुला स्रोत होने से होस्टिंग, 𝕏 API या AI मुफ़्त नहीं होते।",sections:[{heading:"कोड और लाइसेंस",body:"ऐप रिपॉज़िटरी AGPL-3.0-or-later के अंतर्गत सार्वजनिक है। संशोधित नेटवर्क सेवा बाँटने या चलाने से पहले लाइसेंस और तृतीय-पक्ष सूचनाएँ पढ़ें।"},{heading:"स्वयं होस्ट करने का अर्थ",body:"रिपॉज़िटरी स्थानीय कृत्रिम डेमो और सामान्य सेटअप को अलग-अलग बताती है। स्थानीय डेमो उत्पादन-तैयारी सिद्ध नहीं करता। संचालक को अवसंरचना, रहस्य, 𝕏 पहुँच और AI प्रदाता की लागत स्वयं संभालनी होती है।"}]},
      transparency:{title:"उत्पाद की स्थिति साफ़-साफ़।",description:"ISPATLA की मौजूदा सुविधाएँ, सीमाएँ, निर्भरताएँ और प्रमाण की सीमाएँ।",summary:"दिखाई गई सुविधा का अर्थ हमेशा लाइव प्रदाता एकीकरण नहीं होता। कोड के प्रमाण और तैनाती का व्यवहार अलग जाँचें।",sections:[{heading:"सुविधा की स्थिति",body:"कार्यान्वयन स्थिति और जुड़े प्रमाण से लागू, प्रयोगात्मक, नियोजित और अप्रमाणित काम अलग करें। सार्वजनिक कोड या स्थानीय परीक्षण पास होना लाइव प्रदाता प्रवाह का प्रमाण नहीं है।"},{heading:"डेटा, सेवाएँ और लागत",body:"होस्टिंग और प्रतिधारण पर तैनाती संचालक का नियंत्रण है। 𝕏 API और AI प्रदाता अलग शुल्क ले सकते हैं। डेटा प्रवाह और सुरक्षा के लिए गोपनीयता, सुरक्षा और वास्तुकला दस्तावेज़ देखें।"}]},
      noViral:{title:"वायरल होने की गारंटी कोई नहीं दे सकता।",description:"यह प्रमाण, निर्णय और उपयोगकर्ता नियंत्रण पर केंद्रित है।",summary:"ISPATLA पोस्ट के फैलने का वादा नहीं कर सकता। यह शोध और समीक्षा प्रक्रिया के कुछ हिस्से जाँचने देता है।",sections:[{heading:"परिणाम की गारंटी नहीं",body:"निर्णय स्कोर मौजूदा प्रमाण के आधार पर प्रणाली का आकलन है। यह वायरल होने की प्रमाणित संभावना, पहुँच का अनुमान या देखा हुआ परिणाम नहीं है।"},{heading:"आप क्या जाँच सकते हैं",body:"स्रोत, कारण और संपादन योग्य मसौदा देखें; प्रकाशित करने का निर्णय आपका है। प्रदाता द्वारा अनुरोध स्वीकार करना दूरस्थ पोस्ट की पुष्टि नहीं है।"}]},
      research:{title:"Xpatla: तारीख सहित सार्वजनिक स्रोत नोट।",description:"सार्वजनिक उपयोगकर्ता रिपोर्ट और कंपनी बयानों का प्रमाण-लेबल वाला सार।",summary:"यह रिकॉर्ड व्यक्तिगत उपयोगकर्ता दावों, कंपनी बयानों और अनसुलझे तथ्यों को अलग करता है। यह न्यायालय का निष्कर्ष या स्वतंत्र उत्पाद ऑडिट नहीं है।",sections:[{heading:"इसे कैसे पढ़ें",body:"हर सार बताता है कि दावा किस उपयोगकर्ता या कंपनी ने किया। यहाँ शिकायतों की स्वतंत्र पुष्टि नहीं हुई; उनसे सामान्य ग्राहक अनुभव या कानूनी निष्कर्ष नहीं निकाला जा सकता।"},{heading:"रिपोर्ट और कंपनी बयान",body:"एक उपयोगकर्ता ने सदस्यता रद्द करने का विकल्प ढूँढ़ने में कठिनाई बताई। दूसरे उपयोगकर्ता विवरणों में रिफंड या गारंटी से जुड़ी चिंताएँ हैं। ये उपयोगकर्ता के दावे हैं। Xpatla की शर्तें और मंच पेज कंपनी की बताई स्थिति और तारीखयुक्त सेवा स्थिति दिखाते हैं; वे स्वतंत्र परीक्षण नहीं हैं।"},{heading:"सुधार और जवाब",body:"स्रोत, सुधार या जवाब सार्वजनिक ट्रैकर में दें। हम निजी पहचान विवरण दोबारा प्रकाशित नहीं करते और प्रासंगिक प्रमाण बदलने पर तारीखयुक्त रिकॉर्ड अद्यतन करते हैं।"}]},
    },common:{checked:"स्रोत जाँच",method:"विधि और सीमाएँ",source:"स्रोत खोलें",newTab:"नए टैब में खुलेगा",disclaimer:"सुविधाएँ, कीमतें और कंपनी के बयान बदल सकते हैं। यह कानूनी निष्कर्ष या स्वतंत्र उत्पाद परीक्षण नहीं है।",methodText:"हम स्रोत के सीधे कथन और अपनी व्याख्या अलग रखते हैं। सार्वजनिक प्रमाण न मिलना किसी सुविधा के न होने का प्रमाण नहीं है।",languageLink:"यह पृष्ठ हिंदी में पढ़ें",correction:"सुधार और जवाब",correctionLink:"स्रोत या सुधार भेजें"},
    researchHook:"उपयोगकर्ताओं के विवरण में रद्द करने का विकल्प ढूँढ़ने और रिफंड को लेकर चिंताएँ हैं; ये आरोप हैं, स्थापित निष्कर्ष नहीं।",
    complaintSummary:["एक उपयोगकर्ता ने सदस्यता रद्द करने का तरीका ढूँढ़ने में कठिनाई बताई। यह उसी उपयोगकर्ता का विवरण है, स्वतंत्र रूप से सत्यापित निष्कर्ष नहीं।","एक उपयोगकर्ता ने भुगतान और रिफंड संवाद से जुड़ी चिंता बताई। यह आरोप है और कंपनी की सामान्य प्रथा सिद्ध नहीं करता।","Xpatla के सार्वजनिक पेज के अनुसार तारीखयुक्त सूचना के समय कुछ सेवाएँ और नई बिक्री रोकी गई थीं। यह कंपनी का बयान है।"],
    complaintResponse:["मौजूदा शर्तों में नवीनीकरण रद्द करने की बात है। इससे अकेले पुराने उपयोगकर्ता अनुभव की पुष्टि या खंडन नहीं होता।","शर्तें खरीद की तारीख पर लागू नियमों और उपभोक्ता अधिकारों का उल्लेख करती हैं। हमने उस उपयोगकर्ता का लेन-देन या संवाद स्वतंत्र रूप से नहीं जाँचा।","प्लेटफ़ॉर्म स्थिति पेज कंपनी के बताए बदलाव दर्ज करता है। स्थिति बदल सकती है, इसलिए लिंक फिर जाँचें।"],
  },
  es: {
    pages:{
      openSource:{title:"Código abierto. Inspecciona el sistema.",description:"Código público, licencia, instalación y límites operativos de ISPATLA.",summary:"Puedes inspeccionar y modificar la aplicación. El código abierto no hace gratuitos el alojamiento, la API de 𝕏 ni el uso de IA.",sections:[{heading:"Código y licencia",body:"El repositorio de la aplicación es público bajo AGPL-3.0-or-later. Lee la licencia y los avisos de terceros antes de redistribuir u operar un servicio de red modificado."},{heading:"Qué significa autoalojar",body:"El repositorio documenta por separado una demo sintética local y una instalación normal. La demo local no demuestra preparación para producción. Quien opera el servicio aporta y paga la infraestructura, los secretos, el acceso a 𝕏 y los proveedores de IA."}]},
      transparency:{title:"El estado del producto, con claridad.",description:"Capacidades, límites, dependencias y alcance de las pruebas de ISPATLA.",summary:"Una función visible no implica una integración activa con un proveedor. Comprueba por separado el código y el comportamiento de cada despliegue.",sections:[{heading:"Estado de las funciones",body:"Consulta el estado de implementación y las pruebas enlazadas para distinguir lo implementado, experimental, planificado y no verificado. El código público o una prueba local aprobada no demuestra que funcione un flujo con un proveedor activo."},{heading:"Datos, servicios y costes",body:"El operador controla el alojamiento y la retención. La API de 𝕏 y los proveedores de IA pueden cobrar aparte. Revisa la documentación de privacidad, seguridad y arquitectura para conocer los flujos de datos y las protecciones."}]},
      noViral:{title:"Nadie puede garantizar que algo se vuelva viral.",description:"Una campaña sobre pruebas, decisiones y control del usuario, sin promesas de alcance.",summary:"ISPATLA no puede prometer que una publicación se difunda. Sí puede hacer inspeccionables partes del proceso de investigación y revisión.",sections:[{heading:"Sin garantía de resultados",body:"La puntuación de decisión describe la evaluación del sistema según las pruebas disponibles. No es una probabilidad calibrada de viralidad, una predicción de alcance ni un resultado observado."},{heading:"Qué puedes revisar",body:"Examina la fuente, el razonamiento y el borrador editable; tú decides si publicar. Que un proveedor acepte una solicitud no demuestra que se haya confirmado una publicación remota."}]},
      research:{title:"Xpatla: notas de fuentes públicas con fecha.",description:"Resumen con etiquetas de evidencia sobre reportes públicos y declaraciones de la empresa.",summary:"Este registro separa alegaciones individuales, declaraciones de la empresa y hechos pendientes. No es una decisión judicial ni una auditoría independiente del producto.",sections:[{heading:"Cómo leer el registro",body:"Los resúmenes atribuyen cada afirmación a quien la hizo. Aquí no se verifican de forma independiente las quejas y estas no demuestran una experiencia general ni una conclusión legal."},{heading:"Reportes y declaraciones de la empresa",body:"Una persona dijo que le costó encontrar cómo cancelar una suscripción. Otros relatos mencionan inquietudes sobre reembolsos o garantías. Son alegaciones de usuarios. Los términos y páginas de Xpatla expresan la postura de la empresa y su estado de servicio en una fecha; no son pruebas independientes."},{heading:"Correcciones y respuesta",body:"Envía fuentes, correcciones o respuestas mediante el registro público enlazado. Omitimos datos personales y actualizamos el registro fechado cuando cambia evidencia relevante."}]},
    },common:{checked:"Fuentes consultadas",method:"Método y límites",source:"Abrir fuente",newTab:"se abre en una pestaña nueva",disclaimer:"Las funciones, los precios y las declaraciones empresariales pueden cambiar. Esto no es una decisión jurídica ni una prueba independiente.",methodText:"Distinguimos las afirmaciones directas de una fuente de nuestra interpretación. No hallar una fuente pública no demuestra que una función no exista.",languageLink:"Leer esta página en español",correction:"Correcciones y respuestas",correctionLink:"Enviar una fuente o corrección"},
    researchHook:"Los relatos de usuarios mencionan una opción de cancelación difícil de encontrar e inquietudes sobre reembolsos; son alegaciones, no hechos establecidos.",
    complaintSummary:["Una persona dijo que tuvo dificultades para encontrar cómo cancelar una suscripción. Es su relato, no una conclusión verificada de forma independiente.","Una persona describió un problema de comunicación sobre un pago y un reembolso. Es una alegación y no demuestra una práctica general de la empresa.","Las páginas públicas de Xpatla indican que algunos servicios y nuevas ventas se suspendieron según el aviso fechado. Es una declaración de la empresa."],
    complaintResponse:["Las condiciones actuales describen cómo cancelar una renovación. Eso, por sí solo, no confirma ni refuta la experiencia anterior de esa persona.","Los términos mencionan las condiciones vigentes en la fecha de compra y los derechos de consumo aplicables. No revisamos de forma independiente la transacción ni la correspondencia de esa persona.","La página de estado describe los cambios anunciados por la empresa. La situación puede cambiar; vuelve a comprobar las fuentes enlazadas."],
  },
  fr: {
    pages:{
      openSource:{title:"Code ouvert. Inspectez le système.",description:"Code public, licence, installation et limites d’exploitation d’ISPATLA.",summary:"Vous pouvez examiner et modifier l’application. Le code ouvert ne rend gratuits ni l’hébergement, ni l’API 𝕏, ni l’usage de l’IA.",sections:[{heading:"Code et licence",body:"Le dépôt de l’application est public sous AGPL-3.0-or-later. Lisez la licence et les avis des tiers avant de redistribuer ou d’exploiter un service réseau modifié."},{heading:"Ce que signifie l’auto-hébergement",body:"Le dépôt décrit séparément une démo synthétique locale et une installation normale. La démo locale ne prouve pas l’aptitude à la production. L’opérateur fournit et paie l’infrastructure, les secrets, l’accès à 𝕏 et les fournisseurs d’IA."}]},
      transparency:{title:"L’état du produit, clairement.",description:"Fonctions actuelles d’ISPATLA, limites, dépendances et portée des preuves.",summary:"Une fonction visible ne signifie pas qu’une intégration fournisseur est active. Vérifiez séparément le code et le comportement du déploiement.",sections:[{heading:"État des fonctions",body:"Consultez l’état d’implémentation et les preuves liées pour distinguer les fonctions implémentées, expérimentales, prévues et non vérifiées. Un code public ou un test local réussi ne prouve pas le fonctionnement d’un flux fournisseur en direct."},{heading:"Données, services et coûts",body:"L’opérateur contrôle l’hébergement et la conservation. L’API 𝕏 et les fournisseurs d’IA peuvent facturer séparément. Consultez les documents de confidentialité, sécurité et architecture pour les flux de données et les protections."}]},
      noViral:{title:"Personne ne peut garantir la viralité.",description:"Une campagne sur les preuves, les décisions et le contrôle de l’utilisateur, sans promesse de portée.",summary:"ISPATLA ne peut promettre qu’une publication se propagera. Il peut rendre certaines étapes de recherche et de vérification consultables.",sections:[{heading:"Aucune garantie de résultat",body:"Le score de décision décrit l’évaluation du système selon les éléments disponibles. Ce n’est ni une probabilité calibrée de viralité, ni une prévision de portée, ni un résultat observé."},{heading:"Ce que vous pouvez examiner",body:"Consultez la source, le raisonnement et le brouillon modifiable ; vous décidez de publier. L’acceptation d’une requête par un fournisseur ne prouve pas qu’une publication distante a été confirmée."}]},
      research:{title:"Xpatla : notes datées de sources publiques.",description:"Résumé avec états de preuve de témoignages publics et déclarations de l’entreprise.",summary:"Ce dossier distingue les allégations individuelles, les déclarations de l’entreprise et les faits non résolus. Ce n’est ni une décision de justice ni un audit indépendant du produit.",sections:[{heading:"Comment lire ce dossier",body:"Les résumés attribuent chaque affirmation à son auteur. Les plaintes ne sont pas vérifiées indépendamment ici et ne prouvent ni une expérience client générale ni une conclusion juridique."},{heading:"Témoignages et déclarations de l’entreprise",body:"Une personne a dit avoir eu du mal à trouver comment résilier un abonnement. D’autres récits évoquent des inquiétudes de remboursement ou de garantie. Ce sont des allégations d’utilisateurs. Les conditions et pages Xpatla expriment la position de l’entreprise et un état de service daté ; elles ne constituent pas des tests indépendants."},{heading:"Corrections et réponse",body:"Envoyez une source, une correction ou une réponse via le suivi public lié. Nous omettons les identifiants personnels et mettons à jour le dossier daté lorsque des preuves pertinentes changent."}]},
    },common:{checked:"Sources consultées",method:"Méthode et limites",source:"Ouvrir la source",newTab:"s’ouvre dans un nouvel onglet",disclaimer:"Les fonctions, prix et déclarations d’entreprise peuvent changer. Ceci n’est ni une décision juridique ni un test indépendant.",methodText:"Nous distinguons les déclarations des sources de notre interprétation. L’absence de source publique trouvée ne prouve pas l’absence d’une fonction.",languageLink:"Lire cette page en français",correction:"Corrections et réponses",correctionLink:"Soumettre une source ou une correction"},
    researchHook:"Des témoignages évoquent une option de résiliation difficile à trouver et des préoccupations de remboursement ; ce sont des allégations, pas des faits établis.",
    complaintSummary:["Une personne a dit avoir eu du mal à trouver l’option de résiliation. C’est son témoignage, pas un fait vérifié indépendamment.","Une personne a décrit un problème de communication lié à un paiement et à un remboursement. Cette allégation ne démontre pas une pratique générale de l’entreprise.","Les pages publiques de Xpatla indiquent que certains services et nouvelles ventes étaient suspendus selon l’avis daté. C’est une déclaration de l’entreprise."],
    complaintResponse:["Les conditions actuelles décrivent la résiliation du renouvellement. Cela ne confirme ni ne réfute, à lui seul, le témoignage antérieur.","Les conditions mentionnent celles applicables à la date d’achat et les droits des consommateurs. Nous n’avons pas vérifié indépendamment la transaction ou les échanges de cette personne.","La page d’état décrit les changements indiqués par l’entreprise. La situation peut évoluer ; vérifiez à nouveau les pages liées."],
  },
  ar: {
    pages:{
      openSource:{title:"شفرة مفتوحة. افحص النظام.",description:"مصدر ISPATLA وترخيصه وإعداده وحدود تشغيله.",summary:"يمكنك فحص التطبيق وتعديله. المصدر المفتوح لا يجعل الاستضافة أو واجهة 𝕏 أو استخدام الذكاء الاصطناعي مجانياً.",sections:[{heading:"الشفرة والترخيص",body:"مستودع التطبيق متاح للعامة بترخيص AGPL-3.0-or-later. راجع الترخيص وإشعارات الأطراف الأخرى قبل إعادة التوزيع أو تشغيل خدمة شبكة معدّلة."},{heading:"ما معنى الاستضافة الذاتية",body:"يوثّق المستودع عرضاً محلياً اصطناعياً وإعداداً عادياً كلّاً على حدة. العرض المحلي لا يثبت الجاهزية للإنتاج. على المشغّل توفير البنية التحتية والأسرار والوصول إلى 𝕏 وتكاليف مزودي الذكاء الاصطناعي."}]},
      transparency:{title:"حالة المنتج بوضوح.",description:"قدرات ISPATLA الحالية وحدوده واعتماداته ونطاق أدلته.",summary:"ظهور ميزة لا يعني بالضرورة وجود تكامل مباشر مع مزود خدمة. افحص أدلة التنفيذ وسلوك كل نشر على حدة.",sections:[{heading:"حالة الميزات",body:"استخدم سجل التنفيذ والأدلة المرتبطة للتمييز بين ما نُفّذ وما هو تجريبي أو مخطط أو غير متحقق. لا يثبت المستودع العام أو نجاح اختبار محلي أن تدفق المزود يعمل مباشرة."},{heading:"البيانات والخدمات والتكاليف",body:"يتحكم مشغّل النشر في الاستضافة والاحتفاظ بالبيانات. قد تفرض واجهة 𝕏 ومزودو الذكاء الاصطناعي رسوماً منفصلة. راجع وثائق الخصوصية والأمان والبنية لمعرفة التدفقات والضمانات."}]},
      noViral:{title:"لا أحد يستطيع ضمان الانتشار الفيروسي.",description:"حملة عن الأدلة والقرارات وتحكم المستخدم، بلا وعود بالوصول.",summary:"لا تستطيع ISPATLA ضمان انتشار منشور. لكنها تجعل بعض خطوات البحث والمراجعة قابلة للفحص.",sections:[{heading:"لا ضمان للنتيجة",body:"تعبّر درجة القرار عن تقييم النظام وفق الأدلة المتاحة. وهي ليست احتمالاً معايراً للانتشار، ولا توقعاً للوصول، ولا نتيجة تمت ملاحظتها."},{heading:"ما الذي يمكنك فحصه",body:"راجع المصدر والتعليل والمسودة القابلة للتحرير، واتخذ قرار النشر بنفسك. قبول المزود للطلب لا يثبت تأكيد نشره عن بُعد."}]},
      research:{title:"Xpatla: ملاحظات مؤرخة من مصادر عامة.",description:"ملخص مصنف بالأدلة لتقارير مستخدمين علنية وتصريحات الشركة.",summary:"يفصل هذا السجل بين ادعاءات أفراد المستخدمين وتصريحات الشركة والوقائع غير المحسومة. ليس حكماً قضائياً أو تدقيقاً مستقلاً للمنتج.",sections:[{heading:"كيفية قراءة السجل",body:"تنسب الملخصات كل قول إلى المستخدم أو الشركة التي ذكرته. لم نتحقق هنا من الشكاوى بصورة مستقلة، ولا تثبت تجربة عامة أو نتيجة قانونية."},{heading:"تقارير المستخدمين وتصريحات الشركة",body:"ذكر أحد المستخدمين صعوبة العثور على خيار إلغاء الاشتراك. وتصف روايات أخرى مخاوف تتعلق بالاسترداد أو الضمان. هذه ادعاءات مستخدمين. تعرض شروط Xpatla وصفحاتها موقف الشركة وحالة الخدمة في تاريخ محدد؛ وليست اختبارات مستقلة."},{heading:"التصحيح والرد",body:"قدّم مصدراً أو تصحيحاً أو رداً عبر سجل المتابعة العام المرتبط. نحذف المعلومات الشخصية ونحدّث السجل المؤرخ عند تغير الأدلة ذات الصلة."}]},
    },common:{checked:"تاريخ فحص المصادر",method:"المنهج والحدود",source:"افتح المصدر",newTab:"يفتح في علامة تبويب جديدة",disclaimer:"قد تتغير الميزات والأسعار وتصريحات الشركات. هذه الصفحة ليست حكماً قانونياً أو اختباراً مستقلاً للمنتج.",methodText:"نميز بين كلام المصدر المباشر وتفسيرنا. عدم العثور على مصدر عام لا يثبت غياب ميزة.",languageLink:"اقرأ هذه الصفحة بالعربية",correction:"التصحيحات والردود",correctionLink:"أرسل مصدراً أو تصحيحاً"},
    researchHook:"تذكر روايات مستخدمين صعوبة العثور على خيار الإلغاء ومخاوف بشأن الاسترداد؛ إنها ادعاءات وليست وقائع مثبتة.",
    complaintSummary:["ذكر مستخدم أنه واجه صعوبة في العثور على طريقة لإلغاء الاشتراك. هذا وصفه الشخصي وليس نتيجة تحقق مستقل.","وصف مستخدم مشكلة تواصل بشأن دفعة واسترداد. هذا ادعاء لا يثبت ممارسة عامة للشركة.","تذكر صفحات Xpatla العامة تعليق بعض الخدمات والمبيعات الجديدة وفق الإشعار المؤرخ. هذا تصريح للشركة."],
    complaintResponse:["توضح الشروط الحالية إمكانية إلغاء التجديد. وهذا وحده لا يؤكد ولا ينفي تجربة المستخدم السابقة.","تشير الشروط إلى الأحكام السارية عند الشراء وحقوق المستهلك الواجبة. لم نراجع معاملة المستخدم أو مراسلاته بصورة مستقلة.","تصف صفحة حالة المنصة تغييرات الخدمة التي أعلنتها الشركة. قد تتغير الحالة؛ لذا أعد فحص الصفحات المرتبطة."],
  },
  bn: {
    pages:{
      openSource:{title:"খোলা কোড। সিস্টেম পরীক্ষা করুন।",description:"ISPATLA-এর উন্মুক্ত কোড, লাইসেন্স, সেটআপ ও পরিচালনার সীমা।",summary:"আপনি অ্যাপের কোড পরীক্ষা ও পরিবর্তন করতে পারেন। ওপেন সোর্স হওয়া মানে হোস্টিং, 𝕏 API বা AI ব্যবহার বিনামূল্যে নয়।",sections:[{heading:"কোড ও লাইসেন্স",body:"অ্যাপের রিপোজিটরি AGPL-3.0-or-later লাইসেন্সে প্রকাশ্য। পরিবর্তিত নেটওয়ার্ক সেবা পুনর্বিতরণ বা পরিচালনার আগে লাইসেন্স ও তৃতীয় পক্ষের নোটিশ পড়ুন।"},{heading:"নিজে হোস্ট করার অর্থ",body:"রিপোজিটরিতে স্থানীয় কৃত্রিম ডেমো এবং স্বাভাবিক সেটআপ আলাদা করে নথিভুক্ত। স্থানীয় ডেমো উৎপাদন-প্রস্তুতি প্রমাণ করে না। অবকাঠামো, গোপন তথ্য, 𝕏 অ্যাক্সেস এবং AI খরচ পরিচালনাকারীকেই দিতে হয়।"}]},
      transparency:{title:"পণ্যের অবস্থা, স্পষ্টভাবে।",description:"ISPATLA-এর বর্তমান সক্ষমতা, সীমা, নির্ভরতা ও প্রমাণের পরিসর।",summary:"কোনো বৈশিষ্ট্য দেখা গেলেই লাইভ সেবা-সংযোগ প্রমাণ হয় না। বাস্তবায়নের প্রমাণ ও নির্দিষ্ট স্থাপনার আচরণ আলাদাভাবে যাচাই করুন।",sections:[{heading:"বৈশিষ্ট্যের অবস্থা",body:"বাস্তবায়ন অবস্থা ও সংযুক্ত প্রমাণ দেখে সম্পন্ন, পরীক্ষামূলক, পরিকল্পিত এবং অযাচাইকৃত কাজ আলাদা করুন। উন্মুক্ত কোড বা স্থানীয় পরীক্ষায় সাফল্য লাইভ সেবা প্রবাহ প্রমাণ করে না।"},{heading:"তথ্য, সেবা ও খরচ",body:"হোস্টিং ও তথ্য সংরক্ষণ স্থাপনা পরিচালনাকারী নিয়ন্ত্রণ করেন। 𝕏 API ও AI সেবাদাতা আলাদা খরচ নিতে পারে। তথ্যপ্রবাহ ও সুরক্ষা জানতে গোপনীয়তা, নিরাপত্তা ও স্থাপত্য নথি দেখুন।"}]},
      noViral:{title:"ভাইরাল হওয়ার নিশ্চয়তা কেউ দিতে পারে না।",description:"প্রমাণ, সিদ্ধান্ত ও ব্যবহারকারীর নিয়ন্ত্রণ নিয়ে প্রচার; পৌঁছানোর প্রতিশ্রুতি নয়।",summary:"ISPATLA কোনো পোস্ট ছড়িয়ে পড়ার নিশ্চয়তা দিতে পারে না। গবেষণা ও পর্যালোচনার কিছু ধাপ পরীক্ষা করার সুযোগ দেয়।",sections:[{heading:"ফলাফলের নিশ্চয়তা নেই",body:"সিদ্ধান্ত স্কোর বর্তমান প্রমাণ অনুযায়ী সিস্টেমের মূল্যায়ন। এটি ক্যালিব্রেট করা ভাইরাল সম্ভাবনা, পৌঁছানোর পূর্বাভাস বা পর্যবেক্ষিত ফল নয়।"},{heading:"আপনি যা পরীক্ষা করতে পারেন",body:"উৎস, যুক্তি ও সম্পাদনাযোগ্য খসড়া দেখুন; প্রকাশের সিদ্ধান্ত আপনার। সেবাদাতা অনুরোধ গ্রহণ করলেই দূরবর্তী পোস্ট নিশ্চিত হয়েছে এমন নয়।"}]},
      research:{title:"Xpatla: তারিখসহ প্রকাশ্য উৎসের নোট।",description:"প্রকাশ্য ব্যবহারকারী প্রতিবেদন ও কোম্পানির বক্তব্যের প্রমাণ-চিহ্নিত সারাংশ।",summary:"এই নথি ব্যক্তিগত ব্যবহারকারীর অভিযোগ, কোম্পানির বক্তব্য এবং অমীমাংসিত তথ্য আলাদা করে। এটি আদালতের সিদ্ধান্ত বা স্বাধীন পণ্য নিরীক্ষা নয়।",sections:[{heading:"নথিটি কীভাবে পড়বেন",body:"সারাংশে বলা হয় কে বক্তব্য দিয়েছেন—ব্যবহারকারী না কোম্পানি। এখানে অভিযোগ স্বাধীনভাবে যাচাই করা হয়নি; এগুলো সাধারণ গ্রাহক অভিজ্ঞতা বা আইনি সিদ্ধান্ত প্রমাণ করে না।"},{heading:"প্রতিবেদন ও কোম্পানির বক্তব্য",body:"এক ব্যবহারকারী সাবস্ক্রিপশন বাতিলের উপায় খুঁজে পেতে অসুবিধার কথা বলেছেন। অন্য বর্ণনায় ফেরত বা গ্যারান্টি নিয়ে উদ্বেগ আছে। এগুলো ব্যবহারকারীর অভিযোগ। Xpatla-এর নিজস্ব শর্ত ও প্ল্যাটফর্ম পেজ কোম্পানির বক্তব্য এবং তারিখভিত্তিক সেবার অবস্থা জানায়; সেগুলো স্বাধীন পরীক্ষা নয়।"},{heading:"সংশোধন ও জবাব",body:"উৎস, সংশোধন বা জবাব যুক্ত প্রকাশ্য ট্র্যাকার দিয়ে পাঠান। ব্যক্তিগত পরিচয় প্রকাশ করি না এবং প্রাসঙ্গিক প্রমাণ বদলালে তারিখযুক্ত নথি হালনাগাদ করি।"}]},
    },common:{checked:"উৎস যাচাই",method:"পদ্ধতি ও সীমা",source:"উৎস খুলুন",newTab:"নতুন ট্যাবে খুলবে",disclaimer:"বৈশিষ্ট্য, দাম ও কোম্পানির বক্তব্য বদলাতে পারে। এটি আইনি সিদ্ধান্ত বা স্বাধীন পণ্য পরীক্ষা নয়।",methodText:"উৎসের সরাসরি বক্তব্য ও আমাদের ব্যাখ্যা আলাদা রাখা হয়েছে। প্রকাশ্য উৎস না পাওয়া মানে বৈশিষ্ট্যটি নেই—এমন প্রমাণ নয়।",languageLink:"এই পৃষ্ঠা বাংলায় পড়ুন",correction:"সংশোধন ও জবাব",correctionLink:"উৎস বা সংশোধন পাঠান"},
    researchHook:"ব্যবহারকারীদের বর্ণনায় বাতিলের বিকল্প খুঁজে পাওয়া কঠিন এবং ফেরত নিয়ে উদ্বেগের কথা আছে; এগুলো অভিযোগ, প্রতিষ্ঠিত তথ্য নয়।",
    complaintSummary:["এক ব্যবহারকারী সাবস্ক্রিপশন বাতিলের উপায় খুঁজে পেতে অসুবিধার কথা বলেছেন। এটি তাঁর বর্ণনা, স্বাধীনভাবে যাচাই করা সিদ্ধান্ত নয়।","এক ব্যবহারকারী পেমেন্ট ও ফেরত-সংক্রান্ত যোগাযোগের উদ্বেগ জানিয়েছেন। এটি অভিযোগ; কোম্পানির সাধারণ চর্চা প্রমাণ করে না।","তারিখযুক্ত নোটিশ অনুযায়ী কিছু সেবা ও নতুন বিক্রি স্থগিত ছিল বলে Xpatla-এর প্রকাশ্য পেজে বলা হয়েছে। এটি কোম্পানির বক্তব্য।"],
    complaintResponse:["বর্তমান শর্তে নবায়ন বাতিলের কথা বলা আছে। শুধু এটুকু দিয়ে আগের ব্যবহারকারীর অভিজ্ঞতা নিশ্চিত বা নাকচ করা যায় না।","শর্তে কেনার তারিখের নিয়ম ও প্রযোজ্য ভোক্তা অধিকারের কথা আছে। ওই ব্যবহারকারীর লেনদেন বা কথোপকথন আমরা স্বাধীনভাবে যাচাই করিনি।","প্ল্যাটফর্মের অবস্থা পেজে কোম্পানির ঘোষিত পরিবর্তন আছে। অবস্থা বদলাতে পারে; লিংক করা পেজ আবার দেখুন।"],
  },
  "pt-BR": {
    pages:{
      openSource:{title:"Código aberto. Inspecione o sistema.",description:"Código público, licença, instalação e limites operacionais do ISPATLA.",summary:"Você pode inspecionar e modificar o aplicativo. Código aberto não torna gratuitos hospedagem, API do 𝕏 ou uso de IA.",sections:[{heading:"Código e licença",body:"O repositório do aplicativo é público sob AGPL-3.0-or-later. Leia a licença e os avisos de terceiros antes de redistribuir ou operar um serviço de rede modificado."},{heading:"O que significa hospedar por conta própria",body:"O repositório documenta separadamente uma demonstração sintética local e uma instalação normal. A demonstração não comprova prontidão para produção. O operador fornece e paga infraestrutura, segredos, acesso ao 𝕏 e provedores de IA."}]},
      transparency:{title:"Estado do produto, com clareza.",description:"Recursos atuais do ISPATLA, limites, dependências e alcance das evidências.",summary:"Um recurso visível não implica integração ativa com um provedor. Verifique separadamente as evidências do código e o comportamento de cada implantação.",sections:[{heading:"Estado dos recursos",body:"Consulte o status de implementação e as evidências vinculadas para distinguir o que está implementado, experimental, planejado e não verificado. Código público ou teste local aprovado não comprova funcionamento ao vivo."},{heading:"Dados, serviços e custos",body:"O operador controla hospedagem e retenção. A API do 𝕏 e provedores de IA podem cobrar à parte. Consulte os documentos de privacidade, segurança e arquitetura para conhecer fluxos de dados e proteções."}]},
      noViral:{title:"Ninguém pode garantir viralização.",description:"Uma campanha sobre evidências, decisões e controle do usuário, sem promessa de alcance.",summary:"O ISPATLA não pode prometer que uma publicação vai se espalhar. Pode tornar partes da pesquisa e revisão inspecionáveis.",sections:[{heading:"Sem garantia de resultado",body:"A pontuação de decisão descreve a avaliação do sistema com as evidências disponíveis. Não é probabilidade calibrada de viralização, previsão de alcance nem resultado observado."},{heading:"O que você pode inspecionar",body:"Examine a fonte, a justificativa e o rascunho editável; a decisão de publicar é sua. A aceitação de uma solicitação pelo provedor não comprova que a publicação remota foi confirmada."}]},
      research:{title:"Xpatla: notas datadas de fontes públicas.",description:"Resumo com rótulos de evidência sobre relatos públicos e declarações da empresa.",summary:"Este registro separa alegações individuais de usuários, declarações da empresa e fatos não resolvidos. Não é decisão judicial nem auditoria independente do produto.",sections:[{heading:"Como ler este registro",body:"Os resumos atribuem cada afirmação a quem a fez. As reclamações não foram verificadas de forma independente aqui e não demonstram uma experiência geral nem uma conclusão jurídica."},{heading:"Relatos e declarações da empresa",body:"Uma pessoa relatou dificuldade para encontrar como cancelar uma assinatura. Outros relatos mencionam preocupações com reembolso ou garantia. São alegações de usuários. Os termos e páginas da Xpatla apresentam a posição da empresa e um status de serviço datado; não são testes independentes."},{heading:"Correções e resposta",body:"Envie fontes, correções ou respostas pelo rastreador público vinculado. Não republicamos dados pessoais e atualizamos o registro datado quando evidências relevantes mudam."}]},
    },common:{checked:"Fontes consultadas",method:"Método e limites",source:"Abrir fonte",newTab:"abre em nova aba",disclaimer:"Recursos, preços e declarações da empresa podem mudar. Isto não é decisão jurídica nem teste independente do produto.",methodText:"Separamos declarações diretas das fontes da nossa interpretação. Não encontrar uma fonte pública não prova que o recurso não exista.",languageLink:"Ler esta página em português",correction:"Correções e respostas",correctionLink:"Enviar fonte ou correção"},
    researchHook:"Relatos mencionam dificuldade para encontrar o cancelamento e preocupações com reembolso; são alegações, não fatos estabelecidos.",
    complaintSummary:["Uma pessoa relatou dificuldade para encontrar como cancelar uma assinatura. É o relato dessa pessoa, não uma conclusão verificada de forma independente.","Uma pessoa descreveu preocupação com a comunicação sobre pagamento e reembolso. É uma alegação, não prova de prática geral da empresa.","As páginas públicas da Xpatla dizem que alguns serviços e novas vendas foram suspensos conforme o aviso datado. É uma declaração da empresa."],
    complaintResponse:["Os termos atuais descrevem o cancelamento da renovação. Isso, por si só, não confirma nem refuta a experiência anterior relatada.","Os termos mencionam as condições vigentes na data da compra e os direitos obrigatórios do consumidor. Não verificamos de forma independente a transação ou as conversas dessa pessoa.","A página de status descreve as mudanças anunciadas pela empresa. A situação pode mudar; confira novamente as páginas vinculadas."],
  },
  ru: {
    pages:{
      openSource:{title:"Открытый код. Изучите систему.",description:"Открытый исходный код ISPATLA, лицензия, настройка и ограничения эксплуатации.",summary:"Исходный код приложения можно изучать и изменять. Открытая лицензия не делает бесплатными хостинг, API 𝕏 или ИИ.",sections:[{heading:"Код и лицензия",body:"Репозиторий приложения открыт по лицензии AGPL-3.0-or-later. Перед распространением или запуском изменённого сетевого сервиса прочитайте лицензию и уведомления о сторонних компонентах."},{heading:"Что означает самостоятельный хостинг",body:"В репозитории отдельно описаны локальная синтетическая демоверсия и обычная настройка. Локальное демо не подтверждает готовность к эксплуатации. Оператор предоставляет и оплачивает инфраструктуру, секреты, доступ к 𝕏 и услуги ИИ."}]},
      transparency:{title:"О состоянии продукта — прямо.",description:"Текущие возможности ISPATLA, ограничения, зависимости и границы доказательств.",summary:"Наличие функции в интерфейсе не подтверждает работу интеграции с провайдером. Код и поведение конкретного развёртывания нужно проверять отдельно.",sections:[{heading:"Состояние функций",body:"По статусу реализации и ссылкам на доказательства различайте реализованные, экспериментальные, запланированные и непроверенные функции. Открытый код или успешный локальный тест не доказывает работу боевого интеграционного потока."},{heading:"Данные, сервисы и расходы",body:"Оператор развёртывания управляет хостингом и сроками хранения. API 𝕏 и провайдеры ИИ могут взимать отдельную плату. Потоки данных и меры защиты описаны в документах о конфиденциальности, безопасности и архитектуре."}]},
      noViral:{title:"Никто не может гарантировать вирусный охват.",description:"Кампания о доказательствах, решениях и контроле пользователя — без обещаний охвата.",summary:"ISPATLA не обещает распространение публикации. Он делает доступными для проверки некоторые этапы исследования и оценки.",sections:[{heading:"Без гарантии результата",body:"Оценка решения отражает анализ системы по имеющимся данным. Это не откалиброванная вероятность вирусного распространения, прогноз охвата или наблюдённый результат."},{heading:"Что можно проверить",body:"Изучите источник, обоснование и редактируемый черновик; решение о публикации остаётся за вами. Принятие запроса провайдером не подтверждает публикацию удалённой записи."}]},
      research:{title:"Xpatla: датированные заметки по открытым источникам.",description:"Сводка с обозначением статуса доказательств для публичных отзывов и заявлений компании.",summary:"В этом документе отдельно представлены заявления отдельных пользователей, слова компании и нерешённые вопросы. Это не судебное решение и не независимый аудит продукта.",sections:[{heading:"Как читать документ",body:"В сводках указано, кто сделал заявление — пользователь или компания. Жалобы здесь независимо не проверялись и не подтверждают общий пользовательский опыт или юридический вывод."},{heading:"Отзывы и заявления компании",body:"Один пользователь сообщил, что ему было трудно найти отмену подписки. Другие рассказы касаются возвратов или гарантий. Это заявления пользователей. Условия и страницы Xpatla показывают позицию компании и датированный статус сервиса, но не являются независимой проверкой."},{heading:"Исправления и ответ",body:"Отправьте источник, исправление или ответ через связанный публичный трекер. Личные данные не публикуются; датированная запись обновляется при изменении существенных доказательств."}]},
    },common:{checked:"Проверка источников",method:"Метод и ограничения",source:"Открыть источник",newTab:"откроется в новой вкладке",disclaimer:"Функции, цены и заявления компании могут меняться. Это не судебное решение и не независимый тест продукта.",methodText:"Мы отделяем прямые высказывания источников от собственной интерпретации. Отсутствие найденного публичного источника не доказывает отсутствия функции.",languageLink:"Читать страницу на русском",correction:"Исправления и ответы",correctionLink:"Отправить источник или исправление"},
    researchHook:"В сообщениях пользователей упоминаются трудности с поиском отмены и опасения по поводу возврата; это заявления, а не установленные факты.",
    complaintSummary:["Пользователь сообщил, что ему было трудно найти способ отменить подписку. Это его рассказ, а не независимо подтверждённый факт.","Пользователь описал затруднение в общении по поводу платежа и возврата. Это заявление, не доказывающее общую практику компании.","На публичных страницах Xpatla указано, что по датированному уведомлению некоторые услуги и новые продажи были приостановлены. Это заявление компании."],
    complaintResponse:["В текущих условиях описана отмена продления. Само по себе это не подтверждает и не опровергает прежний опыт пользователя.","Условия ссылаются на правила на дату покупки и обязательные права потребителей. Мы независимо не проверяли сделку или переписку пользователя.","На странице статуса описаны изменения, заявленные компанией. Статус может измениться — проверьте ссылки ещё раз."],
  },
  id: {
    pages:{
      openSource:{title:"Kode terbuka. Periksa sistemnya.",description:"Kode publik ISPATLA, lisensi, penyiapan, dan batas operasional.",summary:"Anda dapat memeriksa dan mengubah kode aplikasi. Sumber terbuka tidak membuat hosting, API 𝕏, atau penggunaan AI menjadi gratis.",sections:[{heading:"Kode dan lisensi",body:"Repositori aplikasi tersedia untuk umum dengan lisensi AGPL-3.0-or-later. Baca lisensi dan pemberitahuan pihak ketiga sebelum mendistribusikan atau mengoperasikan layanan jaringan yang dimodifikasi."},{heading:"Arti mengelola hosting sendiri",body:"Repositori mendokumentasikan demo sintetis lokal dan penyiapan normal secara terpisah. Demo lokal tidak membuktikan kesiapan produksi. Operator menyediakan dan membayar infrastruktur, rahasia, akses 𝕏, serta layanan penyedia AI."}]},
      transparency:{title:"Status produk, dijelaskan dengan jelas.",description:"Kemampuan ISPATLA saat ini, batasan, dependensi, dan cakupan bukti.",summary:"Fitur yang terlihat belum tentu terhubung langsung ke penyedia. Periksa bukti implementasi dan perilaku setiap penerapan secara terpisah.",sections:[{heading:"Status fitur",body:"Gunakan status implementasi dan bukti terkait untuk membedakan pekerjaan yang sudah diterapkan, eksperimental, direncanakan, dan belum diverifikasi. Kode publik atau tes lokal yang lulus bukan bukti bahwa alur penyedia langsung berfungsi."},{heading:"Data, layanan, dan biaya",body:"Operator penerapan mengendalikan hosting dan retensi. API 𝕏 dan penyedia AI dapat mengenakan biaya terpisah. Baca dokumen privasi, keamanan, dan arsitektur untuk alur data serta perlindungannya."}]},
      noViral:{title:"Tidak ada yang bisa menjamin viral.",description:"Kampanye tentang bukti, keputusan, dan kendali pengguna—tanpa janji jangkauan.",summary:"ISPATLA tidak dapat menjanjikan sebuah kiriman akan menyebar. Sebagian proses riset dan peninjauan dapat diperiksa.",sections:[{heading:"Tidak menjamin hasil",body:"Skor keputusan menggambarkan penilaian sistem berdasarkan bukti yang tersedia. Skor itu bukan probabilitas viral yang terkalibrasi, perkiraan jangkauan, atau hasil yang diamati."},{heading:"Hal yang dapat Anda periksa",body:"Tinjau sumber, alasan, dan draf yang dapat diedit; keputusan menerbitkan tetap milik Anda. Penyedia menerima permintaan bukan bukti kiriman jarak jauh telah dikonfirmasi."}]},
      research:{title:"Xpatla: catatan sumber publik bertanggal.",description:"Ringkasan berlabel bukti tentang laporan pengguna dan pernyataan perusahaan.",summary:"Catatan ini membedakan klaim pengguna perorangan, pernyataan perusahaan, dan fakta yang belum terselesaikan. Ini bukan putusan hukum atau audit produk independen.",sections:[{heading:"Cara membaca catatan",body:"Ringkasan menyebutkan apakah pernyataan berasal dari pengguna atau perusahaan. Keluhan tidak diverifikasi secara independen di sini dan tidak membuktikan pengalaman pelanggan secara umum atau kesimpulan hukum."},{heading:"Laporan dan pernyataan perusahaan",body:"Seorang pengguna melaporkan kesulitan menemukan cara membatalkan langganan. Laporan lain menyebut kekhawatiran tentang pengembalian dana atau jaminan. Itu adalah klaim pengguna. Ketentuan dan halaman Xpatla menyatakan posisi perusahaan serta status layanan bertanggal; keduanya bukan pengujian independen."},{heading:"Koreksi dan tanggapan",body:"Kirim sumber, koreksi, atau tanggapan melalui pelacak publik yang ditautkan. Kami tidak menerbitkan ulang identitas pribadi dan memperbarui catatan bertanggal saat bukti relevan berubah."}]},
    },common:{checked:"Sumber diperiksa",method:"Metode dan batasan",source:"Buka sumber",newTab:"dibuka di tab baru",disclaimer:"Fitur, harga, dan pernyataan perusahaan dapat berubah. Ini bukan putusan hukum atau pengujian produk independen.",methodText:"Kami memisahkan pernyataan langsung dari sumber dan interpretasi kami. Tidak menemukan sumber publik bukan bukti bahwa fitur tidak ada.",languageLink:"Baca halaman ini dalam bahasa Indonesia",correction:"Koreksi dan tanggapan",correctionLink:"Kirim sumber atau koreksi"},
    researchHook:"Laporan pengguna menyebut opsi pembatalan yang sulit ditemukan dan kekhawatiran soal pengembalian dana; ini klaim, bukan fakta yang terbukti.",
    complaintSummary:["Seorang pengguna melaporkan kesulitan menemukan cara membatalkan langganan. Ini adalah keterangannya, bukan temuan yang diverifikasi secara independen.","Seorang pengguna menceritakan masalah komunikasi tentang pembayaran dan pengembalian dana. Klaim ini tidak membuktikan praktik umum perusahaan.","Halaman publik Xpatla menyatakan bahwa beberapa layanan dan penjualan baru dihentikan sesuai pemberitahuan bertanggal. Ini pernyataan perusahaan."],
    complaintResponse:["Ketentuan saat ini menjelaskan pembatalan perpanjangan. Hal itu saja tidak mengonfirmasi atau menyangkal pengalaman pengguna sebelumnya.","Ketentuan merujuk pada aturan saat pembelian dan hak konsumen yang berlaku. Kami tidak memeriksa transaksi atau korespondensi pengguna secara independen.","Halaman status menjelaskan perubahan layanan yang dinyatakan perusahaan. Status bisa berubah; periksa kembali halaman yang ditautkan."],
  },
};
