export type EvidenceState = "verified" | "vendor_claim" | "user_allegation" | "unverified" | "superseded";
export type Subject = "ispatla" | "xpatla";

export type ComparisonEvidence = {
  id: string;
  subject: Subject;
  topic: string;
  claim: { tr: string; en: string };
  state: EvidenceState;
  sourceUrl: string;
  sourceLabel: { tr: string; en: string };
  observedAt: string;
  eventDate?: string;
  note?: { tr: string; en: string };
};

// Snapshot checked 2026-10-09; vendor pages and plan terms can change.
export const evidence: ComparisonEvidence[] = [
  { id: "isp-repo", subject: "ispatla", topic: "source", claim: { tr: "Uygulama deposu herkese açık ve AGPL-3.0 lisanslıdır.", en: "The application repository is public and licensed under AGPL-3.0." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA", sourceLabel: { tr: "GitHub deposu ve lisans işareti", en: "GitHub repository and license marker" }, observedAt: "2026-10-09" },
  { id: "isp-demo", subject: "ispatla", topic: "self-host", claim: { tr: "Depo, yerel kurulum ve kimlik bilgisi gerektirmeyen sentetik demo adımlarını belgeliyor.", en: "The repository documents local setup and a synthetic demo that needs no credentials." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA#katk%C4%B1c%C4%B1-demosu", sourceLabel: { tr: "README: demo ve yerel başlangıç", en: "README: demo and local setup" }, observedAt: "2026-10-09", note: { tr: "Bu, her kurulumun işletildiği, güvenli olduğu veya gerçek 𝕏 yayınını etkinleştirdiği anlamına gelmez.", en: "This does not mean every installation is operated, secure, or configured for live 𝕏 publishing." } },
  { id: "isp-mcp", subject: "ispatla", topic: "developer", claim: { tr: "Depoda oturum çereziyle uygulama oturumunu yeniden doğrulayan yerel stdio MCP sunucusu belgelenmiştir.", en: "The repository documents a local stdio MCP server that revalidates the application session cookie." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA#kontroller-ve-worker", sourceLabel: { tr: "README: MCP erişimi", en: "README: MCP access" }, observedAt: "2026-10-09", note: { tr: "Bu bir yönetilen, herkese açık API hizmeti değildir.", en: "This is not a hosted public API service." } },
  { id: "isp-x", subject: "ispatla", topic: "publishing", claim: { tr: "Kod, resmi 𝕏 OAuth ve kontrollü yayın/doğrulama akışları içeriyor; canlı sağlayıcı çalışması bu sayfada test edilmedi.", en: "The code includes official 𝕏 OAuth and controlled publishing/verification flows; live provider operation was not tested for this page." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA#resmi-x-ba%C4%9Flant%C4%B1s%C4%B1", sourceLabel: { tr: "README: 𝕏 bağlantısı ve sınırlar", en: "README: 𝕏 connection and limits" }, observedAt: "2026-10-09" },
  { id: "isp-cost", subject: "ispatla", topic: "price", claim: { tr: "İndirme/lisans ücreti yoktur; 𝕏 API, barındırma ve AI sağlayıcı giderleri ayrıca kullanıcı veya işletmeciye aittir.", en: "There is no download/license fee; 𝕏 API, hosting, and AI provider costs remain separate." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA", sourceLabel: { tr: "Depo ve lisans", en: "Repository and license" }, observedAt: "2026-10-09" },
  { id: "isp-browser-unverified", subject: "ispatla", topic: "browser-extension", claim: { tr: "İncelenen depoda bir tarayıcı eklentisi belgelenmemiştir.", en: "No browser extension is documented in the repository inspected." }, state: "unverified", sourceUrl: "https://github.com/OnurByte/ISPATLA", sourceLabel: { tr: "ISPATLA deposu", en: "ISPATLA repository" }, observedAt: "2026-10-09", note: { tr: "Bu, başka bir yerde eklenti olmadığına dair kanıt değildir.", en: "This does not prove that no extension exists elsewhere." } },
  { id: "isp-library-unverified", subject: "ispatla", topic: "viral-library", claim: { tr: "İncelenen depoda büyük gönderi kütüphanesi belgelenmemiştir.", en: "A large post library is not documented in the repository inspected." }, state: "unverified", sourceUrl: "https://github.com/OnurByte/ISPATLA", sourceLabel: { tr: "ISPATLA deposu", en: "ISPATLA repository" }, observedAt: "2026-10-09", note: { tr: "Bu, başka bir yerde böyle bir kütüphane olmadığına dair kanıt değildir.", en: "This does not prove that such a library exists nowhere else." } },
  { id: "isp-engagement", subject: "ispatla", topic: "engagement", claim: { tr: "README, otomatik beğeni ve DM desteği olmadığını açıkça belirtiyor.", en: "The README explicitly says automated likes and DMs are not supported." }, state: "verified", sourceUrl: "https://github.com/OnurByte/ISPATLA#s%C4%B1n%C4%B1rlar", sourceLabel: { tr: "README: ürün sınırları", en: "README: product limits" }, observedAt: "2026-10-09" },
  { id: "xpatla-browser-unverified", subject: "xpatla", topic: "browser-extension", claim: { tr: "İncelenen Xpatla belgelerinde tarayıcı eklentisi doğrulanmadı.", en: "A browser extension was not verified in the Xpatla materials inspected." }, state: "unverified", sourceUrl: "https://xpatla.com/legal/terms", sourceLabel: { tr: "Xpatla koşulları", en: "Xpatla terms" }, observedAt: "2026-10-09" },
  { id: "xpatla-library-unverified", subject: "xpatla", topic: "viral-library", claim: { tr: "İncelenen Xpatla belgelerinde gönderi kütüphanesi doğrulanmadı.", en: "A post library was not verified in the Xpatla materials inspected." }, state: "unverified", sourceUrl: "https://xpatla.com/legal/terms", sourceLabel: { tr: "Xpatla koşulları", en: "Xpatla terms" }, observedAt: "2026-10-09" },
  { id: "xpatla-engagement", subject: "xpatla", topic: "engagement", claim: { tr: "Şirket, engagement pazarının kapalı olduğunu ve Circle/Growth Credit askıya alındığını belirtiyor.", en: "The company says its engagement marketplace is closed and Circle/Growth Credit are suspended." }, state: "vendor_claim", sourceUrl: "https://xpatla.com/platform-integrity", sourceLabel: { tr: "Xpatla platform bütünlüğü", en: "Xpatla platform integrity" }, observedAt: "2026-10-09", eventDate: "2026-07-10" },
  { id: "xpatla-current", subject: "xpatla", topic: "availability", claim: { tr: "Xpatla'nın 10 Temmuz 2026 tarihli koşulları yeni kayıt ve satın alımı, 𝕏 bağlantısı/veri erişimini ve 𝕏 yayınını askıda; mevcut üyeler için çevrimdışı taslağı kullanılabilir olarak tanımlıyor.", en: "Xpatla's terms dated July 10, 2026 suspend new registrations and purchases, 𝕏 linking/data access and publishing, while describing offline drafting as available to existing members." }, state: "vendor_claim", sourceUrl: "https://xpatla.com/legal/terms", sourceLabel: { tr: "Xpatla hizmet koşulları", en: "Xpatla terms of service" }, observedAt: "2026-10-09", eventDate: "2026-07-10" },
  { id: "xpatla-integrity", subject: "xpatla", topic: "features", claim: { tr: "Şirket Circle ve Growth Credit özelliklerini 10 Temmuz 2026'da askıya aldığını; engagement pazarını kapattığını açıklıyor.", en: "The company says Circle and Growth Credit were suspended on July 10, 2026, and its engagement marketplace closed." }, state: "vendor_claim", sourceUrl: "https://xpatla.com/platform-integrity", sourceLabel: { tr: "Xpatla platform bütünlüğü", en: "Xpatla platform integrity" }, observedAt: "2026-10-09", eventDate: "2026-07-10" },
  { id: "xpatla-draft", subject: "xpatla", topic: "features", claim: { tr: "Koşullar mevcut üyeler için AI destekli çevrimdışı içerik taslağı bulunduğunu belirtiyor.", en: "The terms say AI-assisted offline content drafting remains available to existing members." }, state: "vendor_claim", sourceUrl: "https://xpatla.com/legal/terms", sourceLabel: { tr: "Xpatla hizmet koşulları", en: "Xpatla terms of service" }, observedAt: "2026-10-09" },
  { id: "xpatla-source", subject: "xpatla", topic: "source", claim: { tr: "İncelenen herkese açık kaynaklarda ana Xpatla uygulama kodunun açık lisanslı olduğu doğrulanmadı.", en: "The inspected public sources did not verify the main Xpatla application code as openly licensed." }, state: "unverified", sourceUrl: "https://xpatla.com/legal/terms", sourceLabel: { tr: "Xpatla koşulları ve herkese açık belgeler", en: "Xpatla terms and public documentation" }, observedAt: "2026-10-09", note: { tr: "Kamuya açık kaynak bulamamak, hiçbir kodun açık olmadığını kanıtlamaz.", en: "Not finding a public source does not prove no code is open." } },
];

export const complaintEvidence = [
  { id: "cancel", state: "user_allegation", eventDate: "2026-05-10", sourceUrl: "https://www.sikayetvar.com/xpatlacom/aylik-uyelik-iptal-secenegi-yok-yardim-bekliyorum", responseUrl: "https://xpatla.com/legal/terms", summary: { tr: "Bir kullanıcı, aboneliği yaklaşık iki aydır iptal edemediğini ve arayüzde iptal seçeneği bulamadığını yazdı.", en: "A user wrote that they had been unable to cancel a subscription for about two months and could not find a cancellation option in the interface." }, response: { tr: "Güncel koşullar, aboneliğin yenilenmesinin iptal edilebildiğini söylüyor. Bu, şikâyet tarihindeki hesabın deneyimini tek başına doğrulamaz veya çürütmez.", en: "Current terms say renewal can be cancelled. That alone neither verifies nor refutes the user's account of the earlier experience." } },
  { id: "refund", state: "user_allegation", eventDate: "2026-03-16", sourceUrl: "https://www.sikayetvar.com/xpatlacom/xpatla-iade-talebi", responseUrl: "https://xpatla.com/legal/terms", summary: { tr: "Bir kullanıcı 12 Mart'ta 886 TL ödediğini, kısa denemeden sonra aynı gün iade istediğini ve iletişim sorunu yaşadığını ileri sürdü.", en: "A user alleged paying TRY 886 on March 12, requesting a refund the same day after a short trial, and experiencing a communication problem." }, response: { tr: "Şirketin 10 Temmuz tarihli koşulları önceki satın alımların satın alma anındaki garanti ve zorunlu tüketici haklarına göre incelenebileceğini belirtiyor.", en: "The company's July 10 terms say prior purchases may be reviewed under the guarantee terms shown at purchase and mandatory consumer rights." } },
  { id: "guarantee", state: "user_allegation", eventDate: "2026-07-08", sourceUrl: "https://eksisozluk.com/entry/184941413", responseUrl: "https://xpatla.com/platform-integrity", summary: { tr: "Ekşi Sözlük'te bir kullanıcı, satın alma sırasında gördüğü iptal/iade mesajı ile daha sonra karşılaştığı şartların farklı olduğunu ileri sürdü. Bu, kullanıcı beyanıdır; bağımsız teyit veya hukuki karar değildir.", en: "An Ekşi Sözlük user alleged that cancellation/refund messaging at purchase differed from terms encountered later. This is a user account, not independent verification or a legal finding." }, response: { tr: "Şirket, garanti koşullarının satın alma öncesinde daha görünür hale getirildiğini; 30 günlük sonuç garantisinin koşullu olduğunu söylüyor.", en: "The company says guarantee conditions have been made more visible before purchase and that the 30-day results guarantee is conditional." } },
] as const;

export const evidenceStates: EvidenceState[] = ["verified", "vendor_claim", "user_allegation", "unverified", "superseded"];
